"""Original curriculum notes for a two-hour companion course.

Chapter names follow the publisher's public course catalogue, not copied book text.
Each chapter becomes five short, narration-synchronised cuts (foundation, system,
practice, failure mode, and application), keeping every visual beat below 90 seconds.
"""
from textwrap import dedent

RAW = [
 ("Agentic Engineering Orientation", "why an agent is a probabilistic system with consequences, not a chatbot", ["define an accountable outcome", "separate capability from authority", "make failure visible"], "demo-first thinking", "a claims agent that may draft but not submit a payment"),
 ("Agent Runtime Environment", "the bounded environment in which an agent receives context, invokes tools, and records state", ["execution boundary", "tool contracts", "durable state"], "letting a model call production systems directly", "a support agent whose actions pass through a controlled runtime"),
 ("Agentic Security Engineering", "protecting instructions, data, tools, and identities across an autonomous loop", ["least privilege", "prompt-injection resistance", "action authorization"], "treating text input as trusted", "a procurement agent rejecting a malicious vendor document"),
 ("Agentic Observability Engineering", "making uncertain decisions inspectable through traces, metrics, and evidence", ["trace every decision", "measure outcomes", "retain evidence"], "only logging final answers", "an incident timeline that exposes a faulty tool call"),
 ("Agentic Protocol Engineering", "the contracts that let agents, tools, and services exchange intent safely", ["typed messages", "capability discovery", "versioned contracts"], "implicit assumptions between services", "a travel agent negotiating availability through explicit tool schemas"),
 ("Agentic Governance Engineering", "encoding policy, accountability, and review into the operating system", ["policy as executable control", "risk tiers", "audit ownership"], "governance as a document after launch", "a loan workflow requiring approval above a delegated limit"),
 ("Agentic Knowledge Engineering", "turning enterprise knowledge into grounded, maintained, permissioned evidence", ["source quality", "knowledge freshness", "provenance"], "indexing every document without curation", "a medical assistant retrieving only approved clinical guidance"),
 ("Agentic Context Engineering", "constructing the right briefing packet for each model call", ["relevance", "structured context", "context pruning"], "context bloat", "a contract reviewer receiving only liability clauses and policy"),
 ("Agentic Memory Engineering", "choosing what an agent remembers, for how long, and with what confidence", ["working memory", "long-term memory", "memory hygiene"], "persisting unverified model claims", "a concierge remembering preferences but expiring old travel plans"),
 ("Agentic Reasoning Engineering", "designing plans, checks, and reflection without confusing verbosity for intelligence", ["decompose goals", "verify intermediate work", "stop conditions"], "unbounded self-reflection loops", "an analyst agent testing its calculation before presenting a recommendation"),
 ("Agentic Model Engineering", "matching models, prompts, and deterministic components to each task", ["model routing", "structured outputs", "evaluation-driven selection"], "using one expensive model for everything", "a pipeline using rules for validation and a model for ambiguous language"),
 ("Agentic Orchestration Engineering", "coordinating specialist steps while preserving handoffs, state, and control", ["workflow graph", "specialist roles", "recovery paths"], "a swarm without ownership", "a planner delegating research and synthesis with a final verifier"),
 ("Agentic System Design", "designing the whole socio-technical system around goals, boundaries, and failure", ["system boundaries", "non-model safeguards", "escalation design"], "starting with a framework instead of a problem", "a customer operations agent with explicit no-go zones"),
 ("Agentic UX Engineering", "showing intent, progress, uncertainty, and controls so people can collaborate", ["transparent state", "reversible actions", "appropriate autonomy"], "a chat box that hides side effects", "a finance assistant previewing a transfer before approval"),
 ("Agentic Integration Engineering", "connecting agents to real systems through stable interfaces and reliable side effects", ["idempotency", "data contracts", "compensation actions"], "assuming a tool call succeeds once", "an order agent safely retrying a shipment update"),
 ("Agentic Cognition Engineering", "closing the loop among perception, deliberation, action, and reflection", ["observe", "decide and act", "learn within bounds"], "treating a chain of prompts as cognition", "a maintenance agent updating its plan after a sensor anomaly"),
 ("Agentic Trust Engineering", "combining reliability, safety, transparency, and recourse into earned confidence", ["calibrated confidence", "human recourse", "trust evidence"], "claiming trust without measurement", "an HR agent citing policy and routing edge cases to a reviewer"),
 ("AgentOps Engineering", "operating agent fleets through tests, monitoring, cost control, and safe rollout", ["evaluation gates", "production telemetry", "rollback and iteration"], "shipping once and watching complaints", "a release gate blocking a regression in tool selection"),
 ("Agentic Quality Assurance", "testing behavior, decisions, tools, and harmful edge cases before and after deployment", ["scenario suites", "adversarial tests", "quality thresholds"], "testing only happy-path answers", "a red-team suite for prompt injection and authorization bypass"),
 ("Agentic System Development Lifecycle", "extending product delivery from requirements through operations and retirement", ["risk-aware discovery", "continuous evaluation", "change governance"], "treating prompts as unversioned configuration", "a lifecycle that versions prompts, tools, tests, and policies together"),
 ("Agentic Product Management", "choosing valuable jobs, autonomy levels, and success measures for people and business", ["job to be done", "autonomy ladder", "outcome metrics"], "optimizing engagement instead of task success", "a service desk agent measured by resolved work and safe handoffs"),
 ("Agentic Team and Organization Design", "assigning ownership, expertise, and decision rights across humans and agents", ["clear accountability", "cross-functional operating model", "skill development"], "creating an agent team without an accountable human team", "a product squad with model, security, operations, and domain owners"),
 ("Agentic AI Maturity and Operating System", "assessing capability honestly and building the controls required for the next level", ["maturity criteria", "operating cadence", "evidence-based progression"], "calling a prototype enterprise-ready", "a staged path from supervised pilot to governed production"),
 ("AI-Native Transformation", "redesigning work and organizations around accountable intelligence rather than adding a chatbot", ["workflow redesign", "portfolio learning", "responsible scaling"], "automating a broken process", "a claims operation rebuilt around human judgment and machine preparation"),
]

def words(s): return len(s.replace("[pause]", "").split())

def script(title, focus, concepts, trap, example, beat):
    c1, c2, c3 = concepts
    templates = {
      "foundation": f"Welcome to {title}. This chapter is about {focus}. The important shift is simple: a capable model is not yet a dependable system. [pause] Engineering begins when we state the outcome, the people affected, and the evidence needed to judge success. Start with {c1}. Then make {c2} explicit. Finally, treat {c3} as a design requirement, not a future enhancement. [pause] Think about the difference between a fluent answer and a useful action. A useful action has a purpose, a boundary, and a way to be checked. That is the lens for every idea in this chapter. Keep it close as we move from principle to implementation.",
      "system": f"Now turn the principle into a system. For {title}, map the loop from input to decision to action to evidence. At each handoff, ask what information is allowed in, what the component may do, and what record must remain afterward. [pause] The first design choice is {c1}. The second is {c2}. The third is {c3}. These are connected, not separate checkboxes. If one is vague, uncertainty leaks into the next stage. A production team should be able to draw this loop, name its owners, and explain what happens when a dependency is missing. That clarity makes the system easier to evolve and much safer to operate.",
      "practice": f"Here is a practical way to apply {title}. Begin with a narrow job and write a scenario where success is observable. Use the example of {example}. [pause] Define the available inputs, the allowed tools, the expected output, and the human decision that remains outside the agent. Then instrument the path. Capture the evidence that supported the recommendation and the result of any action. Next, run representative cases and inspect failures before widening scope. This practice is deliberately less dramatic than a fully autonomous demo. It is also how reliable systems are built: start with a bounded workflow, learn from real behavior, and expand authority only when the evidence supports it.",
      "failure": f"The common failure in {title} is {trap}. That mistake looks efficient because it removes friction early. In production, it usually creates invisible risk. [pause] Counter it with three questions. What assumption is the system making? What signal would reveal that the assumption is wrong? And what safe action should follow? The answers should be encoded in interfaces, tests, and operating procedures, not left in a team member's memory. Notice the pattern: the goal is not to eliminate uncertainty. Language models will remain uncertain. The goal is to make uncertainty legible, bounded, and recoverable before it becomes customer harm or operational debt.",
      "evaluation": f"Before expanding this capability, evaluate {title} as a behavior, not just an answer. Build a small scenario set around {example}. Include normal cases, incomplete inputs, conflicting instructions, and a case where the correct outcome is to stop. [pause] Score task success, the use of {c1}, and whether {c2} was preserved. Review the traces with people who understand the domain. Their feedback should change the workflow, the controls, or the user experience. This turns quality from an argument into an engineering loop. A passing demo is only a starting point. Evidence across representative situations is what earns the right to increase autonomy.",
      "handoff": f"Finally, consider the human handoff in {title}. A mature agent does not merely escalate a vague problem. It passes along the goal, relevant evidence, actions already attempted, and the reason it stopped. [pause] That package protects the next person from repeating work and lets them make a better decision. It also makes {c3} operational: the team can inspect whether the agent delegated at the right moment. Design the handoff early, even when a pilot is small. It forces clarity about authority and gives users a reliable way back into the loop when judgment, empathy, or accountability cannot be automated.",
      "application": f"Let's close {title} with an operating checklist. First, make {c1} concrete for one workflow. Second, verify {c2} through a realistic evaluation case. Third, preserve {c3} as part of the system record. [pause] Use {example} as the mental model. The agent should help people move faster, while its authority remains proportional to the evidence and risk. Review outcomes regularly, including the cases where the agent abstained or escalated. That is a sign of maturity, not weakness. The takeaway is this: {focus}. When that principle is built into the loop, the agent becomes easier to trust, improve, and scale responsibly.",
    }
    return dedent(templates[beat]).replace("\n", " ").strip()

BEATS = ["foundation", "system", "practice", "failure", "evaluation", "handoff", "application"]
CHAPTERS = []
for n, (title, focus, concepts, trap, example) in enumerate(RAW, 1):
    segments = []
    for beat in BEATS:
        segments.append({"id": beat, "variant": "aae_chapter", "props": {"chapter": n, "title": title, "focus": focus, "concepts": concepts, "example": example, "trap": trap, "takeaway": focus.capitalize() + ".", "beat": beat}, "narration": script(title, focus, concepts, trap, example, beat)})
    CHAPTERS.append({"id": f"ch{n:02d}", "number": n, "title": title, "focus": focus, "segments": segments})

if __name__ == "__main__":
    total = sum(words(s["narration"]) for c in CHAPTERS for s in c["segments"])
    print(f"{len(CHAPTERS)} chapters; {total} narration words; estimated {total / 165:.1f} min at educational pace")
