"""Transformative chapter-by-chapter screenplay based on the supplied 2017 book.

Visual identity (provided by FAScenes): financial slate + ledger-tape motif.
Semantics: sky=business/cash in, green=quality/protective action, violet=price and
valuation, amber=debt/caution, coral=loss/risk. Every scene is duration-phased by
the fa scene set, with a progress bar and continuous background motion.
"""
REV = "#38BDF8"; RISK = "#F87171"; GOOD = "#34D399"; VALUE = "#A78BFA"; DEBT = "#FBBF24"; TEAL = "#2DD4BF"; GRAY = "#8B93B0"

def D(n, title, sub, color):
    return ("divider", "fa_divider", {"n": n, "total": 11, "title": title, "sub": sub, "color": color},
        f"Chapter {n}. {title}. [pause] {sub}.")
def K(sid, kicker, big, sub, color, narration):
    return (sid, "fa_keyidea", {"kicker": kicker, "big": big, "sub": sub, "color": color}, narration)
def C(sid, kicker, title, cos, note, color, narration):
    return (sid, "fa_compare", {"kicker": kicker, "title": title, "cos": cos, "note": note, "color": color}, narration)
def B(sid, kicker, title, bars, note, color, narration):
    return (sid, "fa_bars", {"kicker": kicker, "title": title, "bars": bars, "note": note, "color": color, "decimals": 0}, narration)
def G(sid, kicker, title, value, unit, zones, caption, note, color, narration):
    return (sid, "fa_gauge", {"kicker": kicker, "title": title, "value": value, "unit": unit, "zones": zones, "caption": caption, "note": note, "color": color}, narration)
def L(sid, kicker, title, rows, caption, color, narration):
    return (sid, "fa_ledger", {"kicker": kicker, "title": title, "rows": rows, "caption": caption, "color": color}, narration)

CHAPTERS = [
{"id":"ch01", "title":"Avoiding Loss", "segments":[
 ("title", "fa_title", {"kicker":"INDIAN EQUITY EDUCATION · BOOK GUIDE", "line1":"Avoid Loss and", "line2":"Invest Consistently", "sub":"An 11-chapter practical framework, adapted from the supplied 2017 book", "color":TEAL},
  "A falling stock quote can feel like a verdict. [pause] But a quote is only one signal. This video turns a practical Indian investing book into a clear decision framework. [pause] It is educational information, not investment advice. For personal decisions, consult a SEBI-registered adviser."),
 ("roadmap", "fa_roadmap", {"kicker":"THE COMPLETE MAP · ELEVEN CHAPTERS", "parts":[
    {"n":1,"title":"Avoiding loss","sub":"ownership, process, capital protection","c":RISK},
    {"n":2,"title":"The real risk","sub":"purchasing power and preparation","c":DEBT},
    {"n":3,"title":"Business quality","sub":"returns, moat, and debt","c":GOOD},
    {"n":4,"title":"Management","sub":"evidence over stories","c":TEAL},
    {"n":5,"title":"Valuation","sub":"great business, sensible price","c":VALUE},
    {"n":6,"title":"Buy and sell","sub":"thesis-led decisions","c":REV},
    {"n":7,"title":"Behaviour","sub":"avoid self-inflicted errors","c":RISK}], "color":TEAL},
  "Here is the first half of the map. [pause] We begin with capital protection. Then learn to judge business quality, management, and valuation. [pause] Next comes buying, selling, and the emotional errors that undo otherwise sound analysis. The later chapters finish the map with portfolio construction, adviser due diligence, a screen, and long-term habits."),
 D(1,"Avoiding loss","Stocks are ownership claims, not lottery tickets.",RISK),
 K("ownership","FIRST PRINCIPLE · OWNERSHIP","A share is a small ownership claim on a real business — not a number to gamble on.","Your job is to assess the business and the price, then give the thesis time.",TEAL,
  "The book starts by challenging the gambling label. [pause] Buying a share means owning a tiny claim on a business: its assets, its future cash flows, and its risks. A short-term price move can be noisy. Business performance is what ultimately gives ownership value. [pause] That does not remove risk. It changes the question from, can I guess tomorrow, to, do I understand what I own?"),
 C("loss_loop","WHY MOST PEOPLE LOSE","A process separates investing from tip-chasing",[
  {"name":"Impulse", "c":RISK, "tag":"fragile", "stats":[{"k":"Input","v":"a hot tip"},{"k":"Focus","v":"today's quote"},{"k":"Action","v":"panic / chase"},{"k":"Result","v":"no thesis","hot":True}]},
  {"name":"Process", "c":GOOD, "tag":"repeatable", "stats":[{"k":"Input","v":"business evidence"},{"k":"Focus","v":"value and risk"},{"k":"Action","v":"written thesis"},{"k":"Result","v":"reviewable","hot":True}]},
 ],"The book's central order: protect capital first; seek return second.",TEAL,
  "The book's diagnosis is behavioural. Many retail participants act on free tips, headlines, and excitement. [pause] The alternative is a written process. Record why this business is attractive, what could disprove that view, what price makes sense, and how large the position may be. [pause] A process cannot promise gains. It makes errors visible before they become permanent losses."),
 K("protect","CAPITAL PROTECTION","The first return is avoiding permanent loss. Diversify, understand, and refuse what you cannot explain.","A loss on paper and a broken investment thesis are different events.",GOOD,
  "Capital protection is not hiding from all volatility. [pause] It is avoiding businesses you do not understand, excessive leverage, concentrated bets, and prices that require perfection. The book's recurring message is simple: do not make a large decision while confused. [pause] Make smaller, researched decisions. Review the thesis when facts change, rather than reacting to every red or green tick."),
]},
{"id":"ch02", "title":"The Real Risk", "segments":[
 D(2,"The real risk","Volatility is visible; loss of purchasing power is quieter.",DEBT),
 K("purchasing_power","PURCHASING POWER","Cash that grows slower than your future costs can lose real buying power.","This is a concept, not a claim about any current deposit rate or inflation rate.",DEBT,
  "This chapter reframes risk. [pause] A bank balance may stay numerically stable, yet buy less over time if living costs rise faster than its after-tax growth. That is purchasing-power risk. [pause] Equities can be volatile, but ownership in productive businesses may help a long-term portfolio participate in economic growth. The right comparison is not safe versus risky. It is which risks you are taking, for how long, and with what safeguards."),
 C("risk_layers","TWO KINDS OF RISK","Separate normal fluctuation from a genuine threat to capital",[
  {"name":"Price volatility", "c":DEBT, "tag":"visible", "stats":[{"k":"What moves?","v":"market quote"},{"k":"Time horizon","v":"days to months"},{"k":"Question","v":"has the thesis changed?"},{"k":"Response","v":"review facts","hot":True}]},
  {"name":"Permanent loss", "c":RISK, "tag":"fundamental", "stats":[{"k":"What breaks?","v":"business economics"},{"k":"Signals","v":"debt, fraud, decline"},{"k":"Question","v":"was the thesis wrong?"},{"k":"Response","v":"reduce or exit","hot":True}]},
 ],"A falling price alone is not proof; unchanged facts are not a guarantee either.",DEBT,
  "The book distinguishes a market decline from a damaged business. [pause] Price volatility is normal: markets re-price expectations every day. Permanent loss is different. It can follow from weak economics, unsustainable debt, dishonest management, or paying an extreme price. [pause] This is why an investor needs a thesis. Without one, every fall feels identical. With one, you can ask the only useful question: what changed in the business?"),
 K("learn_basics","THE INVESTOR'S EDGE","Knowledge is a risk-control tool: learn statements, incentives, valuation, and position sizing.","Start small enough that learning mistakes are affordable.",GOOD,
  "The chapter also makes a practical case for learning the basics before committing serious savings. [pause] Know the difference between a business, a stock, a price, and a return. Read annual reports. Learn what debt does in a downturn. Learn why diversification matters. [pause] Education does not create certainty. It reduces the chance that someone else's confidence becomes your unexamined risk."),
]},
{"id":"ch03", "title":"Picking Winning Stocks", "segments":[
 D(3,"Business quality","Start with economic quality before chasing growth.",GOOD),
 G("roe","RETURN ON EQUITY","High ROE can signal that a business converts owners' capital into profit efficiently.",20,"%",[{"to":10,"c":RISK,"label":"weak"},{"to":20,"c":DEBT,"label":"watch"},{"to":40,"c":GOOD,"label":"strong"}],"Use several years and compare with the business model.","ROE must be read beside debt; leverage can artificially lift it.",GOOD,
  "The book puts return on equity, or R O E, near the start of analysis. [pause] In plain English, it asks how much profit a company earns from shareholders' capital. A sustained high return can be a clue to a strong business. [pause] But it is a clue, not a verdict. Borrowing can inflate returns on equity. So the investor must pair R O E with debt, cash flow, margins, and competitive advantage."),
 C("moat","ECONOMIC MOAT","Ask why customers choose this business over alternatives",[
  {"name":"Durable edge", "c":GOOD, "tag":"look for", "stats":[{"k":"Source","v":"brand / cost / network"},{"k":"Customer","v":"returns again"},{"k":"Economics","v":"pricing power"},{"k":"Evidence","v":"sustained returns","hot":True}]},
  {"name":"Commodity trap", "c":RISK, "tag":"be careful", "stats":[{"k":"Source","v":"no clear difference"},{"k":"Customer","v":"buys cheapest"},{"k":"Economics","v":"thin margins"},{"k":"Evidence","v":"cyclical profits","hot":True}]},
 ],"A moat is an economic explanation, not a fashionable label.",GOOD,
  "Next is the economic moat: the reason a business can defend profits. [pause] It could be a trusted brand, low-cost production, distribution, switching costs, or a network effect. The test is practical. Why would a customer keep choosing this company if competitors try harder? [pause] A good story is not enough. Look for evidence in margins, returns, market position, and the durability of cash generation."),
 L("debt","DEBT CHECK","Debt can magnify a good business — and accelerate a bad outcome",[
  {"label":"Debt to equity", "val":"How much borrowing?", "c":DEBT, "bold":True},
  {"label":"Interest coverage", "val":"Can operating profit pay interest?", "c":GOOD},
  {"label":"Current ratio", "val":"Can near-term bills be paid?", "c":REV},
  {"label":"Cash flow", "val":"Does cash support reported profit?", "c":TEAL},
 ],"Read a multi-year trend; one ratio alone never tells the whole story.",DEBT,
  "Debt is the book's danger word. [pause] Debt can fund productive assets, but it also creates fixed obligations. When business conditions weaken, interest still has to be paid. Review debt-to-equity, interest coverage, liquidity, maturity schedules, and whether operating cash flow supports profits. [pause] The important question is not simply, does debt exist? It is, can this business service it comfortably across a difficult cycle?"),
]},
{"id":"ch04", "title":"Evaluating Management", "segments":[
 D(4,"Management quality","Use public evidence, not charisma or access.",TEAL),
 C("evidence","EVIDENCE OVER PROMISES","Retail investors can evaluate incentives without private meetings",[
  {"name":"What leaders say", "c":DEBT, "tag":"starting point", "stats":[{"k":"Source","v":"interviews / calls"},{"k":"Risk","v":"selective story"},{"k":"Use","v":"form questions"},{"k":"Never use","v":"as proof","hot":True}]},
  {"name":"What records show", "c":GOOD, "tag":"stronger", "stats":[{"k":"Source","v":"filings / actions"},{"k":"Signals","v":"ownership, capital use"},{"k":"Use","v":"test consistency"},{"k":"Best evidence","v":"multi-year record","hot":True}]},
 ],"Conference calls and annual reports can be more useful than an impression from a meeting.",TEAL,
  "The book is realistic about access. Most small investors cannot meet every management team. [pause] More useful sources are public filings, annual reports, shareholding patterns, conference calls, and corporate actions. Listen to management, but do not confuse polished communication with quality. [pause] Compare words against outcomes: capital allocation, related-party disclosures, debt, dilution, dividends, and whether past promises were met."),
 L("ownership","SHAREHOLDING PATTERN","Ownership changes can reveal incentives — but require context",[
  {"label":"Promoter holding", "val":"alignment and control", "c":TEAL, "bold":True},
  {"label":"Promoter pledge", "val":"financing risk to inspect", "c":RISK},
  {"label":"Buybacks / dilution", "val":"capital allocation clues", "c":VALUE},
  {"label":"Related-party deals", "val":"governance clue", "c":DEBT},
 ],"No single item proves quality. Look for patterns and explanations across time.",TEAL,
  "Shareholding is one window into incentives. [pause] Promoter ownership can align leaders with shareholders, but it is not a guarantee. A high pledge of promoter shares deserves careful attention because falling prices can create financing stress. Buybacks, frequent dilution, and related-party transactions also need context. [pause] The aim is not to find one magic signal. It is to see whether actions consistently protect, or dilute, minority shareholders."),
 K("capital_allocation","CAPITAL ALLOCATION","Judge management by what it does with each rupee: reinvest, repay debt, acquire, dividend, or dilute.","A strong record turns retained earnings into more durable owner value.",GOOD,
  "The chapter's deepest test is capital allocation. [pause] When a company earns cash, management decides where it goes. It can expand a high-return business, repay expensive debt, make an acquisition, distribute a dividend, buy back shares, or waste it. [pause] Follow the record across several years. Good governance and good economics reinforce each other when leaders explain decisions clearly and deploy capital for long-term value rather than short-term appearances."),
]},
{"id":"ch05", "title":"Valuation", "segments":[
 D(5,"Valuation matters","A great business can still be a poor investment at an extreme price.",VALUE),
 C("quality_price","QUALITY IS NOT PRICE","The business and the stock are related, but not identical",[
  {"name":"Business quality", "c":GOOD, "tag":"what you own", "stats":[{"k":"Ask","v":"is it durable?"},{"k":"Evidence","v":"returns, cash, moat"},{"k":"Time","v":"many years"},{"k":"Can be","v":"excellent","hot":True}]},
  {"name":"Valuation", "c":VALUE, "tag":"what you pay", "stats":[{"k":"Ask","v":"what is priced in?"},{"k":"Evidence","v":"multiples, cash flow"},{"k":"Time","v":"entry point"},{"k":"Can be","v":"too expensive","hot":True}]},
 ],"The book uses historical examples to show that a quality name can disappoint after euphoric pricing.",VALUE,
  "This chapter supplies a crucial correction to quality-only investing. [pause] A superb business can still be a disappointing investment if the purchase price already assumes years of perfect growth. The book illustrates this with historical episodes of strong companies bought during very high valuations. [pause] The lesson is timeless: separate the quality of the business from the price of the stock. You need both a durable enterprise and a sensible expectation embedded in the price."),
 G("multiple","VALUATION MULTIPLES","A multiple is a shorthand for how much the market asks for a unit of earnings or cash flow.",25,"x",[{"to":15,"c":GOOD,"label":"lower"},{"to":30,"c":DEBT,"label":"context"},{"to":50,"c":RISK,"label":"higher"}],"There is no universal 'good P/E'; growth, returns, debt, and cycle matter.","Compare against the company's own history and relevant peers, never in isolation.",VALUE,
  "Price-to-earnings, price-to-book, enterprise value to EBITDA, and free-cash-flow yield are tools, not automatic answers. [pause] A high multiple may be justified by stronger growth, higher returns, or a cleaner balance sheet. It may also reflect excitement that cannot last. [pause] Compare a company with its own history, similar businesses, and the economics behind the number. A valuation ratio is useful only when connected to the quality and durability of the underlying earnings."),
 K("margin_safety","MARGIN OF SAFETY","Demand room for error: conservative assumptions, balance-sheet strength, and a price that does not require perfection.","Valuation is an exercise in humility, not a precise forecast of one future.",GOOD,
  "The practical output is a margin of safety. [pause] Your forecast will be incomplete. Growth may slow, costs may rise, or a cycle may turn. So avoid paying a price that works only if everything goes right. Seek financial strength, understandable cash generation, and assumptions you can defend. [pause] This does not mean waiting for a mathematically perfect bargain. It means recognising that price is part of risk control."),
]},
{"id":"ch06", "title":"When to Buy and Sell", "segments":[
 D(6,"Buy and sell discipline","Let changes in value and fundamentals drive decisions, not your average cost.",REV),
 B("stagger","BUILDING A POSITION","Staggering can reduce timing dependence when a thesis is intact",[
  {"label":"Research", "val":1, "c":TEAL, "note":"understand"},
  {"label":"First buy", "val":2, "c":REV, "note":"start"},
  {"label":"Review", "val":3, "c":DEBT, "note":"new facts"},
  {"label":"Add or stop", "val":4, "c":GOOD, "note":"thesis-led"},
 ],"Illustrative sequence only. Position size must fit personal risk capacity.",REV,
  "The book rejects the idea that a single purchase price should control every later decision. [pause] A position can be built gradually when the business case is understood and new information supports it. The opposite is also true: do not average down merely because a price fell. [pause] Review fundamentals, valuation, concentration, and the original thesis. Staggering is a risk-management technique, not a guarantee and not a substitute for analysis."),
 C("sell","SIX REASONS TO REVISIT","A sell decision should have a business reason",[
  {"name":"Thesis improved?", "c":GOOD, "tag":"hold / add", "stats":[{"k":"Fundamentals","v":"intact or stronger"},{"k":"Valuation","v":"still reasonable"},{"k":"Capital need","v":"covered elsewhere"},{"k":"Action","v":"review calmly","hot":True}]},
  {"name":"Thesis weakened?", "c":RISK, "tag":"reduce / exit", "stats":[{"k":"Fundamentals","v":"material deterioration"},{"k":"Management","v":"governance concern"},{"k":"Valuation","v":"extreme vs facts"},{"k":"Action","v":"reallocate rationally","hot":True}]},
 ],"The book also names better opportunities and predefined exit criteria as valid inputs.",REV,
  "Selling deserves as much thought as buying. [pause] The book lists several triggers: a better opportunity, an original error, over-stretched valuation, a change in fundamentals, or a change in management. Define these conditions before emotion takes over. [pause] Do not sell simply to get back to your purchase price. The market does not know your cost. The relevant question is: from today, is this still the best use of this capital at this risk?"),
 K("exit_plan","PREDEFINED EXIT PLAN","Write what would invalidate the thesis before the position becomes emotionally important.","A plan makes it easier to distinguish new evidence from temporary noise.",GOOD,
  "An exit plan is not a mechanical stop-loss number for every investor. [pause] It is a list of facts that would make your original reasoning false. For example: worsening balance-sheet quality, a lost competitive advantage, management behaviour that breaks trust, or valuation that far outruns plausible business outcomes. [pause] Write it while calm. Then revisit it when new information arrives. This reduces the chance of holding a broken thesis merely because selling feels painful."),
]},
{"id":"ch07", "title":"Do's and Don'ts", "segments":[
 D(7,"Avoid self-inflicted errors","Daily price fixation, anchoring, and forecasts can sabotage good analysis.",RISK),
 K("daily","PRICE IS A SIGNAL, NOT A COMMAND","Checking quotes constantly can turn normal volatility into needless action.","Match your review frequency to your investment horizon and the arrival of material facts.",RISK,
  "The book warns against compulsive quote-checking. [pause] If the intended holding period is years, a noisy daily chart often contributes more emotion than insight. This does not mean ignore a company. Follow results, balance-sheet changes, governance events, and industry facts. [pause] It means give attention to information that changes value, not merely to information that changes colour on a screen."),
 C("anchor","THE ANCHORING TRAP","Your purchase price is history, not an investment thesis",[
  {"name":"Anchored investor", "c":RISK, "tag":"backward-looking", "stats":[{"k":"Question","v":"when do I break even?"},{"k":"Focus","v":"my cost"},{"k":"Risk","v":"holds weak thesis"},{"k":"Decision","v":"emotional","hot":True}]},
  {"name":"Rational investor", "c":GOOD, "tag":"forward-looking", "stats":[{"k":"Question","v":"what is it worth now?"},{"k":"Focus","v":"future cash flows"},{"k":"Risk","v":"tests thesis"},{"k":"Decision","v":"evidence-led","hot":True}]},
 ],"The market does not know the price you paid.",RISK,
  "Another warning is anchoring. [pause] Investors often treat their entry price as a target, holding a weak company until they can get back to even, or refusing to buy a stronger company because it trades above a past price. The market has no memory of your cost. [pause] Reassess from today. What are the business prospects? What is the valuation? What alternatives exist? That forward-looking frame is more useful than trying to erase a feeling attached to a past transaction."),
 K("bear","BEAR MARKETS","A broad decline is not a forecastable timetable; prepare with quality, liquidity, and patience.","Do not panic-sell everything or assume every falling stock is a bargain.",DEBT,
  "The book argues that trying to forecast each market turn is a poor foundation for long-term investing. [pause] In a broad decline, avoid panic and avoid heroics. Check whether businesses remain financially sound. Keep enough liquidity for your real-life needs. Do not confuse a falling index with proof that every company is cheap. [pause] A bear market can create opportunity, but only for investors with research, diversification, and the emotional capacity to follow their process."),
]},
{"id":"ch08", "title":"Portfolio Construction", "segments":[
 D(8,"Build the portfolio","Diversification is about independent risks, not the largest possible stock count.",TEAL),
 C("diversify","DIVERSIFIED OR JUST CROWDED?","Count distinct economic exposures, not merely ticker symbols",[
  {"name":"Diversified", "c":GOOD, "tag":"intentional", "stats":[{"k":"Businesses","v":"understood"},{"k":"Drivers","v":"not all identical"},{"k":"Weights","v":"deliberate"},{"k":"Review","v":"manageable","hot":True}]},
  {"name":"Over-diversified", "c":RISK, "tag":"crowded", "stats":[{"k":"Businesses","v":"too many to follow"},{"k":"Drivers","v":"hidden overlap"},{"k":"Weights","v":"accidental"},{"k":"Review","v":"impossible","hot":True}]},
 ],"The book's point: a large number of holdings can hide a weak portfolio.",TEAL,
  "Portfolio construction is more than selecting individual names. [pause] The book cautions that holding dozens of shares is not automatically diversification. Twenty companies tied to the same economic driver can fall together. A very large list can also prevent thoughtful monitoring. [pause] Think in exposures: sector, cyclicality, leverage, customer type, and business model. Own a number of positions you can actually understand and review."),
 B("allocation","POSITION SIZING","Weights determine how much a correct or incorrect thesis matters",[
  {"label":"Highest conviction", "val":10, "c":GOOD, "note":"still capped"},
  {"label":"Medium conviction", "val":7, "c":TEAL, "note":"evidence"},
  {"label":"Early / uncertain", "val":4, "c":DEBT, "note":"learn"},
  {"label":"Speculative", "val":1, "c":RISK, "note":"avoid or tiny"},
 ],"Illustrative weights, not a personal allocation recommendation.",TEAL,
  "Position sizing turns analysis into real-world risk. [pause] A sound thesis held in an excessive weight can still damage a portfolio. Give more room only where your evidence and understanding are strongest, and maintain limits so a single mistake does not define the outcome. [pause] Review correlation as well as conviction. Several apparently different companies may depend on the same interest rate, commodity price, or consumer cycle."),
 K("crash","DURING A CRASH","Separate a market-wide drawdown from a broken company; keep a cash plan for real-life needs.","Preparation before stress is more useful than predictions during stress.",DEBT,
  "The chapter closes on market crashes. [pause] The book advises against liquidating everything in panic and against pretending to know the bottom. Instead, separate financial needs from investable capital, preserve liquidity, and reassess quality. A serious decline can expose leverage and weak governance. [pause] It can also make durable businesses cheaper. The disciplined response depends on facts, position size, and your capacity to hold — not on headlines alone."),
]},
{"id":"ch09", "title":"Advisers and Direct Equity", "segments":[
 D(9,"Choose help carefully","Adviser, fund, or direct investing: match the route to your knowledge and time.",VALUE),
 C("routes","THREE WAYS TO PARTICIPATE","The best vehicle depends on your ability to evaluate and monitor risk",[
  {"name":"Direct equity", "c":TEAL, "tag":"hands-on", "stats":[{"k":"Needs","v":"time and skill"},{"k":"Control","v":"high"},{"k":"Work","v":"research / review"},{"k":"Risk","v":"self-directed","hot":True}]},
  {"name":"Fund / adviser", "c":GOOD, "tag":"delegated", "stats":[{"k":"Needs","v":"due diligence"},{"k":"Control","v":"lower"},{"k":"Work","v":"choose and monitor"},{"k":"Risk","v":"manager / fees","hot":True}]},
 ],"Neither route removes risk; both require informed monitoring.",VALUE,
  "The book asks a good question: do you truly need an equity adviser? [pause] Direct equity demands time, interest, and the ability to read disclosures. A mutual fund or professional adviser can be appropriate when you need delegation, but delegation is not abdication. [pause] Understand the mandate, fees, conflicts, risk style, and what you will monitor. The right route is the one you can follow responsibly, not the one promising the quickest result."),
 L("advisor_check","ADVISER DUE DILIGENCE","Questions to ask before trusting financial guidance",[
  {"label":"Registration", "val":"verify SEBI registration", "c":GOOD, "bold":True},
  {"label":"Method", "val":"can they explain the logic?", "c":TEAL},
  {"label":"Claims", "val":"avoid 'guaranteed' returns", "c":RISK},
  {"label":"Conflicts / fees", "val":"understand incentives", "c":DEBT},
  {"label":"Record", "val":"check independently", "c":VALUE},
 ],"Use official registries and current disclosures before acting.",VALUE,
  "The book warns that the internet makes it easy to manufacture authority. [pause] A professional-looking page, a chat group, or a claimed success rate is not evidence. Verify whether a person is appropriately registered with SEBI for the service offered. Ask how decisions are made, how fees work, and whether conflicts exist. [pause] Be especially wary of guaranteed returns, jackpot calls, pressure tactics, and advice that cannot explain its own risk."),
 K("accountability","KEEP ACCOUNTABILITY","Even with advice, understand the thesis, the downside, and the reason you own each position.","Outsourcing a decision does not outsource its consequence.",GOOD,
  "The practical conclusion is accountability. [pause] You may use a fund, an adviser, or direct equities. In every case, know what the strategy owns, what could go wrong, and how success will be evaluated. A credible professional should welcome clear questions about logic and risk. [pause] If you cannot explain why money is invested, the position is too opaque to manage responsibly."),
]},
{"id":"ch10", "title":"Quick Formula", "segments":[
 D(10,"A quick screen","A screen narrows the research list; it never replaces full analysis.",GOOD),
 L("screen","THE BOOK'S INITIAL SCREEN","Use a multi-factor filter to find candidates for deeper work",[
  {"label":"Average ROE and ROCE", "val":"above 20%", "c":GOOD, "bold":True},
  {"label":"Debt to equity", "val":"below 1 or improving", "c":DEBT},
  {"label":"Promoter pledge", "val":"low / falling", "c":RISK},
  {"label":"Sales growth", "val":"3-year CAGR > 10%", "c":REV},
  {"label":"Profit growth", "val":"3-year CAGR > 12%", "c":GOOD},
 ],"These are the book's 2017 screening thresholds, presented as a historical educational framework, not current advice.",GOOD,
  "The book offers a quick formula as a starting screen. [pause] It combines three-year returns on equity and capital employed above twenty percent, debt-to-equity below one or falling, low promoter pledging, and positive three-year sales and profit growth thresholds. [pause] Treat these numbers as the author's historical framework, not as a universal rule or a buy list. A screen is designed to reduce thousands of companies to a research shortlist."),
 G("red_flags","TWO-MINUTE RED FLAGS","The book's fast rejection test looks for weak returns, high debt, and high pledging",30,"%",[{"to":10,"c":GOOD,"label":"lower"},{"to":30,"c":DEBT,"label":"inspect"},{"to":60,"c":RISK,"label":"risk"}],"Promoter pledge is one clue; combine it with cash flow, debt terms, and governance evidence.","Banking and NBFCs need sector-specific analysis; the book flags this limitation.",RISK,
  "The companion fast check asks whether returns are persistently weak, debt remains high, or promoter shares are heavily pledged. [pause] One red flag is an invitation to investigate. Several red flags may justify passing. The book also notes that financial companies, including banks and NBFCs, need different analysis because debt is integral to their operating model. [pause] This is the key limitation: ratios must be interpreted inside a business model, not applied mechanically across every sector."),
 K("screen_to_research","SCREEN, THEN RESEARCH","The correct workflow is screen → annual report → management → valuation → portfolio fit.","No formula can guarantee results in a changing market.",TEAL,
  "The author explicitly warns against shortcut thinking. [pause] Passing a screen does not prove quality, honesty, or attractive valuation. It simply tells you where to look next. Read the financial statements. Study the business and its competitive position. Evaluate management. Estimate valuation conservatively. Then ask whether the position belongs in your portfolio. [pause] A checklist is valuable because it makes research repeatable, not because it makes investing automatic."),
]},
{"id":"ch11", "title":"Long-Term Lessons", "segments":[
 D(11,"Long-term habits","Start early, learn continuously, own mistakes, and keep money in perspective.",TEAL),
 K("time","TIME IS AN ASSET","Starting with a small, sustainable amount can give learning and compounding more time to work.","Do not confuse the power of time with a promise of any future return.",GOOD,
  "The final chapter broadens beyond ratios. [pause] Starting early matters because time allows habits, learning, and compounding to work together. The important point is not a guaranteed future number. It is consistency: invest only after building an emergency cushion, keep expectations realistic, and make room to learn from small errors before responsibilities grow larger. [pause] Time is most useful when paired with patience and risk control."),
 C("learning_loop","THE INVESTOR'S LEARNING LOOP","Skill compounds when outcomes become feedback instead of blame",[
  {"name":"Unhelpful loop", "c":RISK, "tag":"stuck", "stats":[{"k":"Loss","v":"blame a tipster"},{"k":"Lesson","v":"none"},{"k":"Next move","v":"new hot tip"},{"k":"Result","v":"repeat error","hot":True}]},
  {"name":"Useful loop", "c":GOOD, "tag":"improving", "stats":[{"k":"Loss","v":"review thesis"},{"k":"Lesson","v":"name the error"},{"k":"Next move","v":"update process"},{"k":"Result","v":"better judgement","hot":True}]},
 ],"Keep an investment journal: thesis, valuation, risks, and what later proved wrong.",TEAL,
  "The author argues for beginning, making mistakes within limits, and learning rather than blaming. [pause] Keep an investment journal. Before buying, write the thesis, the valuation case, the risks, and what would prove you wrong. Later, compare the outcome with the original reasoning. [pause] This separates a bad process from bad luck, and a good process from a fortunate result. Over time, that feedback loop is more valuable than collecting predictions."),
 ("final_recap", "fa_recap", {"kicker":"RECAP · THE WHOLE BOOK", "title":"A calmer way to invest", "items":[
   "Treat shares as ownership claims, not tips or lottery tickets.",
   "Protect capital with knowledge, balance-sheet discipline, and position limits.",
   "Judge business quality, management incentives, and valuation together.",
   "Buy and sell from a written thesis, never from an entry-price anchor.",
   "Diversify by economic exposure; use screens only to begin research.",
   "Verify advisers and reject guaranteed-return claims.",
   "Keep learning, own mistakes, and let time do its work.",
 ], "closer":"Information from a 2017 educational book; not investment advice. Consult a SEBI-registered adviser for personal decisions.", "color":TEAL},
  "Let's close with the whole map. [pause] Ownership, capital protection, business quality, management, valuation, disciplined decisions, sensible diversification, and continuous learning. [pause] The book's promise is not a shortcut to certain returns. It is a way to replace tips and panic with a repeatable process. This video is educational information, not investment advice. For personal decisions, consult a SEBI-registered adviser. Thanks for watching."),
]},
]

# ---------------------------------------------------------------------------
# Detailed teaching beats. These preserve the original chapter sequence while
# expanding every substantial section and historical case study from the PDF.
# Historical stock names, prices, ratios, and rules are explicitly treated as
# the book's 2017 illustrations; they are not current recommendations or data.
EXTRA = {
"ch01": [
 K("detail_broker", "CASE STUDY · THE BROKER LOOP", "Frequent activity can create a conflict: each transaction may create costs, even when the investor's result is poor.", "The book's fictionalised Rohit story begins with tips, early gains, then a sharp loss and accumulated charges.", RISK,
 "The first phase of the book's Rohit case study is about incentives. [pause] He knew little about markets, gave money to a broker friend, and received frequent news-based trade ideas. Early gains made the arrangement look safe. Then a market decline and repeated transactions left him with a large loss. [pause] The educational point is not that every broker is untrustworthy. It is that activity creates costs and incentives. Before acting, know the purpose, cost, and risk of every trade. Do not let someone else's turnover target become your investment plan."),
 K("detail_intraday", "CASE STUDY · INTRADAY AND MARGIN", "A high hit rate can still lose money when losses are larger than gains, costs accumulate, and leverage amplifies errors.", "A stop price is not a guarantee of an exact exit price in a fast move.", RISK,
 "In Rohit's second phase, he follows intraday tips during a rising market. The book shows the trap: many small winning trades can be erased by a few larger losses. [pause] Margin increases exposure. A small adverse move on a large intraday position can consume a much larger share of the capital actually deposited. A stop-loss instruction can help limit risk, but it is not a promise of execution at one exact price during a rapid move. [pause] The durable lesson is to understand payoff, costs, liquidity, and maximum loss before taking leveraged exposure."),
 K("detail_leverage", "CASE STUDY · LOAN AGAINST SHARES", "Borrowing against a portfolio introduces a second risk: a lender can force action precisely when prices are weak.", "A falling collateral value can trigger margin calls and forced selling.", DEBT,
 "Rohit's third phase is the leverage lesson. He borrows against shares after a period of gains, expecting portfolio returns to exceed the loan cost. [pause] When the market drops, the collateral falls below the lender's requirement. He must sell to restore collateral, even though he would prefer to hold. That is forced selling. [pause] Leverage can increase gains in a rising market, but it also removes flexibility in a falling market. For a retail investor, preservation of staying power is often more valuable than a borrowed attempt to accelerate returns."),
 K("detail_fo", "CASE STUDY · F&O TIP CLAIMS", "An extraordinary-return promise is a warning sign, especially when it hides the size and probability of loss.", "Futures and options are risk-management instruments; they can also create leveraged losses.", RISK,
 "The final phase is a warning about paid tips and futures-and-options promises. Rohit sees a successful trial and is then persuaded by dramatic monthly-return claims. [pause] One winning trade increases confidence; a later trade wipes out most of the capital. A short sample never proves a durable process. Ask: what is the downside, who benefits from selling the tip, and why would a repeatable extraordinary strategy need to be marketed this way? [pause] In modern India, derivatives involve complex obligations and risks. Use only products you understand, and never treat promotional claims as evidence."),
 K("detail_long_term", "THE BOOK'S ALTERNATIVE", "The proposed antidote is long-horizon ownership: quality business, sensible valuation, and patience while the thesis remains valid.", "No approach guarantees a profit; it aims to reduce avoidable, permanent mistakes.", GOOD,
 "After showing several ways a retail investor can get trapped, the book's alternative is not a hot strategy. [pause] It is a slower process: own businesses with understandable economics, check management and debt, avoid overpaying, diversify, and give valid theses time. The intended holding period is measured in years rather than days. [pause] This is a framework for decision quality, not a promise. A long holding period cannot repair a bad business, dishonest management, or an extreme purchase price. It gives a good thesis time to work."),
],
"ch02": [
 K("detail_inflation", "INFLATION AND TAX", "Nominal return is not the same as real, after-tax return: future spending power is what matters.", "The book's 2017 deposit-rate and tax figures are historical examples, not present rates.", DEBT,
 "The chapter uses a simple comparison: a deposit can earn a stated interest rate, yet inflation and tax can reduce its purchasing-power result. [pause] The correct concept is real return. Start with the nominal growth of money, then consider taxes and the rise in the cost of goods and services you need. The exact rates in the book are dated, so this video does not reuse them as current facts. [pause] The general lesson remains: match long-term goals with assets that have a credible chance of preserving purchasing power after costs and taxes."),
 C("detail_risk_knowledge", "THE BOOK'S 'ONE RISK'", "The author frames lack of knowledge as the root risk because ignorance leads to bad products, bad timing, and bad leverage.",[
  {"name":"Unprepared", "c":RISK, "tag":"risk multiplies", "stats":[{"k":"Does not know","v":"what is owned"},{"k":"Responds to","v":"tips and price"},{"k":"Uses","v":"borrowed conviction"},{"k":"Outcome","v":"forced decisions","hot":True}]},
  {"name":"Prepared", "c":GOOD, "tag":"risk managed", "stats":[{"k":"Knows","v":"business and downside"},{"k":"Responds to","v":"material facts"},{"k":"Uses","v":"position limits"},{"k":"Outcome","v":"more choice","hot":True}]},
 ],"Knowledge cannot eliminate market risk; it can prevent many self-created risks.",TEAL,
 "The book provocatively calls lack of knowledge the only real risk. [pause] Taken literally, markets still carry economic and business risk. But the teaching point is strong: ignorance magnifies every risk. It can lead an investor to confuse a loan with capital, a tip with research, a price fall with a bargain, or a high return with a safe return. [pause] Learn enough to identify what you do not know. That humility is a form of risk control."),
 L("detail_equity_basics", "WHY EQUITY IS DIFFERENT", "Equity: ownership, liquidity, and uncertainty",[
  {"label":"Ownership", "val":"claim on a business", "c":GOOD, "bold":True},
  {"label":"Liquidity", "val":"usually tradable on exchange", "c":REV},
  {"label":"Accessibility", "val":"small amounts can begin", "c":TEAL},
  {"label":"Uncertainty", "val":"price and return fluctuate", "c":RISK},
  {"label":"Discipline", "val":"research and horizon needed", "c":DEBT},
 ],"These are principles; availability, costs, and rules change over time.",TEAL,
 "The book contrasts equity with other savings choices. Equity can be liquid, accessible, and capable of participating in business growth. [pause] But it does not offer a fixed return or capital certainty over short periods. That is why the investor must not use money needed soon for essential expenses. Start with an emergency cushion, understand the account and transaction mechanics, and invest only a planned surplus. [pause] Equity is neither magic nor poison. It is an ownership instrument whose suitability depends on horizon, knowledge, and risk capacity."),
 K("detail_basics", "DON'T SKIP THE BASICS", "Before selecting a share, understand statements, market terminology, risk, diversification, and the difference between investing and trading.", "A beginner's first advantage is refusing to act beyond their understanding.", TEAL,
 "The book's next message is foundational. [pause] Do not begin with stock names. Begin with vocabulary and mechanics. Know what revenue, profit, cash flow, debt, market capitalisation, valuation, and diversification mean. Know the difference between a delivery investment and a short-term leveraged position. Read a basic annual report before you rely on an analyst summary. [pause] A simple learning plan is more useful than collecting dozens of opinions. Each concept you understand reduces the chance that marketing language controls your money."),
 K("detail_knowledge", "KNOWLEDGE COMPOUNDS", "Learning may not create instant returns, but it improves questions, filters, and the ability to recognise a poor offer.", "Use trusted educational material and primary disclosures; verify changing regulations separately.", GOOD,
 "The chapter ends with the idea that knowledge pays the best interest. [pause] Treat investing education as a continuing practice. Read company disclosures, learn accounting basics, and study both successes and failures. Build a checklist rather than relying on memory. When a regulation, tax rule, lot size, or platform feature matters, verify it from current official or primary sources. [pause] The investor's goal is not to predict every outcome. It is to make fewer unforced errors and to know when expert help is appropriate."),
],
"ch03": [
 K("detail_start", "WHERE TO START", "Do not begin with sales or profit growth alone; reported growth can be weak quality, debt-fuelled, or disconnected from cash.", "Start by asking whether the business earns strong, repeatable returns on the capital it employs.", GOOD,
 "The book tells beginners not to begin with the most exciting growth number. A company can grow sales while destroying margins. It can report profit while cash collection is weak. It can grow through borrowed money. [pause] Start with quality of economics: returns on equity and capital, operating cash flow, debt, and the reason customers choose the business. Growth becomes valuable when it is profitable, cash-supported, and earned without taking unacceptable balance-sheet risk."),
 L("detail_roe_math", "ROE: WHAT TO READ", "ROE: components and multi-year trend",[
  {"label":"Numerator", "val":"profit attributable to owners", "c":GOOD, "bold":True},
  {"label":"Denominator", "val":"shareholders' equity", "c":REV},
  {"label":"Trend", "val":"several years, not one", "c":TEAL},
  {"label":"Cross-check", "val":"ROCE, cash flow, debt", "c":DEBT},
 ],"A high ratio can be genuine strength or debt-driven distortion.",GOOD,
 "Return on equity is presented as an important first filter. [pause] Conceptually, it asks how effectively owners' funds have been converted into profit. But a single-year number can mislead. Exceptional gains can boost profit; a very small equity base or high leverage can make the ratio look artificially high. [pause] Use multiple years. Compare with return on capital employed, operating cash flow, and debt. A quality business is more convincing when high returns persist through different conditions without excessive borrowing."),
 C("detail_moat_types", "WHAT MAKES A MOAT?", "A competitive advantage should explain why returns can stay high",[
  {"name":"Cost advantage", "c":GOOD, "tag":"economics", "stats":[{"k":"Source","v":"scale / process"},{"k":"Benefit","v":"lower unit cost"},{"k":"Test","v":"margin resilience"},{"k":"Risk","v":"technology shift","hot":True}]},
  {"name":"Customer advantage", "c":VALUE, "tag":"demand", "stats":[{"k":"Source","v":"brand / switching"},{"k":"Benefit","v":"repeat demand"},{"k":"Test","v":"pricing power"},{"k":"Risk","v":"preference change","hot":True}]},
 ],"A moat is not permanent by default; investigate how it can weaken.",GOOD,
 "The book describes economic moats as the durable advantages that separate quality businesses. [pause] In practice, ask whether the edge comes from low cost, a brand, distribution, customer switching costs, intellectual property, or network effects. Then ask what could erode it: new technology, regulation, lower barriers to entry, or a stronger competitor. [pause] The purpose of a moat analysis is not to admire a company. It is to explain sustained returns and to identify the conditions under which those returns may fade."),
 L("detail_debt_ratios", "DEBT: FIVE LENSES", "Debt: leverage, liquidity, and cash",[
  {"label":"Debt / equity", "val":"balance-sheet leverage", "c":DEBT, "bold":True},
  {"label":"Interest coverage", "val":"profit versus interest", "c":GOOD},
  {"label":"Current ratio", "val":"near-term liquidity", "c":REV},
  {"label":"Quick ratio", "val":"liquidity without inventory", "c":TEAL},
  {"label":"Debt / owner funds", "val":"capital structure trend", "c":RISK},
 ],"The book lists these as screening tools, not substitute for cash-flow analysis.",DEBT,
 "The debt section gives several ratios because leverage has several failure modes. [pause] Debt-to-equity describes the capital structure. Interest coverage asks whether operating earnings can comfortably service interest. Current and quick ratios examine near-term obligations and liquid resources. The trend in debt relative to owner funds shows whether reliance on borrowing is rising. [pause] Use the ratios together, then read cash flow and maturity details. A business may look profitable but still face stress if cash arrives too slowly or refinancing becomes difficult."),
 K("detail_next", "MOVE TO THE NEXT PARAMETERS", "After return, moat, and debt, continue into management quality and valuation; no single ratio can complete a stock decision.", "The order matters: first quality, then price, then portfolio fit.", TEAL,
 "The chapter's final bridge is important. [pause] A screen for high returns, competitive advantage, and manageable debt can remove many weak candidates. It does not finish the job. The next questions are who runs the business, whether they treat shareholders fairly, and what expectations are embedded in the price. [pause] Think of the process as a funnel. Each stage reduces uncertainty. No single number can turn a complex business into a safe decision."),
],
"ch04": [
 K("detail_agm", "HOW TO ASSESS MANAGEMENT", "Use annual reports, conference calls, AGMs, and repeated disclosures to ask better questions than a private impression can answer.", "Management access is limited for most retail investors; evidence must be scalable.", TEAL,
 "The book questions the usefulness of a simple management visit for retail investors. Executives naturally present their best case. [pause] Public forums can be more informative because analysts and shareholders ask different questions and answers become part of the record. Read annual reports, investor presentations, and conference-call transcripts. Compare explanations from one period to the next. [pause] Do not try to become friends with management. Try to test whether their communication, capital allocation, and reported outcomes remain consistent."),
 L("detail_pattern", "SHAREHOLDING PATTERN", "Ownership: patterns and pledge risk",[
  {"label":"Promoter group", "val":"control and alignment", "c":TEAL, "bold":True},
  {"label":"Public holders", "val":"outside ownership", "c":REV},
  {"label":"Pledged shares", "val":"collateral risk", "c":RISK},
  {"label":"Change over time", "val":"context for action", "c":DEBT},
 ],"A pledge or sale requires investigation; it is not automatic proof of wrongdoing.",TEAL,
 "The shareholding-pattern section distinguishes promoters from the public and explains why trends matter. [pause] Rising promoter ownership may suggest confidence, but it can also simply reflect control. A reduction can have many explanations. Promoter pledging deserves careful scrutiny because pledged shares can create forced-sale pressure if their value drops. [pause] Use filings to ask questions, not to jump to a conclusion. Combine ownership trends with debt, related-party transactions, corporate actions, and management's own explanation."),
 K("detail_buyback", "BUYBACKS, DIVIDENDS, AND TAX", "Capital-return decisions are clues about management's priorities, cash needs, and view of valuation.", "The book describes buybacks as possible uses of surplus cash; current tax treatment and rules must be verified separately.", VALUE,
 "The book discusses dividends, buybacks, and taxation as management-evaluation clues. A company may return surplus cash to shareholders, retain it for high-return reinvestment, repay debt, or pursue acquisitions. [pause] None is universally best. The question is whether the chosen use creates more owner value than the alternatives. Buybacks can be sensible when cash is truly surplus and valuation is attractive; they can be cosmetic when funded by debt or used to disguise dilution. [pause] Do not rely on the book's old tax details; current tax treatment changes and needs current verification."),
 K("detail_roe_management", "ROE AS A MANAGEMENT SCORECARD", "A persistently strong return on equity can reflect disciplined capital allocation — after adjusting for debt and accounting effects.", "Look for a multi-year record, not a single impressive ratio.", GOOD,
 "The chapter returns to R O E as a management clue. [pause] If a leadership team retains shareholder capital and repeatedly earns high, cash-backed returns without dangerous leverage, that is meaningful evidence. But returns can be lifted by debt, asset sales, or a shrinking equity base. [pause] Look at the record over several years: how much capital was retained, where it went, and what it produced. Management quality becomes visible in the compound effect of many allocation decisions."),
 K("detail_management_conclusion", "MANAGEMENT CHECKLIST", "Trust should be earned from alignment, transparency, conservative accounting, and a long record of rational capital decisions.", "Good governance cannot turn a poor industry into a great investment, but weak governance can destroy a good business.", GOOD,
 "The practical conclusion is balanced. [pause] Do not expect a perfect management score. Instead, look for an accumulation of evidence: understandable disclosures, consistent communication, shareholder alignment, low unnecessary dilution, prudent debt, and capital allocation that makes economic sense. The book's wider message is that management risk is real and can change. [pause] Keep monitoring after purchase. Governance is not a box to tick once; it is part of the investment thesis."),
],
"ch05": [
 K("detail_pe", "P/E, P/B, AND MARKET CAP", "A share's rupee price alone says nothing about cheapness; valuation connects price with earnings, assets, growth, and business quality.", "A low P/E can be a bargain or a value trap; a high P/E can be justified or dangerous.", VALUE,
 "This chapter dismantles a common misconception: a two-rupee share is not necessarily cheaper than a two-thousand-rupee share. [pause] Price per share depends on share count. Valuation asks what investors are paying for earnings, assets, cash flow, or the whole enterprise. Price-to-earnings and price-to-book are shortcuts, not verdicts. A low multiple can reflect low quality, debt, declining earnings, or governance concerns. [pause] A high multiple can reflect durable growth and superior returns. Context is the valuation skill."),
 K("detail_value_trap", "CHEAP IS NOT VALUE", "Statistically low P/E, low P/B, or a high dividend yield can be a warning that the market expects trouble.", "Investigate the future earning power and balance sheet before calling a stock undervalued.", RISK,
 "The book calls out the value trap. [pause] Investors may screen for low P E, low P B, or high dividend yield and assume they have found a bargain. But the market can be pricing in weak business quality, shrinking demand, poor cash flow, debt, or an impending cut in dividend. The correct next step is research: why is this multiple low? [pause] Value investing is not buying the smallest ratio. It is buying future cash-generating ability at a price that leaves room for error."),
 K("detail_dcf", "DCF AND ITS LIMITS", "Discounted cash flow converts future cash-flow assumptions into a present value — but small assumption changes can move the answer dramatically.", "Use models as structured thinking, not as an oracle.", VALUE,
 "The book discusses discounted cash flow and other valuation methods critically. A D C F estimates future cash flows and discounts them to today. [pause] Its strength is that it forces explicit assumptions. Its weakness is that future revenue, margins, competition, capital spending, regulation, and discount rates are uncertain. Small changes can produce very different values. The book's examples show why a rigid formula can miss a durable compounder or misread a changing industry. [pause] Use valuation models to test scenarios, but keep judgment, humility, and a margin of safety."),
 L("detail_peg", "THE BOOK'S HISTORICAL METHOD", "Compare today's P/E with the company's own valuation history and with multi-year EPS growth",[
  {"label":"Historical P/E", "val":"own past range", "c":VALUE, "bold":True},
  {"label":"EPS growth", "val":"prefer per-share growth", "c":GOOD},
  {"label":"PEG", "val":"P/E ÷ growth rate", "c":TEAL},
  {"label":"Context", "val":"quality, cycle, debt", "c":DEBT},
 ],"The book's PEG bands and thresholds are a 2017 heuristic, not a current recommendation.",VALUE,
 "The book's practical method combines a company's historical valuation range with P E relative to average earnings-per-share growth, often expressed as P E G. [pause] Its insight is useful: compare a multiple with both the business's growth and its own past. But its numerical cut-offs are historical heuristics, not universal laws. Growth can slow, accounting can change, and cyclical profits can distort the denominator. [pause] Prefer E P S growth to total profit growth when dilution matters. Then layer in balance-sheet quality, competitive advantage, and cycle position."),
 K("detail_limits", "VALUATION LIMITATIONS", "Loss-making, turnaround, and cyclical businesses require different evidence because normal earnings multiples can be meaningless at the wrong point in a cycle.", "Do not assume a weak business will recover merely because its historical price was higher.", RISK,
 "The book explicitly notes limits to its method. [pause] A loss-making company has no meaningful P E. A turnaround may take longer than optimists expect, and a cyclical business can look cheapest when profit is temporarily high and most expensive when profit is temporarily low. Historical examples in the book are just that: historical. [pause] The disciplined default for a retail investor is to prefer understandable, profitable businesses until they have the skill to analyse special situations in depth."),
],
"ch06": [
 B("detail_repeat_buy", "THE AJANTA REPEAT-BUY EXAMPLE", "Higher prices do not automatically end a valid thesis", [{"label":"Initial", "val":250, "c":TEAL, "note":"historical ₹"},{"label":"Later 1", "val":440, "c":REV, "note":"historical ₹"},{"label":"Later 2", "val":500, "c":DEBT, "note":"historical ₹"},{"label":"Later 3", "val":730, "c":GOOD, "note":"historical ₹"}], "The book's pre-split historical example illustrates absolute profit versus percentage return; it is not a current recommendation.",REV,
 "The book uses a historical Ajanta Pharma example to explain repeat buying. A first purchase was followed by higher prices after results and outlook improved. [pause] The lesson is not to chase any rising stock. It is that an investor should not reject every addition just because the average cost rises. If the thesis improves, valuation remains sensible, portfolio weight stays within limits, and cash is truly long-term, a higher price may still be a rational decision. [pause] Percentage return and absolute rupee outcome are different. Always reassess from today's price and facts."),
 K("detail_high", "THE 52-WEEK-HIGH BIAS", "A fresh high can reflect an improving business; price strength alone is neither a buy signal nor a danger signal.", "Ask what is causing the strength and whether valuation still matches the business.", GOOD,
 "Many investors avoid every stock near a fifty-two-week high. The book gives historical examples of companies that kept making new highs as their business performance improved. [pause] A high is simply a price location. It says nothing by itself about valuation or future return. Investigate earnings, cash flow, competitive position, and the expectations now reflected in price. A quality compounder can remain expensive-looking for long periods. [pause] The correct response to a high is analysis, not automatic fear or automatic momentum buying."),
 K("detail_low", "THE 52-WEEK-LOW TRAP", "A large decline does not create value automatically; it may be the market reacting to a damaged business, leverage, or governance failure.", "The book's Educomp, Unitech, and similar examples are historical warnings, not a screening rule.", RISK,
 "The opposite error is treating a fifty-two-week low as a bargain. The book describes historical wealth-destroying companies where each new low attracted buyers who expected a rebound. [pause] A price can keep falling when the business deteriorates. Before considering a fallen share, identify the cause: weaker demand, debt, dilution, lost advantage, accounting concerns, or a cyclical trough. Then decide whether the problem is temporary, fixable, and already priced in. [pause] Never call something undervalued merely because it used to trade higher."),
 L("detail_sell_criteria", "WHEN TO SELL", "Use pre-defined reasons rather than an attempt to call the exact top",[
  {"label":"Better opportunity", "val":"capital can earn more elsewhere", "c":GOOD, "bold":True},
  {"label":"Original error", "val":"thesis was wrong", "c":RISK},
  {"label":"Valuation", "val":"expectations become extreme", "c":VALUE},
  {"label":"Fundamentals", "val":"business deteriorates", "c":DEBT},
  {"label":"Management", "val":"trust or incentives change", "c":TEAL},
 ],"The book also recommends defining an exit strategy while calm.",REV,
 "The sell chapter is more detailed than a price target. The book names better opportunities, a wrong buying decision, extreme valuation, changed fundamentals, and changed management as reasons to reconsider. [pause] The key is to decide in advance what would invalidate the thesis. Do not cling to a past winner because it feels familiar. Do not hold a mistake waiting to recover your cost. [pause] Equally, do not sell a sound business only because its price rose. Review from today: expected return, risk, valuation, and alternatives."),
 K("detail_sell_mistakes", "DEADLY SELLING MISTAKES", "Do not sell merely because of a small gain, fear a higher average price, or mistake a temporary quote change for broken fundamentals.", "Selling discipline is symmetric with buying discipline: thesis first, emotion second.", TEAL,
 "The chapter ends with common selling errors. [pause] Investors may take a quick profit in a strong business while holding a deteriorating loser. They may refuse to add because the average price will rise, or refuse to exit because the price is below cost. These are emotional rules, not economic rules. Replace them with a written review: what changed in business quality, management, valuation, portfolio weight, and your best alternative? [pause] You will not sell every top or buy every bottom. A sound process does not require that impossible standard."),
],
"ch07": [
 K("detail_quote", "DAILY QUOTES", "Frequent monitoring can make a long-term owner behave like a short-term trader.", "Follow company-specific information and scheduled review points instead of reacting to every tick.", RISK,
 "The chapter's first story describes an investor who loses conviction after a few months of price weakness, exits near his cost, and later watches the business perform. [pause] The message is not to ignore prices forever. Prices can reveal new information. It is to distinguish price movement from information. Set review triggers: results, debt changes, governance events, major industry changes, and valuation. [pause] If your horizon is years, a daily quote should not have the power to rewrite a thesis that the underlying facts still support."),
 K("detail_cost_anchor", "PURCHASE PRICE ANCHOR", "Your entry price is personal history; it does not determine future value or the best use of capital today.", "Evaluate hold, add, reduce, or exit from the current facts and alternatives.", RISK,
 "The book repeatedly warns against overemphasising purchase rate. A share bought at a lower price can still be unattractive today. A share below your cost can still be worth selling if the thesis is broken. [pause] The market does not know where you entered. The relevant calculation starts now: what is the expected return from this point, what are the risks, and is there a better opportunity? [pause] Keeping the cost visible for tax records is sensible. Letting it dictate investment logic is not."),
 C("detail_prediction", "PREDICTING THE INDEX", "A weak index can contain strong companies, and a strong index can contain weak companies",[
  {"name":"Index forecast", "c":DEBT, "tag":"hard to repeat", "stats":[{"k":"Focus","v":"macro direction"},{"k":"Problem","v":"timing uncertainty"},{"k":"Risk","v":"missed opportunities"},{"k":"Use","v":"context only","hot":True}]},
  {"name":"Business analysis", "c":GOOD, "tag":"more actionable", "stats":[{"k":"Focus","v":"company facts"},{"k":"Question","v":"quality and price"},{"k":"Risk","v":"specific, reviewable"},{"k":"Use","v":"portfolio decisions","hot":True}]},
 ],"The book uses historical periods when stock-level results diverged from the index.",TEAL,
 "The market-direction section says index forecasting is a poor foundation for a retail investor. The book cites historical periods when a broad index was flat or negative while selected businesses still performed. [pause] This does not mean macro conditions never matter. Interest rates, liquidity, and cycles affect valuation and profits. It means an index call is too blunt to replace company analysis. [pause] Use macro context to stress-test a thesis. Do not postpone all investing until someone can tell you the exact next market turn."),
 K("detail_bear", "LOVE THE BEAR MARKET?", "A downturn can improve prices, but only quality, liquidity, and emotional readiness turn it into opportunity.", "Never treat a crash as a reason to buy indiscriminately.", DEBT,
 "The book asks investors to view a bear market differently. [pause] Lower prices can create opportunity, but only after you check business durability, leverage, and valuation. A falling stock is not automatically a better stock. Keep enough cash for life needs so you are not forced to sell. Maintain diversification so one failed thesis cannot dominate. [pause] The ideal time to decide how you will behave in a crash is before the crash, while your judgment is calm."),
 K("detail_behaviour", "BEHAVIOURAL RULE", "Write the decision rule before emotion arrives: do not trade a headline; investigate a fact.", "A predictable process is more valuable than an exciting one.", GOOD,
 "The do's and don'ts chapter is fundamentally about behaviour. [pause] The investor is tempted by green quotes, red quotes, forecasts, new highs, and familiar entry prices. A written process creates a pause between stimulus and action. Record what evidence would make you buy, add, reduce, or sell. [pause] Then review decisions rather than only outcomes. This does not eliminate emotion. It gives emotion less authority over your capital."),
],
"ch08": [
 K("detail_overlap", "DIVERSIFICATION: THE REAL TEST", "Diversification means exposures that do not all fail for the same reason — not simply owning many tickers.", "Map sector, leverage, commodity, customer, and economic-cycle overlap.", TEAL,
 "The book makes an important distinction between diversification and over-diversification. A portfolio of many shares can still be a single bet if the holdings depend on the same sector, credit cycle, commodity price, or customer demand. [pause] Conversely, a smaller portfolio can be better diversified if its economic drivers differ and each position is understood. The task is to map overlap. Ask what could make several holdings fall together. [pause] Diversification reduces single-point failure; it does not remove market risk or guarantee return."),
 K("detail_many", "THE COST OF TOO MANY HOLDINGS", "A huge portfolio can dilute your best ideas, hide weak positions, increase overlap, and make proper monitoring impossible.", "The right number is the number you can understand, not a universal target.", RISK,
 "The book describes portfolios with many names where a few large winners could not offset broad weakness. [pause] The lesson is not an exact maximum number of shares. The right count depends on time, knowledge, position sizes, and how correlated businesses are. But every holding creates work: results, debt, management, valuation, and thesis review. If you cannot explain why a position exists and what would change your mind, it may be a leftover rather than a deliberate allocation. [pause] Concentration and clutter are both risks."),
 C("detail_crash_types", "CRASH PREPAREDNESS", "The book distinguishes ordinary corrections from deeper market crises, but exact timing and thresholds cannot be forecast reliably",[
  {"name":"Correction", "c":DEBT, "tag":"review", "stats":[{"k":"First step","v":"check thesis"},{"k":"Avoid","v":"panic liquidation"},{"k":"Consider","v":"quality and price"},{"k":"Need","v":"liquidity","hot":True}]},
  {"name":"Deep crisis", "c":RISK, "tag":"survive", "stats":[{"k":"First step","v":"protect solvency"},{"k":"Avoid","v":"leveraged exposure"},{"k":"Consider","v":"real-life needs"},{"k":"Need","v":"staying power","hot":True}]},
 ],"The book's historic crash categories are teaching aids, not a forecast rule.",DEBT,
 "The crash section asks investors to plan for both ordinary corrections and severe crises. In either case, first protect solvency and real-life liquidity. [pause] Do not sell everything simply because fear is high, and do not buy everything simply because prices are lower. Review the business and balance sheet. A deeper crisis is especially dangerous for leveraged investors or businesses that need constant refinancing. [pause] The goal is to retain choice. A portfolio designed to survive stress is more useful than one designed only for the best-case scenario."),
 K("detail_cash_plan", "CASH AND ALLOCATION PLAN", "Set a periodic investment amount based on income and goals, not on today's market mood or portfolio colour.", "Increase savings capacity with income; do not borrow or raid essential reserves to chase a decline.", GOOD,
 "The book recommends a pre-defined, periodic investment approach rather than changing commitment with every market move. [pause] Decide how much capital is available only after essential expenses, insurance, and emergency needs are covered. Then deploy according to a plan and quality criteria. Increase the planned amount when your underlying income and capacity improve, not merely because a recent trade won or lost. [pause] This separates financial planning from market emotion and reduces the temptation to become aggressive late in a bull market or absent during a bear market."),
 K("detail_portfolio_review", "PORTFOLIO REVIEW", "Review weights, overlap, business quality, valuation, and cash needs together — a portfolio is a system, not a list.", "A correct stock choice can still be a poor portfolio decision if the position is too large or too correlated.", TEAL,
 "The chapter's broader teaching is systems thinking. [pause] A portfolio's outcome comes from selections, weights, correlations, cash needs, and behaviour under stress. Review it at planned intervals. Identify positions that became oversized through appreciation, sectors that became crowded, and thesis changes that demand action. [pause] Avoid excessive tinkering. A review is not a reason to trade. It is a reason to check whether the portfolio still reflects your intended risks and long-term goals."),
],
"ch09": [
 K("detail_need_adviser", "DO YOU NEED AN ADVISER?", "The right question is not who has the hottest calls; it is whether you have the time, skill, and temperament to manage direct equity yourself.", "Delegation can be useful, but it never removes the need for due diligence.", VALUE,
 "The book says personal finance is rarely taught formally, yet everyone must manage money. [pause] Direct equity demands research, monitoring, and the ability to tolerate uncertainty without impulsive action. If those demands do not fit your time or skill, a diversified fund or qualified professional may be a more suitable route. [pause] But delegation requires its own work: understand the mandate, fees, risk level, conflicts, and how performance will be judged. A credible adviser helps you make informed decisions; they do not sell certainty."),
 C("detail_fund_direct", "MUTUAL FUND OR DIRECT EQUITY", "Both are tools; choose based on responsibility, not status",[
  {"name":"Mutual fund", "c":GOOD, "tag":"delegated", "stats":[{"k":"Strength","v":"professional process"},{"k":"Trade-off","v":"fees / less control"},{"k":"Investor work","v":"select and monitor"},{"k":"Best for","v":"limited time","hot":True}]},
  {"name":"Direct equity", "c":TEAL, "tag":"self-directed", "stats":[{"k":"Strength","v":"control / learning"},{"k":"Trade-off","v":"research burden"},{"k":"Investor work","v":"analyse and monitor"},{"k":"Best for","v":"prepared investors","hot":True}]},
 ],"This is a conceptual comparison, not a recommendation of any fund or product.",VALUE,
 "The mutual-fund-versus-direct-equity section is not a contest. A fund can provide diversification and a professional process, while direct equity offers control and deeper learning. [pause] Both carry market risk. Both need monitoring. The wrong choice is the one whose obligations you will not meet: buying direct shares without research, or buying a fund without understanding its mandate, cost, and risk. [pause] Match the tool to your skill, time, goals, and willingness to stay disciplined."),
 K("detail_scams", "RED FLAGS IN ADVICE", "Extraordinary-return claims, secret formulas, paid pressure, and unexplained calls are warning signs — not proof of skill.", "Verify registrations and disclosures from current official sources before acting.", RISK,
 "The book lists practical adviser red flags. Be cautious when someone promises extraordinary returns, claims near-perfect accuracy, pressures you to buy a subscription, or cannot explain the logic and risk behind a recommendation. [pause] Past-performance screenshots and testimonials can be selective or fabricated. Verify whether a professional is appropriately registered with SEBI for the service being offered, and independently verify the details. [pause] A responsible adviser explains uncertainty, downside, fees, conflicts, and the limits of their service."),
 K("detail_adviser_process", "A RESPONSIBLE ADVICE PROCESS", "Good guidance should make you more informed: objectives, risk capacity, diversification, evidence, review, and clear fees.", "If the process cannot be explained clearly, do not hand over decision-making authority.", GOOD,
 "The chapter ends with a practical standard. [pause] Whether you use an adviser, a fund, or direct equity, demand a process. It should begin with objectives and risk capacity, not a stock tip. It should explain diversification, valuation, risks, and the reason for each action. It should disclose compensation and conflicts. [pause] You remain responsible for understanding enough to ask questions. The goal of good advice is better judgment and appropriate risk, not emotional dependence on a caller or a group chat."),
],
"ch10": [
 K("detail_formula_caution", "WHAT THE FORMULA IS — AND ISN'T", "The quick formula is a filter for a research list, not a shortcut, guarantee, or substitute for the earlier chapters.", "Passing every ratio still does not prove management quality or attractive valuation.", GOOD,
 "Before giving the screen, the book gives a warning: do not jump straight to a formula and expect certainty. [pause] Markets change, accounting requires interpretation, and businesses differ by sector. A filter is useful because it makes the first pass consistent. It is dangerous when it creates false confidence. The correct order remains: screen candidates, understand the business, inspect management and debt, judge valuation, then decide whether it fits the portfolio. [pause] A formula organizes research; it does not replace it."),
 L("detail_formula_steps", "THE FIVE SCREENING STEPS", "Candidate filter: return, debt, pledge, and growth",[
  {"label":"Three-year ROE / ROCE", "val":"both above 20%", "c":GOOD, "bold":True},
  {"label":"Debt / equity", "val":"below 1 or declining", "c":DEBT},
  {"label":"Promoter pledge", "val":"below 10% or declining", "c":RISK},
  {"label":"Sales CAGR", "val":"above 10%", "c":REV},
  {"label":"Profit CAGR", "val":"above 12%", "c":GOOD},
 ],"These are the author's 2017 thresholds. They are historical educational content, not live screening advice.",GOOD,
 "Here are the book's five original screening criteria in detail. It seeks three-year average return on equity and return on capital employed above twenty percent; debt-to-equity below one or reducing; low or falling promoter pledge; three-year sales CAGR above ten percent; and profit CAGR above twelve percent. [pause] These thresholds belong to the author's 2017 framework. Use them to understand the logic: quality returns, manageable leverage, aligned ownership, and growth. Do not apply them blindly as current investment advice."),
 K("detail_formula_exceptions", "EXCEPTIONS AND LIMITATIONS", "Banks, NBFCs, cyclicals, turnarounds, and loss-making businesses need sector-specific analysis; a generic debt or P/E rule can mislead.", "A screen should identify questions, not remove the need to understand the business model.", DEBT,
 "The book itself names exceptions. Banks and NBFCs use leverage differently from industrial businesses, so normal debt ratios are not directly comparable. A cyclical business needs evaluation across a full cycle. A loss-making turnaround cannot be judged with a P E rule. [pause] That limitation is valuable. Every ratio has a business context. When the context differs, pause rather than forcing a company through a generic screen. Better to skip an unclear candidate than pretend a formula has explained it."),
 L("detail_two_min", "TWO-MINUTE REJECTION CHECK", "The book's fast warning signs combine low returns, high or rising debt, and heavy promoter pledge",[
  {"label":"Average ROE", "val":"below 10%", "c":RISK, "bold":True},
  {"label":"Debt / equity", "val":"above 1 and not improving", "c":DEBT},
  {"label":"Promoter pledge", "val":"above 30% and rising", "c":RISK},
  {"label":"All three", "val":"avoid under the book's rule", "c":RISK},
 ],"The numerical levels are historic book heuristics; investigate context and current disclosures.",RISK,
 "The book also offers a two-minute rejection check. It flags persistently low return on equity, high and non-improving debt-to-equity, and heavy or rising promoter pledge. If all hold, the author says avoid; if one or two hold, investigate carefully. [pause] The useful habit is negative screening. Investors often spend too long searching for reasons to buy. A fast list of disqualifying conditions protects time and capital. [pause] But keep the historic thresholds in context and verify live facts from current filings."),
 K("detail_application", "FROM SCREEN TO DECISION", "After screening, read the annual report, test the moat, evaluate management, compare valuation history, and size the position conservatively.", "A candidate is not a portfolio holding until it survives the full process.", TEAL,
 "Application is the final step. [pause] A screen gives you names; it does not give you understanding. For each survivor, read the annual report and notes, inspect cash flow and debt, identify the competitive advantage, review management actions, and compare current valuation with history and growth. Then consider portfolio overlap and position size. [pause] This layered process is how the book turns a quick formula into a more complete investment discipline."),
],
"ch11": [
 K("detail_start_early", "START EARLY, START SMALL", "The author's lesson is to begin learning and investing with a manageable amount, because time is useful only when paired with survival and discipline.", "The book's future-value illustration is historical and not a return promise.", GOOD,
 "The first personal lesson is to start early. The author uses a small monthly-investment illustration to show the power of time. [pause] Treat such examples as illustrations, not promises: future returns, inflation, and costs are uncertain. The lasting principle is behavioural. Start with a sustainable amount after basic financial protections are in place. Learn while mistakes are small. Let savings capacity grow with income. [pause] Time rewards consistent, survivable habits more than dramatic one-time bets."),
 K("detail_crowd", "DON'T FOLLOW THE CROWD", "In markets, popularity can be a signal to investigate expectations, not a reason to abandon independent analysis.", "Contrarian thinking means evidence-led independence, not automatically doing the opposite of everyone else.", VALUE,
 "The author's personal career story becomes an investing lesson: do not let crowd opinion replace your own reasoning. In a bull market, widespread optimism can inflate expectations. In a bear market, widespread pessimism can make investors ignore quality. [pause] Being contrarian does not mean buying every unpopular stock or selling every popular one. It means examining the facts, valuation, and risks independently. [pause] The market rewards correct analysis, not the comfort of agreement."),
 K("detail_responsibility", "OWN YOUR DECISIONS", "Review losses for errors in process, research, position size, or behaviour instead of outsourcing blame to a broker, adviser, or market.", "Taking responsibility is how an investor turns a loss into a process improvement.", TEAL,
 "The next lesson is personal responsibility. The book argues that investors often claim credit for gains while blaming others for losses. [pause] A broker, adviser, or tipster may indeed behave badly, which is why due diligence matters. But the investor still controls whether to verify, size, borrow, diversify, and act. After an outcome, review the decision. Was the thesis wrong? Was the valuation too high? Was the position too large? Was a rule ignored? [pause] That review is more useful than a search for someone to blame."),
 K("detail_appreciate", "APPRECIATE, DON'T PERSONALISE", "The author's interpersonal lesson is to evaluate people and processes fairly, especially during difficult periods.", "For investing, this means disciplined review rather than emotional praise or condemnation after a short result.", GOOD,
 "The book includes a story about encouragement during a difficult portfolio period. Its broader relevance is emotional discipline. [pause] Do not judge a process from one short outcome, and do not turn every period of underperformance into personal conflict. Evaluate facts, mandate, risk, and time horizon. At the same time, do not ignore evidence of broken trust or a failed process. [pause] Fair, specific feedback is more useful than reactive criticism, whether you are assessing yourself, an adviser, or a management team."),
 K("detail_life", "MONEY IN PERSPECTIVE", "The final lesson is that financial success should support a healthy, meaningful life — not become its only measure.", "Good investing serves life goals; it should not consume judgment, relationships, or well-being.", TEAL,
 "The final chapter leaves finance. The author argues that money matters, but a fulfilling life includes health, relationships, useful work, and contribution. [pause] This is also good investing advice. When wealth becomes the only scorecard, investors can take risks they do not need, follow markets compulsively, or sacrifice the time and judgment that protect them. Set financial goals in service of life goals. [pause] A calmer process, adequate diversification, and clear limits leave room for the rest of life."),
],
}

for _chapter in CHAPTERS:
    _chapter["segments"].extend(EXTRA[_chapter["id"]])

# The original recap is defined with chapter 11; keep it as the actual final beat
# after the additional personal-finance lessons above.
_last = CHAPTERS[-1]
_recap = [s for s in _last["segments"] if s[0] == "final_recap"]
_last["segments"] = [s for s in _last["segments"] if s[0] != "final_recap"] + _recap
