import React from "react";
import { Stage, Card, Wire, Flow, Counter, Type, useP, usePop, rnd } from "../../lib/primitives";
import { FQHead, SceneProgress, Formula, DefBadge, StatChip, T, A, mix, MONO, SANS } from "./kit";

// Deterministic ~130-session close tape: trend + seeded cyclical noise (never Math.random).
const SERIES = Array.from({ length: 130 }, (_, i) => Number((100 + i * 0.18 + 4.8 * Math.sin(i * 0.105) + 2.2 * Math.sin(i * 0.31) + (rnd(i, 17, 91) - 0.5) * 2.6).toFixed(2)));
const movingAverage = (xs: number[], n: number) => xs.map((_, i) => i + 1 < n ? undefined : Number((xs.slice(i - n + 1, i + 1).reduce((a, b) => a + b, 0) / n).toFixed(2)));
const FAST = movingAverage(SERIES, 50);
const SLOW = movingAverage(SERIES, 40); // short-series stand-in for a 200-DMA
const RETURNS = SERIES.slice(1).map((v, i) => v / SERIES[i] - 1);
const mean = (xs: number[]) => xs.reduce((a, b) => a + b, 0) / xs.length;
const stdev = (xs: number[]) => Math.sqrt(mean(xs.map((x) => (x - mean(xs)) ** 2)));
const gains = RETURNS.slice(-14).map((x) => Math.max(0, x));
const losses = RETURNS.slice(-14).map((x) => Math.max(0, -x));
const RSI = Number((100 - 100 / (1 + mean(gains) / Math.max(mean(losses), 1e-9))).toFixed(1));
const VOL = Number((stdev(RETURNS) * Math.sqrt(252) * 100).toFixed(1));
const NIFTY = RETURNS.map((_, i) => (rnd(i, 8, 44) - 0.5) * 0.018 + Math.sin(i * 0.07) * 0.002);
const BETA = Number((mean(RETURNS.map((x, i) => (x - mean(RETURNS)) * (NIFTY[i] - mean(NIFTY)))) / mean(NIFTY.map((x) => (x - mean(NIFTY)) ** 2))).toFixed(2));
let peak = SERIES[0]; let maxDrawdown = 0;
SERIES.forEach((x) => { peak = Math.max(peak, x); maxDrawdown = Math.min(maxDrawdown, x / peak - 1); });
const LOW = Math.min(...SERIES), HIGH = Math.max(...SERIES);
const RANGE_POS = Number(((SERIES[SERIES.length - 1] - LOW) / (HIGH - LOW) * 100).toFixed(1));
const monthReturn = Number(((SERIES[SERIES.length - 1] / SERIES[SERIES.length - 22] - 1) * 100).toFixed(1));

const path = (vals: (number | undefined)[], reveal: number, x: number, y: number, w: number, h: number, lo: number, hi: number) => vals.slice(0, Math.max(2, Math.floor(vals.length * Math.max(0, Math.min(1, reveal))))).map((v, i) => v === undefined ? "" : `${x + i * w / (vals.length - 1)},${y + h - ((v - lo) / (hi - lo)) * h}`).filter(Boolean).join(" ");
const chart = (reveal: number, overlays = false) => {
  const lo = LOW - 2, hi = HIGH + 2;
  return <svg width={1320} height={500} style={{ position: "absolute", left: 100, top: 330, overflow: "visible" }}>
    {[0, 1, 2, 3].map((i) => <line key={i} x1={50} y1={65 + i * 110} x2={1190} y2={65 + i * 110} stroke={T.line} strokeWidth={1} />)}
    <polyline points={path(SERIES, reveal, 50, 65, 1080, 410, lo, hi)} fill="none" stroke={A.tech} strokeWidth={5} strokeLinejoin="round" />
    {overlays && <><polyline points={path(FAST, reveal, 50, 65, 1080, 410, lo, hi)} fill="none" stroke={A.main} strokeWidth={3} /><polyline points={path(SLOW, reveal, 50, 65, 1080, 410, lo, hi)} fill="none" stroke={A.fund} strokeWidth={3} /></>}
    <text x="50" y="35" fill={T.muted} fontFamily={MONO} fontSize="20">DAILY CLOSE · COMPUTED TAPE</text><text x="50" y="485" fill={T.muted} fontFamily={MONO} fontSize="18">DAY 1</text><text x="1080" y="485" fill={T.muted} fontFamily={MONO} fontSize="18">DAY 130</text>
  </svg>;
};
const Motion: React.FC<{ y?: number }> = ({ y = 880 }) => <Flow x1={120} y1={y} x2={1800} y2={y - 20} curve={30} color={A.tech} n={8} speed={0.009} size={9} o={0.65} />;
const Verdict: React.FC<{ text: string; o: number }> = ({ text, o }) => <div style={{ position: "absolute", left: 130, top: 850, width: 1550, fontFamily: SANS, fontSize: 28, color: T.text, opacity: o }}>{text}</div>;

// NARRATION: A price chart joins each day’s closing price. Return compares the end with the start. Reliance at ₹1,287 is the real worked price we will keep reading.
export const ChartScene: React.FC<{ dur?: number }> = ({ dur }) => { const p = useP(dur); const pop = usePop(dur); return <Stage><SceneProgress p={p} color={A.tech} /><FQHead kicker="TECHNICALS · 01" title="A chart is the price telling a story" color={A.tech} p={p} /><Card theme={T} x={110} y={190} w={660} h={122} color={A.tech} o={p(0.08, 0.18)}><DefBadge text="DEFINITION" color={A.tech} o={p(0.1, 0.16)} /><div style={{ marginTop: 13, fontFamily: SANS, fontSize: 27, color: T.text }}>A line joins each day’s closing price.</div></Card><Card theme={T} x={800} y={190} w={620} h={122} color={A.tech} o={p(0.2, 0.3)}><Formula parts={[["Return", A.tech], ["= (end − start) ÷ start", T.text], ["× 100", A.main]]} size={28} o={p(0.22, 0.32)} /></Card>{chart(p(0.28, 0.72))}<div style={{ position: "absolute", left: 1320, top: 350, opacity: p(0.72, 0.82) }}><StatChip label="Reliance · worked price" value="₹1,287" color={A.tech} hero /></div><div style={{ position: "absolute", left: 1320, top: 485, opacity: p(0.78, 0.88) }}><StatChip label="computed 1-month reading" value={`${monthReturn >= 0 ? "+" : ""}${monthReturn}%`} color={A.main} /></div><Verdict text="Start with direction and change; indicators come next." o={p(0.82, 0.9)} /><Motion /><div style={{ position: "absolute", left: 150, top: 700, fontFamily: MONO, fontSize: 24, color: A.tech, opacity: p(0.72, 0.82) }}>CLOSE → RETURN → CONTEXT</div><div style={{ position: "absolute", left: 1430, top: 700, transform: `scale(${0.95 + pop(0.7) * 0.05})`, opacity: p(0.7, 0.8) }}><Counter p={p(0.7, 0.8)} to={130} suffix=" closes" color={A.tech} size={25} /></div></Stage>; };

// NARRATION: A moving average smooths noise by averaging the latest N closes. This tape uses a 50-day line and a 40-day proxy for a 200-DMA because it is shorter. Reliance at ₹1,287 versus its ₹1,396 200-DMA is below trend.
export const DMAScene: React.FC<{ dur?: number }> = ({ dur }) => { const p = useP(dur); return <Stage><SceneProgress p={p} color={A.tech} /><FQHead kicker="TECHNICALS · 02" title="Moving averages reveal the trend" color={A.tech} p={p} /><Card theme={T} x={110} y={180} w={760} h={130} color={A.tech} o={p(0.08, 0.18)}><DefBadge text="DEFINITION" color={A.tech} o={p(0.1, 0.16)} /><div style={{ marginTop: 13, fontFamily: SANS, fontSize: 26, color: T.text }}>The average closing price across the latest N days.</div></Card><Card theme={T} x={910} y={180} w={790} h={130} color={A.tech} o={p(0.2, 0.3)}><Formula parts={[["MA(N)", A.tech], ["= sum(last N closes) ÷ N", T.text]]} size={30} o={p(0.22, 0.3)} /></Card>{chart(p(0.28, 0.73), true)}<div style={{ position: "absolute", left: 1290, top: 340, opacity: p(0.56, 0.66) }}><StatChip label="price · Reliance" value="₹1,287" color={A.tech} /></div><div style={{ position: "absolute", left: 1290, top: 455, opacity: p(0.65, 0.75) }}><StatChip label="200-DMA · worked reading" value="₹1,396" color={A.fund} hero /></div><div style={{ position: "absolute", left: 150, top: 710, display: "flex", gap: 28, opacity: p(0.73, 0.83) }}><StatChip label="50-day average" value={FAST[FAST.length - 1]?.toFixed(2) || "NA"} color={A.main} /><StatChip label="40-day proxy" value={SLOW[SLOW.length - 1]?.toFixed(2) || "NA"} color={A.fund} /></div><Verdict text="Price below its long average = a weak trend signal, not a prediction." o={p(0.83, 0.9)} /><Motion y={820} /></Stage>; };

// NARRATION: RSI measures momentum on a zero-to-one-hundred scale by comparing average gains with losses. Reliance’s RSI is 42.9: below the healthy middle band, but not below 30 oversold.
export const RSIScene: React.FC<{ dur?: number }> = ({ dur }) => { const p = useP(dur); const dial = Math.max(0, Math.min(100, RSI)); const angle = -135 + 270 * dial / 100; return <Stage><SceneProgress p={p} color={A.tech} /><FQHead kicker="TECHNICALS · 03" title="RSI asks: is momentum too hot?" color={A.tech} p={p} /><Card theme={T} x={110} y={190} w={820} h={150} color={A.tech} o={p(0.08, 0.18)}><DefBadge text="DEFINITION" color={A.tech} o={p(0.1, 0.16)} /><div style={{ marginTop: 13, fontFamily: SANS, fontSize: 27, color: T.text }}>RSI is momentum on a 0–100 dial: high means recent buying dominated.</div></Card><Card theme={T} x={970} y={190} w={760} h={150} color={A.tech} o={p(0.2, 0.3)}><Formula parts={[["RSI", A.tech], ["= 100 − 100 ÷ (1 + avg gain ÷ avg loss)", T.text]]} size={25} o={p(0.22, 0.31)} /></Card><div style={{ position: "absolute", left: 230, top: 390, width: 480, height: 300, opacity: p(0.35, 0.78) }}><svg width="480" height="300"><path d="M80 230 A160 160 0 0 1 400 230" fill="none" stroke={T.line} strokeWidth="30" /><path d="M80 230 A160 160 0 0 1 400 230" fill="none" stroke={A.tech} strokeWidth="30" strokeDasharray="503" strokeDashoffset={503 * (1 - p(0.35, 0.78) * dial / 100)} /><line x1="240" y1="230" x2={240 + 135 * Math.cos(angle * Math.PI / 180)} y2={230 + 135 * Math.sin(angle * Math.PI / 180)} stroke={T.text} strokeWidth="8" strokeLinecap="round" /><circle cx="240" cy="230" r="14" fill={A.tech} /><text x="180" y="285" fill={T.text} fontFamily={MONO} fontWeight="800" fontSize="52">{(p(0.6, 0.78) * dial).toFixed(1)}</text></svg></div><div style={{ position: "absolute", left: 820, top: 390, opacity: p(0.58, 0.68) }}><StatChip label="Reliance · worked RSI" value="42.9" color={A.tech} hero /></div><div style={{ position: "absolute", left: 820, top: 520, fontFamily: SANS, fontSize: 28, color: T.text, opacity: p(0.68, 0.78), lineHeight: 1.45 }}>Above 70 = overbought<br />Below 30 = oversold<br />45–65 = healthier middle</div><div style={{ position: "absolute", left: 1290, top: 405, width: 420, height: 220, border: `2px solid ${A.tech}`, borderRadius: 18, padding: 24, boxSizing: "border-box", opacity: p(0.74, 0.84), background: mix(T.panel, A.tech, 0.08) }}><Type text="42.9 is soft momentum — not an automatic sell." p={p(0.74, 0.84)} size={29} color={T.text} /></div><Verdict text="RSI describes momentum; it does not tell you the future." o={p(0.84, 0.9)} /><Motion y={830} /></Stage>; };

// NARRATION: Volatility is the typical size of daily moves, annualised by square root of 252. Beta compares a stock with the Nifty; one is market-like. Max drawdown is the worst peak-to-trough fall.
export const VolBetaScene: React.FC<{ dur?: number }> = ({ dur }) => { const p = useP(dur); return <Stage><SceneProgress p={p} color={A.tech} /><FQHead kicker="TECHNICALS · 04" title="Volatility, beta and drawdown" color={A.tech} p={p} /><Card theme={T} x={110} y={185} w={800} h={150} color={A.tech} o={p(0.08, 0.18)}><DefBadge text="DEFINITION" color={A.tech} o={p(0.1, 0.16)} /><div style={{ marginTop: 13, fontFamily: SANS, fontSize: 26, color: T.text }}>Risk has three faces: daily swing, market sensitivity and loss from a peak.</div></Card><Card theme={T} x={950} y={185} w={780} h={150} color={A.tech} o={p(0.2, 0.3)}><Formula parts={[["Volatility", A.tech], ["= stdev(daily returns) × √252", T.text]]} size={27} o={p(0.22, 0.31)} /></Card><div style={{ position: "absolute", left: 130, top: 385, display: "flex", gap: 28, opacity: p(0.35, 0.65) }}><StatChip label="computed tape · annual vol" value={`${VOL}%`} color={A.tech} hero /><StatChip label="computed tape · beta" value={BETA.toFixed(2)} color={A.main} hero /><StatChip label="computed tape · max DD" value={`${(maxDrawdown * 100).toFixed(1)}%`} color={A.risk} hero /></div><div style={{ position: "absolute", left: 130, top: 570, width: 1530, height: 132, display: "flex", alignItems: "center", gap: 22, opacity: p(0.62, 0.72) }}><div style={{ fontFamily: MONO, fontSize: 23, color: T.muted }}>NIFTY</div><div style={{ width: 500, height: 8, background: T.line, borderRadius: 5, position: "relative" }}><div style={{ position: "absolute", left: `${Math.min(90, Math.max(8, 50 + BETA * 20))}%`, top: -13, width: 34, height: 34, borderRadius: 20, background: A.main, boxShadow: `0 0 20px ${A.main}` }} /></div><div style={{ fontFamily: SANS, fontSize: 27, color: T.text }}>β = 1 moves with it; β &gt; 1 amplifies it.</div></div><div style={{ position: "absolute", left: 130, top: 720, opacity: p(0.74, 0.84) }}><StatChip label="Reliance · real beta from brief" value="0.94" color={A.main} hero /></div><Verdict text="Reliance’s β 0.94 is close to market-like; volatility still tells you how rough the ride feels." o={p(0.84, 0.9)} /><Motion y={850} /></Stage>; };

// NARRATION: The 52-week range is the lowest and highest traded price in one year. The marker shows where today’s price sits. Reliance is at 8% of its range, a weak-tape reading near its low.
export const W52Scene: React.FC<{ dur?: number }> = ({ dur }) => { const p = useP(dur); return <Stage><SceneProgress p={p} color={A.tech} /><FQHead kicker="TECHNICALS · 05" title="The 52-week range gives a map" color={A.tech} p={p} /><Card theme={T} x={110} y={190} w={820} h={128} color={A.tech} o={p(0.08, 0.18)}><DefBadge text="DEFINITION" color={A.tech} o={p(0.1, 0.16)} /><div style={{ marginTop: 13, fontFamily: SANS, fontSize: 27, color: T.text }}>The lowest and highest prices seen over the last 52 weeks.</div></Card><Card theme={T} x={970} y={190} w={760} h={128} color={A.tech} o={p(0.2, 0.3)}><Formula parts={[["Position", A.tech], ["= (price − low) ÷ (high − low) × 100", T.text]]} size={25} o={p(0.22, 0.31)} /></Card><div style={{ position: "absolute", left: 140, top: 430, width: 1300, opacity: p(0.35, 0.72) }}><div style={{ height: 14, background: `linear-gradient(90deg, ${A.risk}, ${A.tech}, ${A.fund})`, borderRadius: 8 }} /><div style={{ position: "absolute", left: "8%", top: -18, width: 50, height: 50, borderRadius: 28, background: T.text, border: `7px solid ${A.tech}`, boxShadow: `0 0 24px ${A.tech}`, transform: "translateX(-25px)" }} /><div style={{ display: "flex", justifyContent: "space-between", marginTop: 24, fontFamily: MONO, fontSize: 26, color: T.text }}><span>52-WK LOW</span><span>52-WK HIGH</span></div></div><div style={{ position: "absolute", left: 160, top: 570, opacity: p(0.65, 0.75) }}><StatChip label="Reliance · worked position" value="8% of range" color={A.tech} hero /></div><div style={{ position: "absolute", left: 650, top: 570, fontFamily: SANS, fontSize: 29, color: T.text, opacity: p(0.7, 0.8) }}>₹1,287 sits close to the 52-week low.</div><div style={{ position: "absolute", left: 150, top: 720, fontFamily: MONO, fontSize: 24, color: A.tech, opacity: p(0.77, 0.87) }}>LOW ← price location → HIGH</div><Verdict text="Location adds context: near the low is weak tape, not proof of cheapness." o={p(0.84, 0.9)} /><Motion /></Stage>; };

// NARRATION: Put the indicators together. Reliance is ₹1,287 versus a ₹1,396 200-DMA, RSI 42.9, only 8% up its 52-week range, and beta 0.94. The plain-English read is weak tape, but technicals alone do not prove value.
export const ApplyTAScene: React.FC<{ dur?: number }> = ({ dur }) => { const p = useP(dur); const items = [{ l: "TREND", v: "₹1,287 < ₹1,396", s: "below 200-DMA", c: A.tech }, { l: "MOMENTUM", v: "RSI 42.9", s: "soft, not oversold", c: A.tech }, { l: "LOCATION", v: "8% of 52-wk", s: "near the low", c: A.risk }, { l: "MARKET SENSITIVITY", v: "β 0.94", s: "roughly market-like", c: A.main }]; return <Stage><SceneProgress p={p} color={A.tech} /><FQHead kicker="TECHNICALS · 06 · WORKED READING" title="Reading Reliance with all four lenses" color={A.tech} p={p} /><div style={{ position: "absolute", left: 110, top: 190, fontFamily: SANS, fontSize: 33, color: T.text, opacity: p(0.08, 0.18) }}>One stock. Four simple questions.</div><div style={{ position: "absolute", left: 120, top: 290, width: 1424, height: 360 }}>{items.map((it, i) => <Card key={it.l} theme={T} x={(i % 2) * 724} y={Math.floor(i / 2) * 190} w={700} h={165} color={it.c} o={p(0.22 + i * 0.11, 0.31 + i * 0.11)} pad="20px 26px"><div style={{ fontFamily: MONO, letterSpacing: 2, fontSize: 20, color: it.c }}>{it.l}</div><div style={{ fontFamily: MONO, fontWeight: 800, fontSize: 35, color: T.text, marginTop: 12 }}>{it.v}</div><div style={{ fontFamily: SANS, fontSize: 24, color: T.muted, marginTop: 8 }}>{it.s}</div></Card>)}</div><div style={{ position: "absolute", left: 120, top: 690, width: 1420, borderLeft: `6px solid ${A.tech}`, padding: "20px 28px", background: mix(T.panel, A.tech, 0.1), opacity: p(0.72, 0.82) }}><DefBadge text="PLAIN-ENGLISH VERDICT" color={A.tech} o={p(0.73, 0.79)} /><div style={{ fontFamily: SANS, fontSize: 35, fontWeight: 800, color: T.text, marginTop: 15 }}>Weak tape, but cheap — check the fundamentals before acting.</div></div><Wire x1={840} y1={445} x2={1060} y2={445} p={p(0.62, 0.73)} color={A.tech} w={4} /><Flow x1={900} y1={445} x2={1100} y2={445} curve={-70} color={A.tech} n={7} speed={0.012} size={9} o={0.8} /><Verdict text="Technical analysis describes the tape; it does not replace valuation or risk checks." o={p(0.84, 0.9)} /></Stage>; };
