"""Psychology of Money — screenplay.

HARD RULE: narration only speaks what is printed on that beat's props.
Each row/line has a `say` field; helpers join those says with [pause].
Figures are from Housel 2020 (book-dated), not live markets.
"""
G = "#E8B86D"; R = "#F87171"; OK = "#34D399"; M = "#A78BFA"; L = "#38BDF8"; D = "#FBBF24"

def _plain(rows):
    return [{k: v for k, v in r.items() if k != "say"} for r in rows]

def S(sid, variant, props, say_parts):
    nar = " [pause] ".join(s.strip() for s in say_parts if s and s.strip())
    return {"id": sid, "variant": variant, "props": props, "narration": nar}

def Div(n, title, lines, color):
    return S("divider", "pm_divider",
             {"n": n, "total": 20, "title": title, "lines": [x[0] for x in lines], "color": color},
             [f"Chapter {n}. {title}."] + [x[1] for x in lines])

def Sheet(sid, kicker, title, rows, color, note=""):
    return S(sid, "pm_sheet",
             {"kicker": kicker, "title": title, "rows": _plain(rows), "color": color, "note": note},
             [r["say"] for r in rows])

def Dual(sid, kicker, title, left, right, color, note=""):
    lp = {**left, "lines": [x[0] for x in left["lines"]]}
    rp = {**right, "lines": [x[0] for x in right["lines"]]}
    says = [f"{left['name']}. {left.get('tag', '')}".strip()] + [x[1] for x in left["lines"]]
    says += [f"{right['name']}. {right.get('tag', '')}".strip()] + [x[1] for x in right["lines"]]
    return S(sid, "pm_dual",
             {"kicker": kicker, "title": title, "left": lp, "right": rp, "color": color, "note": note},
             says)

def List(sid, kicker, title, items, color, note=""):
    return S(sid, "pm_list",
             {"kicker": kicker, "title": title, "items": [x[0] for x in items], "color": color, "note": note},
             [x[1] for x in items])

CHIPS = [
    {"n": 1, "title": "No One's Crazy", "c": M}, {"n": 2, "title": "Luck and Risk", "c": L},
    {"n": 3, "title": "Never Enough", "c": R}, {"n": 4, "title": "Compounding", "c": G},
    {"n": 5, "title": "Stay Wealthy", "c": OK}, {"n": 6, "title": "Tails, You Win", "c": L},
    {"n": 7, "title": "Freedom", "c": G}, {"n": 8, "title": "Car Paradox", "c": D},
    {"n": 9, "title": "Hidden Wealth", "c": M}, {"n": 10, "title": "Save Money", "c": OK},
    {"n": 11, "title": "Reasonable", "c": M}, {"n": 12, "title": "Surprise", "c": D},
    {"n": 13, "title": "Room for Error", "c": OK}, {"n": 14, "title": "You'll Change", "c": M},
    {"n": 15, "title": "Nothing's Free", "c": R}, {"n": 16, "title": "You and Me", "c": L},
    {"n": 17, "title": "Pessimism", "c": D}, {"n": 18, "title": "Believe Anything", "c": M},
    {"n": 19, "title": "All Together", "c": G}, {"n": 20, "title": "Confessions", "c": OK},
]

CHAPTERS = [
{"id": "ch00", "title": "Introduction", "segments": [
    S("title", "pm_title", {
        "kicker": "BOOK GUIDE · EDUCATION, NOT ADVICE",
        "line1": "The Psychology", "line2": "of Money",
        "sub": "Morgan Housel, 2020 · figures as printed in the book",
        "color": G,
        "points": [
            "Doing well with money is mostly behaviour, not formulas.",
            "This video walks every chapter and puts the book's numbers on screen.",
            "Education only — not investment advice. Consult a SEBI-registered adviser.",
        ],
    }, [
        "Doing well with money is mostly behaviour, not formulas.",
        "This video walks every chapter and puts the book's numbers on screen.",
        "This is education only, not investment advice. For personal decisions, consult a SEBI-registered adviser.",
    ]),
    Sheet("hook_read", "INTRODUCTION · THE OPENING PUZZLE", "Ronald Read, Vermont janitor", [
        {"k": "Work", "v": "Janitor and gas-station attendant; first in family to finish high school; hitchhiked to campus.",
         "c": OK, "say": "Ronald Read was a janitor and gas-station attendant. He was first in his family to finish high school, and he hitchhiked to campus."},
        {"k": "House", "v": "Bought a two-bedroom house for $12,000 at age 38 and lived there for life.",
         "c": G, "say": "He bought a two-bedroom house for twelve thousand dollars at age thirty-eight, and lived there for life."},
        {"k": "Life", "v": "Widowed at 50; hobby: chopping firewood. Died 2014, age 92.",
         "c": M, "say": "He was widowed at fifty. His hobby was chopping firewood. He died in twenty fourteen, at age ninety-two."},
        {"k": "Estate", "v": "More than $8 million: $2 million to family, more than $6 million to hospital and library.",
         "c": OK, "say": "His estate was more than eight million dollars. Two million went to family. More than six million went to his local hospital and library."},
        {"k": "How", "v": "No lottery, no inheritance: saved what he could, bought blue-chip stocks, waited decades.",
         "c": L, "say": "There was no lottery and no inheritance. He saved what he could, bought blue-chip stocks, and waited for decades."},
    ], OK, "Book-dated story, 2020 text. Not a forecast."),
    Sheet("hook_fuscone", "INTRODUCTION · THE OTHER DOSSIER", "Richard Fuscone, Harvard M.B.A.", [
        {"k": "Résumé", "v": "Harvard M.B.A.; Merrill Lynch executive; retired in his 40s; Crain's 40 under 40.",
         "c": D, "say": "Richard Fuscone had a Harvard M.B.A., was a Merrill Lynch executive, retired in his forties, and made Crain's forty under forty."},
        {"k": "House", "v": "Expanded an 18,000-square-foot Greenwich home: 11 bathrooms, 2 elevators, 2 pools, 7 garages.",
         "c": R, "say": "He borrowed heavily to expand an eighteen thousand square foot Greenwich home, with eleven bathrooms, two elevators, two pools, and seven garages."},
        {"k": "Cost", "v": "More than $90,000 a month to maintain. Then 2008 hit.",
         "c": D, "say": "It cost more than ninety thousand dollars a month to maintain. Then two thousand eight hit."},
        {"k": "2008", "v": "Told a bankruptcy judge: 'I currently have no income.' Palm Beach house foreclosed.",
         "c": R, "say": "He told a bankruptcy judge in two thousand eight that he currently had no income. His Palm Beach house was foreclosed."},
        {"k": "2014", "v": "Greenwich foreclosure sold 75% below the insurer's figure — five months before Read's gifts.",
         "c": M, "say": "In twenty fourteen the Greenwich mansion sold at foreclosure for seventy-five percent less than an insurer had figured. That was five months before Read's charitable gifts."},
    ], R, "Book-dated story, 2020 text. Not a forecast."),
    Sheet("why", "WHY THIS BOOK EXISTS", "Finance is a soft skill", [
        {"k": "The contrast", "v": "A janitor with no degree can outperform a Harvard-trained executive in investing.",
         "c": G, "say": "The contrast: a janitor with no degree can outperform a Harvard-trained executive in investing."},
        {"k": "Not medicine", "v": "A janitor will not outperform a Harvard surgeon, architect, or nuclear engineer.",
         "c": R, "say": "That does not happen in medicine. A janitor will not outperform a Harvard surgeon, architect, or nuclear engineer."},
        {"k": "Two explanations", "v": "Luck independent of skill — or behaviour mattering more than technical knowledge.",
         "c": L, "say": "Two explanations: luck independent of skill, or behaviour mattering more than technical knowledge."},
        {"k": "Housel's bet", "v": "Financial success is mostly a soft skill: how you behave is more important than what you know.",
         "c": OK, "say": "Housel's bet: financial success is mostly a soft skill. How you behave is more important than what you know."},
        {"k": "2014 estates", "v": "2,813,503 Americans died in 2014; fewer than 4,000 left a net worth over $8 million. Read was one.",
         "c": M, "say": "In twenty fourteen, two million eight hundred thirteen thousand five hundred three Americans died. Fewer than four thousand left a net worth over eight million dollars. Read was one of them."},
    ], M, "Source: Housel 2020 introduction."),
    S("map", "pm_grid", {
        "kicker": "TWENTY CHAPTERS ON THIS GRID", "title": "Every box is a later chapter",
        "chips": CHIPS, "color": G,
        "note": "Audio names the same twenty titles you see in the boxes.",
    }, [
        "Chapter one, No One's Crazy. Two, Luck and Risk. Three, Never Enough. Four, Compounding. Five, Stay Wealthy.",
        "Six, Tails, You Win. Seven, Freedom. Eight, Car Paradox. Nine, Hidden Wealth. Ten, Save Money.",
        "Eleven, Reasonable. Twelve, Surprise. Thirteen, Room for Error. Fourteen, You'll Change. Fifteen, Nothing's Free.",
        "Sixteen, You and Me. Seventeen, Pessimism. Eighteen, Believe Anything. Nineteen, All Together. Twenty, Confessions.",
    ]),
]},
{"id": "ch01", "title": "No One's Crazy", "segments": [
    Div(1, "No One's Crazy", [
        ("People are not dumb with money. They are consistent with their own history.",
         "People are not dumb with money. They are consistent with their own history."),
        ("Your life is a tiny sample of the world, and a huge sample of your beliefs.",
         "Your life is a tiny sample of the world, and a huge sample of your beliefs."),
    ], M),
    Sheet("ratio", "CHAPTER 1 · THE RATIO", "Experience versus the world", [
        {"k": "Experience", "v": "Your personal money history may be 0.00000001% of what has happened in the world.",
         "c": D, "say": "Your personal money history may be zero point zero zero zero zero zero zero zero one percent of what has happened in the world."},
        {"k": "Beliefs", "v": "That same sliver may be about 80% of how you think the world works.",
         "c": M, "say": "That same sliver may be about eighty percent of how you think the world works."},
        {"k": "Result", "v": "Equally smart people disagree on recessions, investing, priorities, and how much risk to take.",
         "c": L, "say": "Equally smart people disagree on recessions, investing, priorities, and how much risk to take."},
        {"k": "Depression", "v": "Frederick Lewis Allen: the Great Depression marked millions of Americans inwardly for life — with a range of experiences.",
         "c": G, "say": "Frederick Lewis Allen wrote that the Great Depression marked millions of Americans inwardly for the rest of their lives, with a range of experiences."},
        {"k": "J.F.K.", "v": "Asked what he remembered of the Depression, Kennedy said he had no first-hand memory of hardship — different life, different model.",
         "c": OK, "say": "Asked what he remembered of the Depression, Kennedy said he had no first-hand memory of hardship. Different life, different model."},
    ], M),
    Dual("unemp", "SAME MONTH, DIFFERENT COUNTRY", "November 2009 unemployment",
        {"name": "The headline", "tag": "one average", "c": D, "lines": [
            ("U.S. nationwide unemployment, November 2009: around 10%.",
             "U.S. nationwide unemployment in November two thousand nine was around ten percent."),
            ("An average hides who actually lost work.",
             "An average hides who actually lost work."),
        ]},
        {"name": "The split", "tag": "same month", "c": R, "lines": [
            ("African American males age 16–19 without a high-school diploma: 49% unemployed.",
             "African American males age sixteen to nineteen without a high-school diploma: forty-nine percent unemployed."),
            ("Caucasian females over 45 with a college degree: 4% unemployed.",
             "Caucasian females over age forty-five with a college degree: four percent unemployed."),
            ("Local stock markets in Germany and Japan were wiped out in World War Two; German farms at war's end: about 1,000 calories a day.",
             "Local stock markets in Germany and Japan were wiped out in World War Two. At the end of the war, German farms produced about one thousand calories a day per person."),
            ("The U.S. stock market more than doubled over the war years — not the same scar.",
             "The U.S. stock market more than doubled over the war years. That is not the same scar."),
        ]}, M, "Figures as printed in the book for those dates."),
    Sheet("lotto", "WHY LOTTERY TICKETS EXIST", "A terrible product that still sells", [
        {"k": "Spend", "v": "Lower-income households: about $412 a year on lottery tickets — four times higher-income households.",
         "c": D, "say": "Lower-income households spent about four hundred twelve dollars a year on lottery tickets, four times higher-income households."},
        {"k": "Emergency", "v": "Those buyers are largely the same people who say they could not find $400 in an emergency.",
         "c": R, "say": "Those buyers are largely the same people who say they could not find four hundred dollars in an emergency."},
        {"k": "Spreadsheet", "v": "As an investment the ticket is awful. As a purchased dream of a gap, it can be the only option in the room.",
         "c": M, "say": "As an investment the ticket is awful. As a purchased dream of a gap, it can be the only option in the room."},
        {"k": "Lesson", "v": "Do not call the buyer crazy until you see the financial room they live in.",
         "c": OK, "say": "Do not call the buyer crazy until you see the financial room they live in."},
    ], D),
    Sheet("retire", "RETIREMENT IS NEW", "Pensions were never universal", [
        {"k": "2018 stock", "v": "End of 2018: about $27 trillion in U.S. retirement accounts.",
         "c": G, "say": "At the end of two thousand eighteen there was about twenty-seven trillion dollars in U.S. retirement accounts."},
        {"k": "Work after 65", "v": "Participation rate of men age 65+ stayed above 50% until the mid-twentieth century.",
         "c": D, "say": "The participation rate of men age sixty-five and over stayed above fifty percent until the mid twentieth century."},
        {"k": "First check", "v": "Ida May Fuller, 1940: first Social Security check $22.54 — about $416 in later dollars.",
         "c": L, "say": "Ida May Fuller cashed the first Social Security check in nineteen forty: twenty-two dollars and fifty-four cents, about four hundred sixteen dollars in later dollars."},
        {"k": "1980s", "v": "Average Social Security check for retirees did not exceed $1,000 a month, inflation-adjusted, until the 1980s.",
         "c": M, "say": "The average Social Security check for retirees did not exceed one thousand dollars a month, inflation-adjusted, until the nineteen eighties."},
        {"k": "Poverty", "v": "More than a quarter of Americans over 65 were in Census poverty until the late 1960s.",
         "c": R, "say": "More than a quarter of Americans over age sixty-five were classified as living in poverty until the late nineteen sixties."},
        {"k": "1975 pension", "v": "Only a quarter of those 65+ had pension income in 1975; among them, ~15% of household income came from it.",
         "c": OK, "say": "Only a quarter of those age sixty-five or older had pension income in nineteen seventy-five. Among them, about fifteen percent of household income came from a pension."},
    ], M, "Employee Benefit Research Institute, as cited in the book."),
]},
{"id": "ch02", "title": "Luck and Risk", "segments": [
    Div(2, "Luck and Risk", [
        ("Luck and risk are the same coin. We see the winner and ignore the roommate who died.",
         "Luck and risk are the same coin. We see the winner and ignore the roommate who died."),
        ("Judge processes, not one outcome. Nothing is as good or as bad as it looks.",
         "Judge processes, not one outcome. Nothing is as good or as bad as it looks."),
    ], L),
    Dual("lakeside", "LAKESIDE SCHOOL", "Bill Gates, Paul Allen, Kent Evans",
        {"name": "The lucky room", "tag": "1968 funnel", "c": OK, "lines": [
            ("Lakeside had a computer when almost no high school did — Gates and Allen used it.",
             "Lakeside had a computer when almost no high school did. Bill Gates and Paul Allen used it."),
            ("1968: roughly 303 million high-school-age people in the world; about 18 million in the U.S.",
             "In nineteen sixty-eight there were roughly three hundred three million high-school-age people in the world, about eighteen million in the United States."),
            ("Start with 303 million, end with a few hundred in that building. That is luck.",
             "Start with three hundred three million, end with a few hundred in that building. That is luck."),
        ]},
        {"name": "The missing partner", "tag": "risk", "c": R, "lines": [
            ("Kent Evans was Gates's best friend and classmate in that same room.",
             "Kent Evans was Gates's best friend and classmate in that same room."),
            ("He died in a mountaineering accident as a teenager.",
             "He died in a mountaineering accident as a teenager."),
            ("Same unusual environment: one path to Microsoft, one funeral. Luck and risk arrived together.",
             "Same unusual environment: one path to Microsoft, one funeral. Luck and risk arrived together."),
        ]}, L),
    Sheet("yahoo", "HINDSIGHT ON BOLDNESS", "Yahoo's 2006 offer for Facebook", [
        {"k": "2006", "v": "Yahoo offered about $1 billion to buy Facebook. Mark Zuckerberg said no.",
         "c": L, "say": "In two thousand six, Yahoo offered about one billion dollars to buy Facebook. Mark Zuckerberg said no."},
        {"k": "If it won", "v": "Because Facebook later became enormous, the refusal is taught as genius.",
         "c": OK, "say": "Because Facebook later became enormous, the refusal is taught as genius."},
        {"k": "If it lost", "v": "If Facebook had stalled, the same no would be taught as arrogance.",
         "c": R, "say": "If Facebook had stalled, the same no would be taught as arrogance."},
        {"k": "Rule", "v": "Risk is what remains after you subtract luck from a good outcome. Do not copy leverage from a winner's highlight reel.",
         "c": M, "say": "Risk is what remains after you subtract luck from a good outcome. Do not copy leverage from a winner's highlight reel."},
    ], L),
    List("do", "WHAT TO DO WITH LUCK AND RISK", "The chapter's working rules", [
        ("Do not assume a rich person is purely skilled, or a broke person is purely foolish.",
         "Do not assume a rich person is purely skilled, or a broke person is purely foolish."),
        ("Look at decisions under their control, then at timing, health, and one-off breaks.",
         "Look at decisions under their control, then at timing, health, and one-off breaks."),
        ("The book's line: nothing is as good or as bad as it looks.",
         "The book's line: nothing is as good or as bad as it looks."),
        ("That humility stops you cloning someone else's debt, and quitting a good process after one bad year.",
         "That humility stops you cloning someone else's debt, and quitting a good process after one bad year."),
    ], OK),
]},
{"id": "ch03", "title": "Never Enough", "segments": [
    Div(3, "Never Enough", [
        ("The hardest financial skill is stopping when you already have enough.",
         "The hardest financial skill is stopping when you already have enough."),
        ("Do not risk what you have and need for what you do not have and do not need.",
         "Do not risk what you have and need for what you do not have and do not need."),
    ], R),
    Dual("gupta", "ALREADY RICH, STILL REACHING", "Gupta and Madoff",
        {"name": "Rajat Gupta", "tag": "McKinsey", "c": R, "lines": [
            ("Reported net worth about $100 million. The book: that throws off roughly $600 an hour, 24 hours a day.",
             "Reported net worth about one hundred million dollars. The book says that throws off roughly six hundred dollars an hour, twenty-four hours a day."),
            ("Still passed insider tips. Rajaratnam made a quick $1 million.",
             "He still passed insider tips. Rajaratnam made a quick one million dollars."),
            ("Prosecutors: Gupta's tips linked to about $17 million in profits. Gupta went to prison.",
             "Prosecutors said Gupta's tips linked to about seventeen million dollars in profits. Gupta went to prison."),
        ]},
        {"name": "Bernie Madoff", "tag": "already a fortune", "c": D, "lines": [
            ("Legal market-making: about $25 to $50 million a year before the fraud.",
             "Legal market-making made about twenty-five to fifty million dollars a year before the fraud."),
            ("Book: Madoff's electronic volume equaled about 9% of the New York exchange.",
             "The book says Madoff's electronic volume equaled about nine percent of the New York exchange."),
            ("That legal business was not enough. The Ponzi is what people remember. Others were ruined.",
             "That legal business was not enough. The Ponzi is what people remember. Others were ruined."),
        ]}, R, "Do not risk what you have and need for what you do not have and do not need."),
    Sheet("ladder", "THE COMPARISON LADDER", "Someone is always richer", [
        {"k": "Rookie", "v": "A rookie baseball player on $500,000 a year is rich in any normal life.",
         "c": OK, "say": "A rookie baseball player on five hundred thousand dollars a year is rich in any normal life."},
        {"k": "Trout", "v": "Mike Trout: 12-year, $430 million contract — about $36 million a year. The rookie can feel broke.",
         "c": L, "say": "Mike Trout had a twelve-year, four hundred thirty million dollar contract, about thirty-six million a year. The rookie can feel broke."},
        {"k": "Hedge fund", "v": "To feel like a top earner, the book says you might need $340 million in one year.",
         "c": D, "say": "To feel like a top hedge-fund earner, the book says you might need three hundred forty million dollars in one year."},
        {"k": "2018 pay", "v": "Some managers earned at least $770 million in 2018.",
         "c": R, "say": "Some managers earned at least seven hundred seventy million dollars in two thousand eighteen."},
        {"k": "Bezos 2018", "v": "Jeff Bezos's net worth increased by about $24 billion in 2018 — the ladder has no last rung.",
         "c": G, "say": "Jeff Bezos's net worth increased by about twenty-four billion dollars in two thousand eighteen. The ladder has no last rung."},
    ], D),
    List("enough", "NAME ENOUGH IN ADVANCE", "The antidote", [
        ("Decide what enough is before results inflate your expectations.",
         "Decide what enough is before results inflate your expectations."),
        ("Enough is people you will not disappoint, plus risk that lets you stay in the game.",
         "Enough is people you will not disappoint, plus risk that lets you stay in the game."),
        ("Rockefeller, asked how much is enough: 'Just a little bit more' — a warning, not a plan.",
         "Rockefeller, asked how much is enough, said just a little bit more. That is a warning, not a plan."),
        ("If expectations rise with every win, compounding cannot catch a moving finish line.",
         "If expectations rise with every win, compounding cannot catch a moving finish line."),
    ], OK),
]},
{"id": "ch04", "title": "Compounding", "segments": [
    Div(4, "Compounding", [
        ("Buffett's secret is time, not a magic annual rate.",
         "Buffett's secret is time, not a magic annual rate."),
        ("Linear intuition cannot feel an exponential. That is why compounding confounds.",
         "Linear intuition cannot feel an exponential. That is why compounding confounds."),
    ], G),
    Sheet("buffett", "AS THE BOOK PRINTS IT (2020)", "Warren Buffett's pile arrived late", [
        {"k": "Net worth", "v": "As Housel wrote: $84.5 billion.",
         "c": G, "say": "As Housel wrote, Buffett's net worth was eighty-four point five billion dollars."},
        {"k": "After 50", "v": "$84.2 billion of that was accumulated after his 50th birthday.",
         "c": G, "say": "Eighty-four point two billion of that was accumulated after his fiftieth birthday."},
        {"k": "After 65", "v": "$81.5 billion came after he qualified for Social Security, in his mid-60s.",
         "c": OK, "say": "Eighty-one point five billion came after he qualified for Social Security, in his mid-sixties."},
        {"k": "Start", "v": "Serious investing from age 10. By 30: $1 million then, about $9.3 million inflation-adjusted.",
         "c": L, "say": "He began serious investing at age ten. By thirty he had one million dollars, about nine point three million inflation-adjusted."},
        {"k": "Rate cited", "v": "Rough lifetime compounding cited: about 22% a year. Skill is investing. Secret is time.",
         "c": D, "say": "Rough lifetime compounding cited: about twenty-two percent a year. His skill is investing. His secret is time."},
        {"k": "Books", "v": "More than 2,000 books try to explain Buffett. Few stress the calendar.",
         "c": M, "say": "More than two thousand books try to explain Buffett. Few stress the calendar."},
    ], G, "Book-dated fortune, not a live Forbes quote."),
    S("if", "pm_compound", {
        "kicker": "THE BOOK'S THOUGHT EXPERIMENT", "title": "Same 22%, far less time",
        "color": G,
        "series": [
            {"label": "$25,000 at 22% for 30 years", "start": 25000, "rate": 0.22, "years": 30, "c": D, "endLabel": "~$11.9 million"},
        ],
        "facts": [
            {"k": "Setup", "v": "$25,000 at age 30, still 22% a year, stop at 60.", "c": D},
            {"k": "Ending pile", "v": "About $11.9 million — not $84.5 billion.", "c": G},
            {"k": "Gap", "v": "99.9% less than the actual book net worth.", "c": R},
            {"k": "Why", "v": "The exponential does almost nothing for years, then stands up.", "c": M},
        ],
        "note": "Counterfactual from the book. The on-screen curve is 22% for 30 years from $25,000.",
    }, [
        "Setup: twenty-five thousand dollars at age thirty, still twenty-two percent a year, stop at sixty.",
        "The ending pile is about eleven point nine million dollars, not eighty-four point five billion.",
        "That is ninety-nine point nine percent less than the actual book net worth.",
        "The exponential does almost nothing for years, then stands up. That is why compounding confounds.",
    ]),
    Dual("simons", "HIGHER RATE, LESS TIME", "Jim Simons versus Buffett, in the book",
        {"name": "Buffett", "tag": "~22% / year", "c": G, "lines": [
            ("Started as a child; roughly 75 years of compounding.",
             "Buffett started as a child, with roughly seventy-five years of compounding."),
            ("Book net worth: $84.5 billion.",
             "Book net worth: eighty-four point five billion dollars."),
        ]},
        {"name": "Jim Simons", "tag": "~66% since 1988", "c": L, "lines": [
            ("Renaissance Technologies: about 66% a year since 1988 — roughly 3× Buffett's cited rate.",
             "Jim Simons compounded about sixty-six percent a year since nineteen eighty-eight, roughly three times Buffett's cited rate."),
            ("Found his stride near age 50. Book net worth: about $21 billion — roughly 75% less rich.",
             "He found his stride near age fifty. Book net worth: about twenty-one billion, roughly seventy-five percent less rich."),
            ("If 66% ran for Buffett's 70-year span, the book says the pile becomes tens of quintillions — a joke about time, not a target rate.",
             "If sixty-six percent ran for Buffett's seventy-year span, the book says the pile becomes tens of quintillions. That is a joke about time, not a target rate."),
        ]}, G),
]},
{"id": "ch05", "title": "Stay Wealthy", "segments": [
    Div(5, "Stay Wealthy", [
        ("Getting money and keeping money are different skills.",
         "Getting money and keeping money are different skills."),
        ("Survival is the strategy: stay in the game so compounding can finish.",
         "Survival is the strategy: stay in the game so compounding can finish."),
    ], OK),
    Dual("skills", "OFFENSE VERSUS DEFENSE", "Two jobs, two personalities",
        {"name": "Getting wealthy", "tag": "offense", "c": L, "lines": [
            ("Needs taking risk, optimism, concentration, hustle.",
             "Getting wealthy needs taking risk, optimism, concentration, and hustle."),
            ("Fails as fragility: a great return that ends in year twelve.",
             "It fails as fragility: a great return that ends in year twelve."),
        ]},
        {"name": "Staying wealthy", "tag": "defense", "c": OK, "lines": [
            ("Needs humility, useful fear, cash, frugality, room for error.",
             "Staying wealthy needs humility, useful fear, cash, frugality, and room for error."),
            ("Wins as longevity: a good return that lasts fifty years beats a spectacular one that blows up.",
             "It wins as longevity. A good return that lasts fifty years beats a spectacular one that blows up."),
            ("Margin of safety is not about being right. It is about not being forced out.",
             "A margin of safety is not about being right. It is about not being forced out."),
        ]}, OK),
    Sheet("rick", "RICK GUERIN", "Leverage turned a crash into a forced sale", [
        {"k": "Partners", "v": "Charlie Munger and Rick Guerin were both early Buffett partners.",
         "c": L, "say": "Charlie Munger and Rick Guerin were both early Buffett partners."},
        {"k": "Margin", "v": "Guerin used leverage. In the early 1970s the market crushed him.",
         "c": R, "say": "Guerin used leverage. In the early nineteen seventies the market crushed him."},
        {"k": "Berkshire", "v": "Berkshire fell almost 70% in those two years.",
         "c": D, "say": "Berkshire fell almost seventy percent in those two years."},
        {"k": "Sale", "v": "Margin calls: Guerin sold Berkshire under $40 a share. Buffett later bought some of that stock.",
         "c": R, "say": "Margin calls: Guerin sold Berkshire under forty dollars a share. Buffett later bought some of that stock."},
        {"k": "Buffett wait", "v": "Buffett did not need the money, so he was not a forced seller.",
         "c": OK, "say": "Buffett did not need the money, so he was not a forced seller."},
        {"k": "Rule", "v": "Staying wealthy means arranging life so you never have to sell at the bottom.",
         "c": G, "say": "Staying wealthy means arranging life so you never have to sell at the bottom."},
    ], R),
    Sheet("cash", "CASH LOOKS DUMB UNTIL YOU NEED IT", "The 1% versus 10% nag", [
        {"k": "The nag", "v": "Illustration: cash earns 1%, stocks 10%. The 9-point gap nags every day.",
         "c": D, "say": "Illustration: cash earns one percent, stocks ten percent. The nine-point gap nags every day."},
        {"k": "True yield", "v": "The book's point: cash's real yield is not 1%. It is the option not to become a forced seller.",
         "c": OK, "say": "The book's point: cash's real yield is not one percent. It is the option not to become a forced seller."},
        {"k": "Housing", "v": "The book cites a housing boom and bust that touched nearly 10 million households.",
         "c": R, "say": "The book cites a housing boom and bust that touched nearly ten million households."},
        {"k": "Plan", "v": "A rate you can survive: '8% would be great; 4% I can still live with.'",
         "c": G, "say": "Plan a rate you can survive. It would be great if the market returns eight percent a year; if it only does four, you can still live with it."},
    ], D),
]},
{"id": "ch06", "title": "Tails, You Win", "segments": [
    Div(6, "Tails, You Win", [
        ("A few extreme outcomes drive most of finance. Being wrong often can still win.",
         "A few extreme outcomes drive most of finance. Being wrong often can still win."),
        ("Index-like patience is how you make sure you own the tail.",
         "Index-like patience is how you make sure you own the tail."),
    ], L),
    Sheet("vc", "VENTURE MATH (CORRELATION VENTURES)", "More than 21,000 financings, 2004–2014", [
        {"k": "Lost money", "v": "65% of venture financings lost money.",
         "c": R, "say": "Sixty-five percent of venture financings lost money."},
        {"k": "10 to 20×", "v": "Two and a half percent made ten times to twenty times.",
         "c": D, "say": "Two and a half percent made ten times to twenty times."},
        {"k": "Over 20×", "v": "One percent made more than a twenty-times return.",
         "c": L, "say": "One percent made more than a twenty-times return."},
        {"k": "50× club", "v": "Half a percent — about 100 companies out of 21,000 — earned 50× or more. That is where most industry returns come from.",
         "c": OK, "say": "Half a percent, about one hundred companies out of twenty-one thousand, earned fifty times or more. That is where most industry returns come from."},
    ], L, "Correlation Ventures, as cited in the book."),
    Sheet("russell", "PUBLIC STOCKS LOOK LIKE VENTURE", "Russell 3000 since 1980 (J.P. Morgan A.M., as cited)", [
        {"k": "Failed names", "v": "40% of Russell 3000 components lost at least 70% of their value and never recovered.",
         "c": R, "say": "Forty percent of Russell three thousand components lost at least seventy percent of their value and never recovered."},
        {"k": "Who drove it", "v": "Effectively all of the index's overall returns came from 7% of companies that outperformed by at least two standard deviations.",
         "c": G, "say": "Effectively all of the index's overall returns came from seven percent of companies that outperformed by at least two standard deviations."},
        {"k": "Bessembinder", "v": "1926–2016: the best-performing about 4% of listed companies explain the net gain of the entire U.S. stock market; the rest collectively matched Treasury bills.",
         "c": L, "say": "Bessembinder, nineteen twenty-six to twenty sixteen: the best-performing about four percent of listed companies explain the net gain of the entire U.S. stock market. The rest collectively matched Treasury bills."},
        {"k": "2018 tails", "v": "Amazon drove about 6% of S&P 500 returns in 2018. Apple: almost 7%.",
         "c": M, "say": "Amazon drove about six percent of S and P five hundred returns in two thousand eighteen. Apple: almost seven percent."},
    ], L),
    Sheet("disney", "ONE TAIL CAN PAY THE REST", "Snow White versus hundreds of shorts", [
        {"k": "Before", "v": "Disney's first studio went bankrupt. By the mid-1930s he had produced more than 400 cartoons; most lost money.",
         "c": R, "say": "Disney's first studio went bankrupt. By the mid nineteen thirties he had produced more than four hundred cartoons. Most lost money."},
        {"k": "Snow White", "v": "The $8 million earned in the first six months of 1938 dwarfed anything before. Debts paid. New Burbank studio. Celebrity.",
         "c": OK, "say": "The eight million dollars earned in the first six months of nineteen thirty-eight dwarfed anything before. Debts were paid. A new Burbank studio. Celebrity."},
        {"k": "The 83 minutes", "v": "By 1938 he had produced several hundred hours of film. In business terms, the 83 minutes of Snow White were what mattered.",
         "c": G, "say": "By nineteen thirty-eight he had produced several hundred hours of film. In business terms, the eighty-three minutes of Snow White were what mattered."},
        {"k": "Art dealers", "v": "Berggruen-style dealers bought portfolios. Perhaps 99% of works were of little value if 1% was Picasso.",
         "c": M, "say": "Art dealers like Berggruen bought portfolios. Perhaps ninety-nine percent of works were of little value if one percent was Picasso."},
    ], G),
    Sheet("sue", "STAYING IN FOR THE TAIL MONTHS", "$1 a month, 1900–2019", [
        {"k": "Sue", "v": "Invests $1 every month, rain or shine. Ends with $435,551.",
         "c": OK, "say": "Sue invests one dollar every month, rain or shine. She ends with four hundred thirty-five thousand five hundred fifty-one dollars."},
        {"k": "Jim", "v": "Sells in recessions, holds cash, buys back after. Ends with $257,386.",
         "c": D, "say": "Jim sells in recessions, holds cash, and buys back after. He ends with two hundred fifty-seven thousand three hundred eighty-six dollars."},
        {"k": "Tom", "v": "Sells six months after a recession starts, buys six months after it ends. Ends with $234,476.",
         "c": R, "say": "Tom sells six months after a recession starts and buys six months after it ends. He ends with two hundred thirty-four thousand four hundred seventy-six dollars."},
        {"k": "The 22%", "v": "1,428 months in the span; just over 300 were recession months — about 22% of the time. Sue's cool there is most of the gap.",
         "c": L, "say": "There were one thousand four hundred twenty-eight months in the span. Just over three hundred were recession months, about twenty-two percent of the time. Sue keeping her cool then is most of the gap."},
        {"k": "2008", "v": "How you behaved in a few months of late 2008 and early 2009 can outweigh everything from 2000 to 2008.",
         "c": M, "say": "How you behaved in a few months of late two thousand eight and early two thousand nine can outweigh everything from two thousand to two thousand eight."},
    ], OK),
]},
{"id": "ch07", "title": "Freedom", "segments": [
    Div(7, "Freedom", [
        ("The highest dividend money pays is control over your time.",
         "The highest dividend money pays is control over your time."),
        ("Saving is not only for stuff. It is for options.",
         "Saving is not only for stuff. It is for options."),
    ], G),
    Sheet("time", "THE HIGHEST DIVIDEND", "Richer, bigger homes — more worry", [
        {"k": "Gallup 2019", "v": "150,000 people in 140 countries: 45% of Americans felt 'a lot of worry' the previous day vs 39% globally.",
         "c": L, "say": "A two thousand nineteen Gallup poll of one hundred fifty thousand people in one hundred forty countries found about forty-five percent of Americans felt a lot of worry the previous day, versus thirty-nine percent globally."},
        {"k": "Stress", "v": "55% of Americans felt 'a lot of stress' the previous day. Rest of world: 35%.",
         "c": R, "say": "Fifty-five percent of Americans felt a lot of stress the previous day. For the rest of the world, thirty-five percent said the same."},
        {"k": "Income then", "v": "Median U.S. family income, inflation-adjusted: $29,000 in 1955, just over $62,000 in 2019.",
         "c": G, "say": "Median U.S. family income, inflation-adjusted, was twenty-nine thousand dollars in nineteen fifty-five, and just over sixty-two thousand in twenty nineteen."},
        {"k": "Homes", "v": "Median American home: 983 square feet in 1950, 2,436 square feet in 2018. New homes: more bathrooms than occupants.",
         "c": D, "say": "The median American home increased from nine hundred eighty-three square feet in nineteen fifty to two thousand four hundred thirty-six in twenty eighteen. The average new home now has more bathrooms than occupants."},
    ], G, "Book-dated Gallup and housing figures, 2020 text."),
    Sheet("time_save", "THE $12,000 PERMISSION SLIP", "Housel at twenty-two", [
        {"k": "Path", "v": "A day-job path around $20,000 a year. He never took a taxi.",
         "c": D, "say": "A day-job path around twenty thousand dollars a year. He never took a taxi."},
        {"k": "Gap", "v": "Living cost about $1,000 a month, earning about $1,800. The gap was the strategy.",
         "c": G, "say": "Living cost about one thousand dollars a month, earning about eighteen hundred. The gap was the strategy."},
        {"k": "Pile", "v": "He saved about $12,000 in two years, then quit to write.",
         "c": OK, "say": "He saved about twelve thousand dollars in two years, then quit to write."},
        {"k": "Lesson", "v": "Using money to buy control of your time is the most valuable use of money the book names.",
         "c": M, "say": "Using money to buy control of your time is the most valuable use of money the book names."},
    ], OK),
]},
{"id": "ch08", "title": "Car Paradox", "segments": [
    Div(8, "Car Paradox", [
        ("You want the car because of how you think it makes others see you.",
         "You want the car because of how you think it makes others see you."),
        ("They are looking at the car, not at you.",
         "They are looking at the car, not at you."),
    ], D),
    List("car", "THE MAN IN THE CAR", "What a $100,000 car actually signals", [
        ("Someone driving a $100,000 car might be wealthy — or might have $100,000 less, or $100,000 more debt.",
         "Someone driving a one hundred thousand dollar car might be wealthy, or might have one hundred thousand less, or one hundred thousand more in debt."),
        ("Humble: you want respect. The paradox: observers respect the car, not the driver.",
         "You want respect. The paradox: observers respect the car, not the driver."),
        ("Rich is a current income. Wealth is unspent options. They look the same from the curb until they do not.",
         "Rich is a current income. Wealth is unspent options. They look the same from the curb until they do not."),
        ("If the point was admiration, the book says: skip the car and keep the assets that actually buy freedom.",
         "If the point was admiration, the book says skip the car and keep the assets that actually buy freedom."),
    ], D),
]},
{"id": "ch09", "title": "Hidden Wealth", "segments": [
    Div(9, "Hidden Wealth", [
        ("Wealth is what you do not see: the cars not bought, the upgrades declined.",
         "Wealth is what you do not see: the cars not bought, the upgrades declined."),
        ("Spending is the visible part. The unseen pile is the whole point.",
         "Spending is the visible part. The unseen pile is the whole point."),
    ], M),
    Sheet("unseen", "WEALTH IS THE UNSPENT", "The iceberg, not the boat", [
        {"k": "Definition", "v": "Wealth is financial assets that have not yet been converted into stuff.",
         "c": G, "say": "Wealth is financial assets that have not yet been converted into stuff."},
        {"k": "Rich vs wealth", "v": "Rich is current income. Wealth is unspent income. A high salary with a high burn rate can be poor in options.",
         "c": D, "say": "Rich is current income. Wealth is unspent income. A high salary with a high burn rate can be poor in options."},
        {"k": "Why we misread", "v": "We study visible spending and copy it. We cannot study the neighbor's brokerage lot.",
         "c": M, "say": "We study visible spending and copy it. We cannot study the neighbor's brokerage lot."},
        {"k": "Energy analogy", "v": "The U.S. uses about 60% less energy per dollar of G.D.P. than it did decades ago — efficiency is invisible like savings.",
         "c": L, "say": "The U.S. uses about sixty percent less energy per dollar of G.D.P. than it did decades ago. Efficiency is invisible, like savings."},
        {"k": "Rule", "v": "The world is filled with people who look rich and are one paycheck from tight. Judge unseen reserves, not chrome.",
         "c": OK, "say": "The world is filled with people who look rich and are one paycheck from tight. Judge unseen reserves, not chrome."},
    ], M),
]},
{"id": "ch10", "title": "Save Money", "segments": [
    Div(10, "Save Money", [
        ("Building wealth has little to do with your income or investment return, and a lot to do with your savings rate.",
         "Building wealth has little to do with your income or investment return, and a lot to do with your savings rate."),
        ("You can build wealth without a high return. You cannot build it without a gap between ego and income.",
         "You can build wealth without a high return. You cannot build it without a gap between ego and income."),
    ], OK),
    List("save", "THE SAVINGS RATE", "What the chapter actually argues", [
        ("Past a modest income, your savings rate matters more than your investment rate of return.",
         "Past a modest income, your savings rate matters more than your investment rate of return."),
        ("Wealth is the gap between your ego and your income. Hide the ego, the gap appears.",
         "Wealth is the gap between your ego and your income. Hide the ego, the gap appears."),
        ("Saving is not only for a target purchase. It is flexibility, options, and waiting power.",
         "Saving is not only for a target purchase. It is flexibility, options, and waiting power."),
        ("You do not need a specific reason to save. The reason arrives later, as luck and risk do.",
         "You do not need a specific reason to save. The reason arrives later, as luck and risk do."),
        ("Everyone's savings is a function of their expectations more than their salary.",
         "Everyone's savings is a function of their expectations more than their salary."),
    ], OK),
]},
{"id": "ch11", "title": "Reasonable", "segments": [
    Div(11, "Reasonable", [
        ("Aim to be reasonable, not coldly rational. You have to stick with the plan.",
         "Aim to be reasonable, not coldly rational. You have to stick with the plan."),
        ("A technically perfect strategy you abandon is worse than a good one you love.",
         "A technically perfect strategy you abandon is worse than a good one you love."),
    ], M),
    Sheet("odds", "STAYING IN THE GAME", "U.S. market odds as the book prints them", [
        {"k": "One day", "v": "Historical odds of making money in U.S. markets: about 50/50 over one-day periods.",
         "c": D, "say": "Historical odds of making money in U.S. markets: about fifty-fifty over one-day periods."},
        {"k": "One year", "v": "About 68% in one-year periods.",
         "c": L, "say": "About sixty-eight percent in one-year periods."},
        {"k": "Ten years", "v": "About 88% in ten-year periods.",
         "c": G, "say": "About eighty-eight percent in ten-year periods."},
        {"k": "Twenty years", "v": "So far, 100% in twenty-year periods — anything that keeps you invested has a quantifiable edge.",
         "c": OK, "say": "So far, one hundred percent in twenty-year periods. Anything that keeps you invested has a quantifiable edge."},
        {"k": "Love the plan", "v": "Do what you love is not a fortune cookie here. It is endurance through lean years.",
         "c": M, "say": "Do what you love is not a fortune cookie here. It is endurance through lean years."},
    ], M),
]},
{"id": "ch12", "title": "Surprise", "segments": [
    Div(12, "Surprise", [
        ("History is the study of surprises. It is a bad map of the next surprise.",
         "History is the study of surprises. It is a bad map of the next surprise."),
        ("The most important events are the ones nobody predicted. Plan for that, not for a repeat.",
         "The most important events are the ones nobody predicted. Plan for that, not for a repeat."),
    ], D),
    Sheet("tails-hist", "THE CENTURY WAS TAILS", "U.S. history, as the book lists it", [
        {"k": "War deaths", "v": "1.3 million Americans died fighting nine major wars.",
         "c": R, "say": "One point three million Americans died fighting nine major wars."},
        {"k": "Companies", "v": "Roughly 99.9% of all companies that were created went out of business.",
         "c": D, "say": "Roughly ninety-nine point nine percent of all companies that were created went out of business."},
        {"k": "Drops", "v": "The stock market fell more than 10% from a recent high at least 102 times.",
         "c": L, "say": "The stock market fell more than ten percent from a recent high at least one hundred two times."},
        {"k": "Inflation years", "v": "Annual inflation exceeded 7% in 20 separate years.",
         "c": M, "say": "Annual inflation exceeded seven percent in twenty separate years."},
        {"k": "Seven people", "v": "The book: 0.00000000004% of people were responsible for much of the last century's direction.",
         "c": G, "say": "The book says zero point zero zero zero zero zero zero zero zero zero zero four percent of people were responsible for much of the last century's direction."},
        {"k": "Student loans", "v": "About $1.6 trillion in student loans with a 10.8% default rate — a surprise the prior generation did not budget.",
         "c": R, "say": "About one point six trillion dollars in student loans with a ten point eight percent default rate. That is a surprise the prior generation did not budget."},
        {"k": "Templeton", "v": "The four most dangerous words: this time is different. Templeton still admitted it is different at least 20% of the time.",
         "c": OK, "say": "The four most dangerous words: this time is different. Templeton still admitted it is different at least twenty percent of the time."},
    ], D),
]},
{"id": "ch13", "title": "Room for Error", "segments": [
    Div(13, "Room for Error", [
        ("The most important part of every plan is planning on the plan not going according to plan.",
         "The most important part of every plan is planning on the plan not going according to plan."),
        ("Room for error is the only way an uncertain world stays survivable.",
         "Room for error is the only way an uncertain world stays survivable."),
    ], OK),
    Sheet("margin", "MARGIN OF SAFETY", "Avoid ruin even when the odds look good", [
        {"k": "Stocks since 1870s", "v": "U.S. stocks: annual average about 6.8% after inflation since the 1870s — with brutal variation around that mean.",
         "c": G, "say": "U.S. stocks: annual average about six point eight percent after inflation since the eighteen seventies, with brutal variation around that mean."},
        {"k": "Overrun", "v": "Infrastructure projects often run 25% to 50% over budget. Your life plan will too.",
         "c": D, "say": "Infrastructure projects often run twenty-five to fifty percent over budget. Your life plan will too."},
        {"k": "Taleb", "v": "You can be risk-loving and still averse to ruin. Russian roulette has favorable odds. The downside is still unacceptable.",
         "c": R, "say": "Taleb: you can be risk-loving and still averse to ruin. Russian roulette has favorable odds. The downside is still unacceptable."},
        {"k": "95 / 5", "v": "If something is 95% likely, the 5% will still happen in a long life. If that 5% is ruin, do not take the bet.",
         "c": M, "say": "If something is ninety-five percent likely, the five percent will still happen in a long life. If that five percent is ruin, do not take the bet."},
        {"k": "Gap", "v": "Use a gap between what can happen and what you need to happen. That gap is the room for error.",
         "c": OK, "say": "Use a gap between what can happen and what you need to happen. That gap is the room for error."},
    ], OK),
]},
{"id": "ch14", "title": "You'll Change", "segments": [
    Div(14, "You'll Change", [
        ("Long-term planning is hard because your future self is a stranger.",
         "Long-term planning is hard because your future self is a stranger."),
        ("Avoid extreme plans that only work if you never change your mind.",
         "Avoid extreme plans that only work if you never change your mind."),
    ], M),
    List("change", "THE END OF HISTORY ILLUSION", "You will not want the same life", [
        ("People are very good at guessing how much they have changed — and very bad at guessing they will keep changing.",
         "People are very good at guessing how much they have changed, and very bad at guessing they will keep changing."),
        ("27% of college graduates work in a job related to their major. Compound that over a career.",
         "Twenty-seven percent of college graduates work in a job related to their major. Compound that over a career."),
        ("Sunk costs of identity: 'I am a person who holds this stock' is a trap when the thesis died.",
         "Sunk costs of identity: I am a person who holds this stock is a trap when the thesis died."),
        ("Prefer balanced plans you can revisit every few years over a 40-year vow made at 22.",
         "Prefer balanced plans you can revisit every few years over a forty-year vow made at twenty-two."),
    ], M),
]},
{"id": "ch15", "title": "Nothing's Free", "segments": [
    Div(15, "Nothing's Free", [
        ("Every return has a price. Volatility is the fee, not a fine.",
         "Every return has a price. Volatility is the fee, not a fine."),
        ("If you want the return, pay the fee. If you will not pay it, buy a quieter asset.",
         "If you want the return, pay the fee. If you will not pay it, buy a quieter asset."),
    ], R),
    Sheet("fee", "THE PRICE OF RETURNS", "Days below the old high are the bill", [
        {"k": "S&P 1950–2019", "v": "About 11% a year from 1950 to 2019 — with many stretches at least 5% below a previous high.",
         "c": G, "say": "About eleven percent a year from nineteen fifty to twenty nineteen, with many stretches at least five percent below a previous high."},
        {"k": "Netflix", "v": "Netflix returned more than 35,000% from 2002 to 2018, but traded below its previous all-time high on 94% of days.",
         "c": L, "say": "Netflix returned more than thirty-five thousand percent from two thousand two to twenty eighteen, but traded below its previous all-time high on ninety-four percent of days."},
        {"k": "Monster", "v": "Monster Beverage returned 319,000% from 1995 to 2018, below its previous high 95% of the time.",
         "c": M, "say": "Monster Beverage returned three hundred nineteen thousand percent from nineteen ninety-five to twenty eighteen, below its previous high ninety-five percent of the time."},
        {"k": "The car", "v": "A $30,000 car: pay it, buy used, or steal it. Almost nobody chooses steal. In markets, 'steal' is wanting 11% with no drawdowns.",
         "c": R, "say": "A thirty thousand dollar car: pay it, buy used, or steal it. Almost nobody chooses steal. In markets, steal is wanting eleven percent with no drawdowns."},
        {"k": "Disneyland", "v": "Tickets cost $100. That is the price of the day, not a punishment. Volatility is the same kind of price.",
         "c": D, "say": "Disneyland tickets cost one hundred dollars. That is the price of the day, not a punishment. Volatility is the same kind of price."},
        {"k": "2008 wealth", "v": "The housing bubble's end cut more than $8 trillion; household wealth fell about $6.2 trillion in the crisis window the book cites.",
         "c": R, "say": "The housing bubble's end cut more than eight trillion dollars. Household wealth fell about six point two trillion in the crisis window the book cites."},
    ], R),
]},
{"id": "ch16", "title": "You and Me", "segments": [
    Div(16, "You and Me", [
        ("You and I can look at the same price and be playing different games.",
         "You and I can look at the same price and be playing different games."),
        ("Bubbles form when short-term traders set prices that long-term owners then treat as wisdom.",
         "Bubbles form when short-term traders set prices that long-term owners then treat as wisdom."),
    ], L),
    Sheet("games", "DIFFERENT PLAYERS, SAME TICKER", "Cisco 1999 as the book's example", [
        {"k": "Cisco 1999", "v": "Cisco stock rose 300% in 1999 to $60 a share. Market value about $600 billion.",
         "c": D, "say": "Cisco stock rose three hundred percent in nineteen ninety-nine to sixty dollars a share. Market value about six hundred billion dollars."},
        {"k": "Day trader", "v": "At $60, a momentum trader can be right for a week. A 30-year owner needed a different math.",
         "c": L, "say": "At sixty dollars, a momentum trader can be right for a week. A thirty-year owner needed a different math."},
        {"k": "Turnover", "v": "The average mutual fund had about 120% annual turnover — many 'investors' were not investing.",
         "c": M, "say": "The average mutual fund had about one hundred twenty percent annual turnover. Many so-called investors were not investing."},
        {"k": "Rule", "v": "Identify your game. Do not take cues from people playing a different one.",
         "c": OK, "say": "Identify your game. Do not take cues from people playing a different one."},
    ], L),
]},
{"id": "ch17", "title": "Pessimism", "segments": [
    Div(17, "Pessimism", [
        ("Pessimism sounds smarter than optimism and travels faster.",
         "Pessimism sounds smarter than optimism and travels faster."),
        ("Progress is slow and quiet. Setbacks are fast and loud. That skews the news.",
         "Progress is slow and quiet. Setbacks are fast and loud. That skews the news."),
    ], D),
    Sheet("seduced", "WHY PESSIMISM SEDUCES", "Asymmetry of stories", [
        {"k": "News", "v": "Stocks rising 1% might get a mention. A 1% fall is reported in bold.",
         "c": D, "say": "Stocks rising one percent might get a mention. A one percent fall is reported in bold."},
        {"k": "1929 owners", "v": "Only 2.5% of Americans owned stocks on the eve of the crash — yet it defines the national memory.",
         "c": M, "say": "Only two point five percent of Americans owned stocks on the eve of the crash, yet it defines the national memory."},
        {"k": "Heart disease", "v": "U.S. death rates from heart disease declined more than 70% since 1965 — a quiet miracle versus a loud crash.",
         "c": OK, "say": "U.S. death rates from heart disease declined more than seventy percent since nineteen sixty-five. A quiet miracle versus a loud crash."},
        {"k": "40 vs 140", "v": "A 40% decline in months owns the narrative. A 140% gain over six years can go almost unnoticed.",
         "c": R, "say": "A forty percent decline in months owns the narrative. A one hundred forty percent gain over six years can go almost unnoticed."},
        {"k": "Oil", "v": "A barrel sold for $20 in 2001 and $138 by 2008. Yergin: 86% of oil is still in the ground — scarcity stories ignore that.",
         "c": L, "say": "A barrel sold for twenty dollars in two thousand one and one hundred thirty-eight by two thousand eight. Yergin: eighty-six percent of oil is still in the ground. Scarcity stories ignore that."},
        {"k": "Japan aside", "v": "The book imagines a 1945 Japanese forecast of 15× growth, doubled lifespan, and decades under 6% unemployment — optimism that sounded insane and happened.",
         "c": G, "say": "The book imagines a nineteen forty-five Japanese forecast of fifteen times growth, doubled lifespan, and decades under six percent unemployment. Optimism that sounded insane, and happened."},
    ], D),
]},
{"id": "ch18", "title": "Believe Anything", "segments": [
    Div(18, "Believe Anything", [
        ("Stories are how we stitch incomplete facts into a feeling of control.",
         "Stories are how we stitch incomplete facts into a feeling of control."),
        ("The more you want the world to be predictable, the more fiction you will accept.",
         "The more you want the world to be predictable, the more fiction you will accept."),
    ], M),
    Sheet("stories", "COMING UP WITH REASONS", "Control we do not have", [
        {"k": "Active funds", "v": "85% of active mutual funds underperformed their benchmarks in the span the book cites.",
         "c": R, "say": "Eighty-five percent of active mutual funds underperformed their benchmarks in the span the book cites."},
        {"k": "Fed range", "v": "A Fed forecast once gave 1.6% to 2.8% growth as its band — then missed by more than 2%.",
         "c": D, "say": "A Fed forecast once gave one point six to two point eight percent growth as its band, then missed by more than two percent."},
        {"k": "NASA", "v": "A Pluto flyby forecast 99.99998% accurate. Money is not a spacecraft. We still want that feeling.",
         "c": L, "say": "A Pluto flyby forecast was ninety-nine point nine nine nine nine eight percent accurate. Money is not a spacecraft. We still want that feeling."},
        {"k": "Startups", "v": "Kahneman: founders say at least 80% of the outcome depends on what they do inside the firm.",
         "c": M, "say": "Kahneman: founders say at least eighty percent of the outcome depends on what they do inside the firm."},
        {"k": "Appeal", "v": "A 1% chance of getting rich without effort is easy to over-weight if you cannot calibrate small odds.",
         "c": G, "say": "A one percent chance of getting rich without effort is easy to over-weight if you cannot calibrate small odds."},
    ], M),
]},
{"id": "ch19", "title": "All Together", "segments": [
    Div(19, "All Together", [
        ("The book compresses into a short list of behaviours, not a formula.",
         "The book compresses into a short list of behaviours, not a formula."),
        ("Go out of your way to find humility when things are going well.",
         "Go out of your way to find humility when things are going well."),
    ], G),
    List("together", "CHAPTER 19 · THE COMPRESSION", "What to actually do", [
        ("Go out of your way to find humility when things are going right, and forgiveness when they go wrong.",
         "Go out of your way to find humility when things are going right, and forgiveness when they go wrong."),
        ("Less ego, more wealth: define enough; save; leave room for error.",
         "Less ego, more wealth: define enough, save, leave room for error."),
        ("Manage your money in a way that helps you sleep at night.",
         "Manage your money in a way that helps you sleep at night."),
        ("Increase your time horizon. Time is the most powerful force in investing, as Buffett's calendar showed.",
         "Increase your time horizon. Time is the most powerful force in investing, as Buffett's calendar showed."),
        ("Become OK with a lot of things going wrong. Tails drive the outcome.",
         "Become OK with a lot of things going wrong. Tails drive the outcome."),
        ("Use money to gain control of your time. Avoid taking financial cues from people playing a different game.",
         "Use money to gain control of your time. Avoid taking financial cues from people playing a different game."),
        ("Respect the fee: volatility. Pay it if you want the return. Be nicer and less extreme.",
         "Respect the fee: volatility. Pay it if you want the return. Be nicer and less extreme."),
    ], G),
]},
{"id": "ch20", "title": "Confessions", "segments": [
    Div(20, "Confessions", [
        ("Housel publishes his own household rules so the book is not a lecture from nowhere.",
         "Housel publishes his own household rules so the book is not a lecture from nowhere."),
        ("Independence is the goal. The strategy is whatever you will actually stick with.",
         "Independence is the goal. The strategy is whatever you will actually stick with."),
    ], OK),
    Sheet("house", "HOUSEL'S HOUSEHOLD (AS PRINTED)", "Not a universal prescription", [
        {"k": "Goal", "v": "Independence. Every saving and investing decision is pointed at not being a forced actor.",
         "c": G, "say": "The goal is independence. Every saving and investing decision is pointed at not being a forced actor."},
        {"k": "House", "v": "They keep a paid-for house as a large, conservative chunk — a reasonable, not maximally rational, choice.",
         "c": D, "say": "They keep a paid-for house as a large, conservative chunk. A reasonable, not maximally rational, choice."},
        {"k": "Stocks", "v": "Around 20% of assets outside the house in a mix they can hold. No leverage.",
         "c": L, "say": "Around twenty percent of assets outside the house in a mix they can hold. No leverage."},
        {"k": "Funds", "v": "He prefers low-cost index funds and notes about 85% of large active funds fail to beat their index over long spans.",
         "c": M, "say": "He prefers low-cost index funds and notes about eighty-five percent of large active funds fail to beat their index over long spans."},
        {"k": "Humility", "v": "The plan is what his family will stick with — not what a spreadsheet says is optimal this year.",
         "c": OK, "say": "The plan is what his family will stick with, not what a spreadsheet says is optimal this year."},
    ], OK, "Confessions chapter. His plan is not your plan."),
    S("recap", "pm_recap", {
        "kicker": "RECAP — THE BOOK ON ONE CARD",
        "title": "What to remember",
        "color": G,
        "items": [
            "Behaviour beats formulas; luck and risk are a pair.",
            "Name enough. Compounding needs time and survival.",
            "Tails drive returns; savings and unseen wealth are the real pile.",
            "Be reasonable. Leave room for error. You will change.",
            "Volatility is a fee. Do not copy another player's game.",
            "Pessimism seduces. Stories fake control. Independence is the point.",
        ],
        "closer": "Education, not advice. Consult a SEBI-registered adviser. Thanks for watching.",
    }, [
        "Behaviour beats formulas. Luck and risk are a pair.",
        "Name enough. Compounding needs time and survival.",
        "Tails drive returns. Savings and unseen wealth are the real pile.",
        "Be reasonable. Leave room for error. You will change.",
        "Volatility is a fee. Do not copy another player's game.",
        "Pessimism seduces. Stories fake control. Independence is the point.",
        "This is education, not advice. Consult a SEBI-registered adviser. Thanks for watching.",
    ]),
]},
]

from more import attach
attach(CHAPTERS, Sheet, List, Dual, S, G, R, OK, M, L, D)
