"""Extra dense beats so the master can reach ~60 teaching minutes.

Same contract: every spoken claim is on the frame. Book-dated figures only.
"""

def attach(CHAPTERS, Sheet, List, Dual, S, G, R, OK, M, L, D):
    extra = {
"ch00": [
    Sheet("valet", "THE VALET STORY", "Gold coins into the Pacific", [
        {"k": "Job", "v": "Housel worked college years as a valet at a nice Los Angeles hotel.",
         "c": M, "say": "Housel worked his college years as a valet at a nice Los Angeles hotel."},
        {"k": "Guest", "v": "A tech executive who had designed a Wi-Fi router part, sold companies, and carried a thick stack of hundred-dollar bills.",
         "c": D, "say": "A frequent guest was a tech executive who had designed a part used in Wi-Fi routers, sold companies, and carried a thick stack of hundred-dollar bills."},
        {"k": "Coins", "v": "He sent a colleague to buy a few $1,000 gold coins, then skipped them into the ocean for fun.",
         "c": R, "say": "He sent a colleague to buy a few one-thousand-dollar gold coins, then skipped them into the ocean for fun."},
        {"k": "Lamp", "v": "He broke a $500 lamp, then handed over $5,000 and told the manager never to insult him again.",
         "c": D, "say": "He broke a five-hundred-dollar lamp, then handed over five thousand dollars and told the manager never to insult him again."},
        {"k": "End", "v": "The behaviour did not last. Housel later learned the man went broke.",
         "c": OK, "say": "The behaviour did not last. Housel later learned the man went broke."},
    ], D, "Introduction. Same lesson as Read versus Fuscone: behaviour can swamp credentials."),
],
"ch01": [
    List("crazy-rules", "CHAPTER 1 · TAKEAWAYS ON SCREEN", "No one is crazy — they are local", [
        ("People's money views are a product of when they were born, what they lived, and what they needed.",
         "People's money views are a product of when they were born, what they lived, and what they needed."),
        ("Do not expect a 1970s inflation scar and a 1990s bull-market childhood to produce the same investor.",
         "Do not expect a nineteen seventies inflation scar and a nineteen nineties bull-market childhood to produce the same investor."),
        ("A 'crazy' choice is often a rational answer to a room you have never stood in.",
         "A crazy choice is often a rational answer to a room you have never stood in."),
        ("Your job is not to mock the lottery ticket. It is to notice that your own history is also a tiny sample.",
         "Your job is not to mock the lottery ticket. It is to notice that your own history is also a tiny sample."),
    ], M),
],
"ch02": [
    Sheet("bill-paul", "LUCK IS NOT A FOOTNOTE", "The same table, different exits", [
        {"k": "Microsoft", "v": "Gates and Allen turned a rare high-school computer into a company. That is skill plus a door that almost nobody else had.",
         "c": OK, "say": "Gates and Allen turned a rare high-school computer into a company. That is skill plus a door that almost nobody else had."},
        {"k": "Kent", "v": "Kent Evans sat at the same table and never got the second act. Risk is luck's twin, not its opposite.",
         "c": R, "say": "Kent Evans sat at the same table and never got the second act. Risk is luck's twin, not its opposite."},
        {"k": "Praise", "v": "Be slower to praise winners as geniuses and slower to damn losers as fools.",
         "c": M, "say": "Be slower to praise winners as geniuses and slower to damn losers as fools."},
        {"k": "Copying", "v": "Copying a winner's leverage copies their unseen risk, not just their return.",
         "c": D, "say": "Copying a winner's leverage copies their unseen risk, not just their return."},
    ], L),
],
"ch03": [
    Sheet("enough-math", "THE HOURLY FIGURE", "Why $100 million still felt small", [
        {"k": "$100 million", "v": "The book: a fortune that size generates almost $600 an hour, 24 hours a day.",
         "c": D, "say": "The book: a fortune that size generates almost six hundred dollars an hour, twenty-four hours a day."},
        {"k": "Still reaching", "v": "Gupta still wanted the next rung. Comparison, not poverty, drove the extra risk.",
         "c": R, "say": "Gupta still wanted the next rung. Comparison, not poverty, drove the extra risk."},
        {"k": "Madoff legal", "v": "Twenty-five to fifty million a year, legally, was already 'enough' by any household standard. It was not enough for his identity.",
         "c": M, "say": "Twenty-five to fifty million a year, legally, was already enough by any household standard. It was not enough for his identity."},
        {"k": "Rule on screen", "v": "There is no reason to risk what you have and need for what you do not have and do not need.",
         "c": OK, "say": "There is no reason to risk what you have and need for what you do not have and do not need."},
    ], R),
],
"ch04": [
    List("compound-rules", "WHAT COMPOUNDING DEMANDS", "Printed lessons, not a rate chase", [
        ("Most of an exponential's visible work happens in the last years. Stopping early throws away the pile.",
         "Most of an exponential's visible work happens in the last years. Stopping early throws away the pile."),
        ("A good rate for a long time beats a spectacular rate for a short time — Simons versus Buffett in the book.",
         "A good rate for a long time beats a spectacular rate for a short time. That is Simons versus Buffett in the book."),
        ("You cannot feel compounding with linear intuition. That is why people quit in year eight.",
         "You cannot feel compounding with linear intuition. That is why people quit in year eight."),
        ("The practical move is staying invested and unbroken — not hunting a 66% personal rate.",
         "The practical move is staying invested and unbroken, not hunting a sixty-six percent personal rate."),
    ], G),
],
"ch05": [
    List("survive-list", "SURVIVAL CHECKLIST", "Staying wealthy on one card", [
        ("Frugality, cash, and low leverage are how you avoid becoming Rick Guerin in a two-year crash.",
         "Frugality, cash, and low leverage are how you avoid becoming Rick Guerin in a two-year crash."),
        ("A 70% drop is a fee if you can wait. It is ruin if a lender can call the loan.",
         "A seventy percent drop is a fee if you can wait. It is ruin if a lender can call the loan."),
        ("Plan for 4% years even if you hope for 8%. Room between those numbers is the strategy.",
         "Plan for four percent years even if you hope for eight. Room between those numbers is the strategy."),
        ("Getting rich and staying rich need different personalities. Do not let offense run the whole life.",
         "Getting rich and staying rich need different personalities. Do not let offense run the whole life."),
    ], OK),
],
"ch06": [
    Sheet("vc-again", "TAILS ARE NORMAL", "Failure is not a glitch in the system", [
        {"k": "VC 65%", "v": "Most venture deals lose money. That is the design, not an accident.",
         "c": R, "say": "Most venture deals lose money. That is the design, not an accident."},
        {"k": "Public 40%", "v": "Forty percent of Russell 3000 names lost 70% and never recovered — inside a 'boring' index.",
         "c": D, "say": "Forty percent of Russell three thousand names lost seventy percent and never recovered, inside a boring index."},
        {"k": "4% / 7%", "v": "Bessembinder's about 4% of listed firms, and J.P. Morgan's 7% of the Russell, are why diversification exists.",
         "c": L, "say": "Bessembinder's about four percent of listed firms, and J.P. Morgan's seven percent of the Russell, are why diversification exists."},
        {"k": "Sue", "v": "Missing the ugly 22% of months cost Jim and Tom roughly 40% of Sue's pile.",
         "c": OK, "say": "Missing the ugly twenty-two percent of months cost Jim and Tom roughly forty percent of Sue's pile."},
        {"k": "Job", "v": "Your job is to still be invested when the handful of winners show up.",
         "c": G, "say": "Your job is to still be invested when the handful of winners show up."},
    ], L),
],
"ch07": [
    Sheet("jobs-flip", "WORK FOLLOWED US HOME", "From hands to heads", [
        {"k": "1870 mix", "v": "Economist Robert Gordon: 46% agriculture, 35% crafts or manufacturing. Few jobs were 'think all day.'",
         "c": D, "say": "Economist Robert Gordon: forty-six percent agriculture, thirty-five percent crafts or manufacturing. Few jobs were think all day."},
        {"k": "Today", "v": "38% of jobs are managers, officials, and professionals. Another 41% are service jobs that live in your head.",
         "c": L, "say": "Thirty-eight percent of jobs are now managers, officials, and professionals. Another forty-one percent are service jobs that live in your head."},
        {"k": "Clock", "v": "Factory work ended at the gate. Decision work does not. That is why extra income did not buy extra peace.",
         "c": M, "say": "Factory work ended at the gate. Decision work does not. That is why extra income did not buy extra peace."},
        {"k": "Cancel", "v": "Bigger houses and faster cars, plus less control of time, can cancel. Happiness did not clearly rise with the $29k to $62k jump.",
         "c": R, "say": "Bigger houses and faster cars, plus less control of time, can cancel. Happiness did not clearly rise with the twenty-nine thousand to sixty-two thousand jump."},
        {"k": "Use of money", "v": "The highest-return purchase in the chapter is control of your waking hours.",
         "c": OK, "say": "The highest-return purchase in the chapter is control of your waking hours."},
    ], G),
    List("freedom-do", "FREEDOM · WHAT TO DO", "Independence is the dividend", [
        ("Save for options, not only for a sofa. Options are how you refuse a bad boss or a forced sale.",
         "Save for options, not only for a sofa. Options are how you refuse a bad boss or a forced sale."),
        ("A modest life you control can beat a larger life that owns your calendar.",
         "A modest life you control can beat a larger life that owns your calendar."),
        ("Housel's $12,000 at 22 was not a fortune. It was a permission slip to quit.",
         "Housel's twelve thousand dollars at twenty-two was not a fortune. It was a permission slip to quit."),
    ], OK),
],
"ch08": [
    Dual("car-split", "HUMILITY VERSUS THE BUMPER", "What you think you bought vs what they saw",
        {"name": "What you wanted", "tag": "inside your head", "c": D, "lines": [
            ("Respect, status, proof you made it.",
             "What you wanted: respect, status, proof you made it."),
            ("A $100,000 car as a loud résumé.",
             "A one hundred thousand dollar car as a loud résumé."),
        ]},
        {"name": "What they saw", "tag": "from the sidewalk", "c": M, "lines": [
            ("The car. Not your skill, not your savings rate, not your name.",
             "What they saw: the car. Not your skill, not your savings rate, not your name."),
            ("They may want the same car next. You were the billboard, not the hero.",
             "They may want the same car next. You were the billboard, not the hero."),
            ("If admiration was the goal, unspent wealth buys more of it over decades than chrome does in a minute.",
             "If admiration was the goal, unspent wealth buys more of it over decades than chrome does in a minute."),
        ]}, D),
    List("car-rules", "CAR PARADOX · RULES", "Keep the respect trade honest", [
        ("Spending to be liked is a tax. The audience is looking at the object.",
         "Spending to be liked is a tax. The audience is looking at the object."),
        ("Rich and wealthy look identical at a stoplight. Only the unspent pile is wealth.",
         "Rich and wealthy look identical at a stoplight. Only the unspent pile is wealth."),
        ("If the car requires debt that can force a sale, you bought the opposite of freedom.",
         "If the car requires debt that can force a sale, you bought the opposite of freedom."),
    ], D),
],
"ch09": [
    Dual("iceberg", "VISIBLE VERSUS INVISIBLE", "Why we copy the wrong neighbor",
        {"name": "What is visible", "tag": "easy to copy", "c": D, "lines": [
            ("Cars, watches, additions, vacations posted online.",
             "What is visible: cars, watches, additions, vacations posted online."),
            ("That spending is the opposite of wealth. It is wealth converted into stuff.",
             "That spending is the opposite of wealth. It is wealth converted into stuff."),
        ]},
        {"name": "What is hidden", "tag": "the actual pile", "c": OK, "lines": [
            ("Brokerage lots, paid-off houses, unused credit lines, a job you can quit.",
             "What is hidden: brokerage lots, paid-off houses, unused credit lines, a job you can quit."),
            ("You cannot screenshot someone else's savings rate. So you copy their burn rate instead.",
             "You cannot screenshot someone else's savings rate. So you copy their burn rate instead."),
            ("The 60% drop in energy per dollar of G.D.P. is the same shape: the win is the waste you do not see.",
             "The sixty percent drop in energy per dollar of G.D.P. is the same shape: the win is the waste you do not see."),
        ]}, M),
    List("hidden-do", "HIDDEN WEALTH · RULES", "Judge reserves, not chrome", [
        ("When you see a nice lifestyle, remember you are seeing the expense, not the net worth.",
         "When you see a nice lifestyle, remember you are seeing the expense, not the net worth."),
        ("The most valuable assets do not photograph well. That is the point.",
         "The most valuable assets do not photograph well. That is the point."),
        ("Building wealth is often the art of looking poorer than you are, on purpose.",
         "Building wealth is often the art of looking poorer than you are, on purpose."),
    ], OK),
],
"ch10": [
    Sheet("save-more", "WHY SAVING BEATS A CLEVER RETURN", "The gap is the strategy", [
        {"k": "Math", "v": "Past a modest income, cutting spending 10% can matter more than finding an extra 1% of return.",
         "c": G, "say": "Past a modest income, cutting spending ten percent can matter more than finding an extra one percent of return."},
        {"k": "Ego", "v": "Wealth is the gap between ego and income. Raise income or lower ego. Both widen the gap.",
         "c": M, "say": "Wealth is the gap between ego and income. Raise income or lower ego. Both widen the gap."},
        {"k": "No target", "v": "You do not need a named purchase to justify saving. Flexibility is the purchase.",
         "c": L, "say": "You do not need a named purchase to justify saving. Flexibility is the purchase."},
        {"k": "Luck later", "v": "Savings is how you survive the unplanned: a job loss, a medical bill, a market you want to buy.",
         "c": OK, "say": "Savings is how you survive the unplanned: a job loss, a medical bill, a market you want to buy."},
        {"k": "Everyone", "v": "Two households with the same salary can have opposite wealth if expectations differ.",
         "c": D, "say": "Two households with the same salary can have opposite wealth if expectations differ."},
    ], OK),
    List("save-do", "SAVE MONEY · RULES", "Build the gap on purpose", [
        ("Increase the savings rate before you hunt a fancier strategy.",
         "Increase the savings rate before you hunt a fancier strategy."),
        ("Hidden lifestyle cuts are more reliable than promised alpha.",
         "Hidden lifestyle cuts are more reliable than promised alpha."),
        ("Save because your future self will need room, not because a spreadsheet named a yacht.",
         "Save because your future self will need room, not because a spreadsheet named a yacht."),
    ], G),
    Sheet("efficiency", "SAVINGS IS THE M.P.G. OF MONEY", "Control versus hoped-for returns", [
        {"k": "Energy", "v": "U.S. energy per dollar of G.D.P. is 60% lower than 1950. Average MPG of vehicles on the road has doubled since 1975.",
         "c": L, "say": "U.S. energy per dollar of G.D.P. is sixty percent lower than nineteen fifty. Average miles per gallon of vehicles on the road has doubled since nineteen seventy-five."},
        {"k": "Taurus", "v": "A 1989 Ford Taurus: 18.0 MPG. A 2019 Chevy Suburban: 18.1 MPG. Efficiency moved the world more than geology.",
         "c": D, "say": "A nineteen eighty-nine Ford Taurus: eighteen point zero miles per gallon. A twenty nineteen Chevy Suburban: eighteen point one. Efficiency moved the world more than geology."},
        {"k": "Oil since 1975", "v": "U.S. oil and gas production up 65% since 1975, while conservation more than doubled what we can do with that energy.",
         "c": G, "say": "U.S. oil and gas production is up sixty-five percent since nineteen seventy-five, while conservation more than doubled what we can do with that energy."},
        {"k": "8% vs 12%", "v": "Book: if you earn 8% and I earn 12%, but I need half as much to be happy, I can be better off as the worse investor.",
         "c": M, "say": "The book: if you earn eight percent and I earn twelve, but I need half as much to be happy, I can be better off as the worse investor."},
        {"k": "0.1%", "v": "Professionals grind for 0.1% of extra return while two or three full points of lifestyle bloat sit unused.",
         "c": R, "say": "Professionals grind for zero point one percent of extra return while two or three full points of lifestyle bloat sit unused."},
    ], OK, "Chapter 10, as printed. Not a live energy forecast."),
],
"ch11": [
    Sheet("reasonable-more", "WHY REASONABLE WINS", "A plan you will not abandon", [
        {"k": "50/50 days", "v": "One-day U.S. market odds about 50/50. A rational robot still has to live through the red days.",
         "c": D, "say": "One-day U.S. market odds are about fifty-fifty. A rational robot still has to live through the red days."},
        {"k": "68 / 88 / 100", "v": "About 68% of one-year periods, 88% of ten-year, 100% of twenty-year so far — if you stayed.",
         "c": G, "say": "About sixty-eight percent of one-year periods, eighty-eight percent of ten-year, one hundred percent of twenty-year so far, if you stayed."},
        {"k": "Love", "v": "Loving a slightly imperfect strategy is how you capture those long-horizon odds.",
         "c": M, "say": "Loving a slightly imperfect strategy is how you capture those long-horizon odds."},
        {"k": "Cold rational", "v": "A spreadsheet-perfect mix you dump at minus 30% is not rational. It is unused.",
         "c": R, "say": "A spreadsheet-perfect mix you dump at minus thirty percent is not rational. It is unused."},
    ], M),
    List("reasonable-do", "REASONABLE · RULES", "Optimise for sleep and stickiness", [
        ("Pick an asset mix you can explain to yourself on a bad Tuesday.",
         "Pick an asset mix you can explain to yourself on a bad Tuesday."),
        ("Home bias, a paid-off house, extra cash — if they keep you invested, they can be reasonable.",
         "Home bias, a paid-off house, extra cash: if they keep you invested, they can be reasonable."),
        ("The edge is not brilliance. The edge is still being there in year twenty.",
         "The edge is not brilliance. The edge is still being there in year twenty."),
    ], OK),
],
"ch12": [
    Sheet("surprise-more", "HISTORY IS A LIST OF SURPRISES", "Do not treat the last war as the next one", [
        {"k": "102 drops", "v": "More than 10% off a recent high, at least 102 times. Surprise is the base rate.",
         "c": D, "say": "The market fell more than ten percent from a recent high at least one hundred two times. Surprise is the base rate."},
        {"k": "99.9%", "v": "Roughly 99.9% of companies ever created went out of business. Failure is normal.",
         "c": R, "say": "Roughly ninety-nine point nine percent of companies ever created went out of business. Failure is normal."},
        {"k": "7% inflation", "v": "Inflation over 7% in 20 separate years. Your parents' price world is not a law.",
         "c": M, "say": "Inflation exceeded seven percent in twenty separate years. Your parents' price world is not a law."},
        {"k": "Student debt", "v": "$1.6 trillion of student loans, 10.8% default — a mass product the 1950s planner did not have.",
         "c": L, "say": "One point six trillion dollars of student loans, ten point eight percent default. A mass product the nineteen fifties planner did not have."},
        {"k": "This time", "v": "Templeton's warning still allows that it is different at least 20% of the time. Plan for both.",
         "c": OK, "say": "Templeton's warning still allows that it is different at least twenty percent of the time. Plan for both."},
    ], D),
    List("surprise-do", "SURPRISE · RULES", "Forecast less, buffer more", [
        ("The next big event will not be in last decade's textbook. Room for error is how you admit that.",
         "The next big event will not be in last decade's textbook. Room for error is how you admit that."),
        ("Do not require a precise story of 2035. Require a life that survives a story you did not write.",
         "Do not require a precise story of twenty thirty-five. Require a life that survives a story you did not write."),
    ], M),
],
"ch13": [
    Sheet("error-more", "ROOM FOR ERROR IN NUMBERS", "The mean is not the life you live", [
        {"k": "6.8%", "v": "About 6.8% a year after inflation since the 1870s — an average that hides years that feel like ruin.",
         "c": G, "say": "About six point eight percent a year after inflation since the eighteen seventies. An average that hides years that feel like ruin."},
        {"k": "25–50%", "v": "Projects run 25% to 50% over budget. Your retirement math should assume the same slop.",
         "c": D, "say": "Projects run twenty-five to fifty percent over budget. Your retirement math should assume the same slop."},
        {"k": "95/5", "v": "A 95% bet will still hit the 5% in a long life. If the 5% is bankruptcy, the bet is illegal for you.",
         "c": R, "say": "A ninety-five percent bet will still hit the five percent in a long life. If the five percent is bankruptcy, the bet is illegal for you."},
        {"k": "Taleb", "v": "Risk-loving and ruin-averse can coexist. That is the adult version of room for error.",
         "c": M, "say": "Risk-loving and ruin-averse can coexist. That is the adult version of room for error."},
    ], OK),
    List("error-do", "ROOM FOR ERROR · RULES", "Leave slack on purpose", [
        ("Save more than the model. Spend less than the peak year. Borrow less than the bank offers.",
         "Save more than the model. Spend less than the peak year. Borrow less than the bank offers."),
        ("A plan that only works if every assumption is right is not a plan. It is a wish.",
         "A plan that only works if every assumption is right is not a plan. It is a wish."),
    ], G),
],
"ch14": [
    Sheet("change-more", "YOU WILL NOT STAY THIS PERSON", "The end-of-history illusion", [
        {"k": "Major", "v": "Only 27% of college graduates work in a job related to their major. Identity is not a 40-year contract.",
         "c": M, "say": "Only twenty-seven percent of college graduates work in a job related to their major. Identity is not a forty-year contract."},
        {"k": "Sunk identity", "v": "'I am a person who holds this stock' is how people refuse to sell a dead thesis.",
         "c": R, "say": "I am a person who holds this stock is how people refuse to sell a dead thesis."},
        {"k": "Age 22 vows", "v": "A 40-year financial vow made at 22 assumes a stranger will thank you. Maybe they will not.",
         "c": D, "say": "A forty-year financial vow made at twenty-two assumes a stranger will thank you. Maybe they will not."},
        {"k": "Review", "v": "Revisit goals every few years. Moderate plans survive personality drift better than extremes.",
         "c": OK, "say": "Revisit goals every few years. Moderate plans survive personality drift better than extremes."},
    ], M),
    List("change-do", "YOU'LL CHANGE · RULES", "Leave yourself an exit that is not failure", [
        ("Avoid careers, houses, and portfolios that only work if you never change your mind.",
         "Avoid careers, houses, and portfolios that only work if you never change your mind."),
        ("Changing a goal is not weakness. Pretending you are finished evolving is.",
         "Changing a goal is not weakness. Pretending you are finished evolving is."),
    ], L),
],
"ch15": [
    Sheet("fee-more", "PAY THE FEE OR BUY LESS RETURN", "Drawdowns are the invoice", [
        {"k": "11%", "v": "About 11% a year, 1950–2019, came bundled with long stretches 5% or more below an old high.",
         "c": G, "say": "About eleven percent a year from nineteen fifty to twenty nineteen came bundled with long stretches five percent or more below an old high."},
        {"k": "Netflix 94%", "v": "More than 35,000% total return, below the old high on 94% of days. The fee was almost every morning.",
         "c": L, "say": "More than thirty-five thousand percent total return, below the old high on ninety-four percent of days. The fee was almost every morning."},
        {"k": "Monster 95%", "v": "319,000% from 1995–2018, below the previous high 95% of the time.",
         "c": M, "say": "Three hundred nineteen thousand percent from nineteen ninety-five to twenty eighteen, below the previous high ninety-five percent of the time."},
        {"k": "Steal", "v": "Wanting 11% with no drawdowns is the market version of stealing the $30,000 car.",
         "c": R, "say": "Wanting eleven percent with no drawdowns is the market version of stealing the thirty-thousand-dollar car."},
        {"k": "2008", "v": "More than $8 trillion of housing wealth and about $6.2 trillion of household wealth gone in the window the book cites — that was a fee, loudly collected.",
         "c": D, "say": "More than eight trillion of housing wealth and about six point two trillion of household wealth gone in the window the book cites. That was a fee, loudly collected."},
    ], R),
    List("fee-do", "NOTHING'S FREE · RULES", "Choose the product, then pay", [
        ("If you want equity-like returns, budget for equity-like nausea. Do not call it a bug.",
         "If you want equity-like returns, budget for equity-like nausea. Do not call it a bug."),
        ("If you will not pay, buy a quieter asset and accept a quieter payoff. That is honest.",
         "If you will not pay, buy a quieter asset and accept a quieter payoff. That is honest."),
    ], OK),
],
"ch16": [
    Sheet("games-more", "CISCO WAS TWO GAMES AT $60", "Do not import another player's scoreboard", [
        {"k": "300%", "v": "Cisco rose 300% in 1999 to $60. Valuation about $600 billion.",
         "c": D, "say": "Cisco rose three hundred percent in nineteen ninety-nine to sixty dollars. Valuation about six hundred billion."},
        {"k": "Trader", "v": "A one-week momentum trader can be right at $60. That does not make $60 a 30-year entry.",
         "c": L, "say": "A one-week momentum trader can be right at sixty dollars. That does not make sixty dollars a thirty-year entry."},
        {"k": "120%", "v": "Average mutual fund turnover about 120% a year — many holders were not 'investors.'",
         "c": M, "say": "Average mutual fund turnover about one hundred twenty percent a year. Many holders were not investors."},
        {"k": "Bubble path", "v": "Short-term players set the print. Long-term owners treat the print as wisdom. That is how bubbles recruit.",
         "c": R, "say": "Short-term players set the print. Long-term owners treat the print as wisdom. That is how bubbles recruit."},
    ], L),
    List("games-do", "YOU AND ME · RULES", "Name your time horizon out loud", [
        ("Write whether you are playing weeks, years, or decades before you copy a price take.",
         "Write whether you are playing weeks, years, or decades before you copy a price take."),
        ("Hot takes from a different game are not information. They are someone else's payoff function.",
         "Hot takes from a different game are not information. They are someone else's payoff function."),
    ], G),
],
"ch17": [
    Sheet("pess-more", "PROGRESS IS QUIET", "Why the crash owns the story", [
        {"k": "1% news", "v": "A 1% rise is a mention. A 1% fall is a headline. Attention is not a fair sample.",
         "c": D, "say": "A one percent rise is a mention. A one percent fall is a headline. Attention is not a fair sample."},
        {"k": "2.5%", "v": "Only 2.5% of Americans owned stocks at the 1929 crash. The memory is national anyway.",
         "c": M, "say": "Only two point five percent of Americans owned stocks at the nineteen twenty-nine crash. The memory is national anyway."},
        {"k": "Heart 70%", "v": "Deaths from heart disease down more than 70% since 1965 — slow, so it barely feels like news.",
         "c": OK, "say": "Deaths from heart disease down more than seventy percent since nineteen sixty-five. Slow, so it barely feels like news."},
        {"k": "40 vs 140", "v": "A 40% drop in months is a saga. A 140% gain over six years is a shrug.",
         "c": R, "say": "A forty percent drop in months is a saga. A one hundred forty percent gain over six years is a shrug."},
        {"k": "Oil 86%", "v": "Yergin: 86% of oil still in the ground. Scarcity stories skip the residual.",
         "c": L, "say": "Yergin: eighty-six percent of oil is still in the ground. Scarcity stories skip the residual."},
    ], D),
    List("pess-do", "PESSIMISM · RULES", "Do not let the loud side monopolise the file", [
        ("For every crash story, ask what slow compounding happened in the same decades.",
         "For every crash story, ask what slow compounding happened in the same decades."),
        ("Optimism can sound naive and still be the base rate of a growing economy.",
         "Optimism can sound naive and still be the base rate of a growing economy."),
    ], G),
],
"ch18": [
    Sheet("stories-more", "WE WANT A NASA STORY", "Money is not 99.99998% controllable", [
        {"k": "85%", "v": "About 85% of active funds underperformed their benchmarks in the span the book cites.",
         "c": R, "say": "About eighty-five percent of active funds underperformed their benchmarks in the span the book cites."},
        {"k": "Fed miss", "v": "A 1.6% to 2.8% growth band, then a miss of more than 2%. Official stories drift too.",
         "c": D, "say": "A one point six to two point eight percent growth band, then a miss of more than two percent. Official stories drift too."},
        {"k": "Pluto", "v": "A flyby at 99.99998% accuracy. We crave that feeling in markets and invent it.",
         "c": L, "say": "A flyby at ninety-nine point nine nine nine nine eight percent accuracy. We crave that feeling in markets and invent it."},
        {"k": "80%", "v": "Founders tell Kahneman that at least 80% of the outcome is what they do inside the firm.",
         "c": M, "say": "Founders tell Kahneman that at least eighty percent of the outcome is what they do inside the firm."},
        {"k": "1% lottery", "v": "A 1% tale of effortless riches is easy to over-weight if you cannot feel small probabilities.",
         "c": G, "say": "A one percent tale of effortless riches is easy to over-weight if you cannot feel small probabilities."},
    ], M),
    List("stories-do", "BELIEVE ANYTHING · RULES", "Keep the story thinner than the cash", [
        ("Prefer rules that survive a wrong story: save, diversify, avoid ruin, stay for tails.",
         "Prefer rules that survive a wrong story: save, diversify, avoid ruin, stay for tails."),
        ("When a forecast feels perfectly tight, remember the Fed miss and the 85% of funds.",
         "When a forecast feels perfectly tight, remember the Fed miss and the eighty-five percent of funds."),
    ], OK),
],
"ch19": [
    List("together-more", "ALL TOGETHER · SECOND PASS", "The behaviours again, slower", [
        ("Humility in good times, forgiveness in bad. Outcomes mix luck into skill.",
         "Humility in good times, forgiveness in bad. Outcomes mix luck into skill."),
        ("Define enough. Save more than is fashionable. Leave slack.",
         "Define enough. Save more than is fashionable. Leave slack."),
        ("Sleep is a constraint. If the plan wrecks sleep, it will wreck compounding.",
         "Sleep is a constraint. If the plan wrecks sleep, it will wreck compounding."),
        ("Lengthen the horizon. Buffett's calendar is the exhibit.",
         "Lengthen the horizon. Buffett's calendar is the exhibit."),
        ("Accept that many things will fail. Own a wide enough net for the 4% and the 7%.",
         "Accept that many things will fail. Own a wide enough net for the four percent and the seven percent."),
        ("Buy time. Ignore players on another clock. Pay volatility if you want the return.",
         "Buy time. Ignore players on another clock. Pay volatility if you want the return."),
    ], G),
],
"ch20": [
    Sheet("confess-more", "WHY HE PUBLISHES THE PLAN", "A confession is not a command", [
        {"k": "Not advice", "v": "These are Housel's household rules. They are evidence of 'reasonable,' not a model portfolio.",
         "c": M, "say": "These are Housel's household rules. They are evidence of reasonable, not a model portfolio."},
        {"k": "Independence", "v": "Every dollar is aimed at not being forced — not at winning a neighbor's comparison.",
         "c": G, "say": "Every dollar is aimed at not being forced, not at winning a neighbor's comparison."},
        {"k": "House + 20%", "v": "A paid house plus about 20% of other assets, no leverage, index-heavy — chosen for stickiness.",
         "c": L, "say": "A paid house plus about twenty percent of other assets, no leverage, index-heavy, chosen for stickiness."},
        {"k": "85% funds", "v": "He cites about 85% of large active funds missing the index over long spans as a reason for simplicity.",
         "c": D, "say": "He cites about eighty-five percent of large active funds missing the index over long spans as a reason for simplicity."},
    ], OK),
],
}

    extra2 = {
"ch01": [
    List("crazy-close", "CHAPTER 1 · CLOSE", "Your sample is not the world", [
        ("A Depression childhood and a 1990s bull-market childhood are different operating systems.",
         "A Depression childhood and a nineteen nineties bull-market childhood are different operating systems."),
        ("People buy lottery tickets for a story of control, not because they failed a probability class.",
         "People buy lottery tickets for a story of control, not because they failed a probability class."),
        ("Respect the other room. Then notice that your own room is also small.",
         "Respect the other room. Then notice that your own room is also small."),
        ("The chapter's mercy: nobody is crazy. They are local.",
         "The chapter's mercy: nobody is crazy. They are local."),
    ], M),
],
"ch02": [
    List("luck-close", "CHAPTER 2 · CLOSE", "Hold skill loosely", [
        ("Bill Gates got a computer. Kent Evans sat at the same table and did not get a second act.",
         "Bill Gates got a computer. Kent Evans sat at the same table and did not get a second act."),
        ("Yahoo's Facebook offer is genius or arrogance depending on a future nobody knew in two thousand six.",
         "Yahoo's Facebook offer is genius or arrogance depending on a future nobody knew in two thousand six."),
        ("When you copy a winner, you may be copying an unseen accident, not a method.",
         "When you copy a winner, you may be copying an unseen accident, not a method."),
        ("The book's line again: nothing is as good or as bad as it looks.",
         "The book's line again: nothing is as good or as bad as it looks."),
    ], L),
],
"ch03": [
    List("enough-close", "CHAPTER 3 · CLOSE", "Write enough before the ladder moves", [
        ("A rookie on five hundred thousand can feel poor next to a three hundred forty million year.",
         "A rookie on five hundred thousand can feel poor next to a three hundred forty million year."),
        ("Gupta already had a one hundred million fortune. The extra risk was comparison, not rent.",
         "Gupta already had a one hundred million fortune. The extra risk was comparison, not rent."),
        ("Madoff already had a legal fortune. The fraud was identity, not necessity.",
         "Madoff already had a legal fortune. The fraud was identity, not necessity."),
        ("Name the people you will not disappoint. That list is a better finish line than a neighbor's net worth.",
         "Name the people you will not disappoint. That list is a better finish line than a neighbor's net worth."),
    ], R),
],
"ch04": [
    List("compound-close", "CHAPTER 4 · CLOSE", "Protect the calendar", [
        ("Most of Buffett's pile arrived after fifty because the years stacked, not because year sixty invented a new trick.",
         "Most of Buffett's pile arrived after fifty because the years stacked, not because year sixty invented a new trick."),
        ("The book's twenty-two percent thought experiment at age thirty still ends near twelve million, not eighty-four billion.",
         "The book's twenty-two percent thought experiment at age thirty still ends near twelve million, not eighty-four billion."),
        ("Simons's sixty-six percent is real and rare. Do not treat it as a personal template.",
         "Simons's sixty-six percent is real and rare. Do not treat it as a personal template."),
        ("The practical compounding skill is staying unbroken long enough for the curve to bend.",
         "The practical compounding skill is staying unbroken long enough for the curve to bend."),
    ], G),
],
"ch05": [
    Sheet("barbell", "OPTIMISM AND PARANOIA", "Two personalities, one life", [
        {"k": "Offense", "v": "Getting rich can require optimism, concentration, and a willingness to look foolish for a while.",
         "c": G, "say": "Getting rich can require optimism, concentration, and a willingness to look foolish for a while."},
        {"k": "Defense", "v": "Staying rich requires paranoia about ruin: cash, frugality, and no lender who can call you at the bottom.",
         "c": R, "say": "Staying rich requires paranoia about ruin: cash, frugality, and no lender who can call you at the bottom."},
        {"k": "Guerin", "v": "Rick Guerin was in the same early Buffett circle. Leverage turned a crash into an exit.",
         "c": D, "say": "Rick Guerin was in the same early Buffett circle. Leverage turned a crash into an exit."},
        {"k": "Switch", "v": "The book: do not let the personality that got you rich run the whole rest of the life.",
         "c": OK, "say": "The book: do not let the personality that got you rich run the whole rest of the life."},
        {"k": "Aim", "v": "Survive first. Compounding is only available to people who are still in the game.",
         "c": M, "say": "Survive first. Compounding is only available to people who are still in the game."},
    ], OK),
],
"ch06": [
    List("tails-close", "CHAPTER 6 · CLOSE", "Stay for the handful", [
        ("Most venture deals lose money. That is how the industry is built, not a scandal.",
         "Most venture deals lose money. That is how the industry is built, not a scandal."),
        ("Forty percent of Russell three thousand names lost seventy percent and never recovered, inside a boring index.",
         "Forty percent of Russell three thousand names lost seventy percent and never recovered, inside a boring index."),
        ("Sue captured the ugly months. Jim and Tom did not. The pile gap is the point.",
         "Sue captured the ugly months. Jim and Tom did not. The pile gap is the point."),
        ("Your job is not to be right every year. It is to still be invested when the few winners arrive.",
         "Your job is not to be right every year. It is to still be invested when the few winners arrive."),
    ], L),
],
"ch08": [
    Sheet("status", "RESPECT IS NOT TRANSFERABLE", "The paradox in one column", [
        {"k": "Wanted", "v": "People buy loud goods hoping the object will transfer respect onto the owner.",
         "c": D, "say": "People buy loud goods hoping the object will transfer respect onto the owner."},
        {"k": "Received", "v": "Observers usually stop at the object. They imagine themselves in the seat, not you.",
         "c": M, "say": "Observers usually stop at the object. They imagine themselves in the seat, not you."},
        {"k": "Debt", "v": "If the object is financed, you may have purchased the opposite of the freedom you wanted to display.",
         "c": R, "say": "If the object is financed, you may have purchased the opposite of the freedom you wanted to display."},
        {"k": "Quiet", "v": "Unspent wealth does not photograph. That is why it is easy to under-count and over-spend.",
         "c": OK, "say": "Unspent wealth does not photograph. That is why it is easy to under-count and over-spend."},
        {"k": "Move", "v": "If admiration was the goal, keep the assets that buy time. Chrome is a billboard for the factory.",
         "c": G, "say": "If admiration was the goal, keep the assets that buy time. Chrome is a billboard for the factory."},
    ], D),
],
"ch11": [
    Sheet("sleep", "REASONABLE CASH IS NOT A BUG", "A plan you will not dump", [
        {"k": "Perfect mix", "v": "A spreadsheet can tell you to stay fully invested. A human has to sleep through minus thirty percent.",
         "c": D, "say": "A spreadsheet can tell you to stay fully invested. A human has to sleep through minus thirty percent."},
        {"k": "Cash drag", "v": "Extra cash looks irrational until it is the reason you did not sell the rest.",
         "c": G, "say": "Extra cash looks irrational until it is the reason you did not sell the rest."},
        {"k": "House", "v": "A paid-off house can be a drag on paper and still be the reasonable glue for a family.",
         "c": L, "say": "A paid-off house can be a drag on paper and still be the reasonable glue for a family."},
        {"k": "Home bias", "v": "Owning more of what you understand can be reasonable if it keeps you from panic.",
         "c": M, "say": "Owning more of what you understand can be reasonable if it keeps you from panic."},
        {"k": "Score", "v": "The score is still being there in year twenty, not winning year one's efficiency contest.",
         "c": OK, "say": "The score is still being there in year twenty, not winning year one's efficiency contest."},
    ], M),
],
"ch14": [
    Sheet("sunk", "DO NOT MARRY A PAST GOAL", "Identity is a sunk cost too", [
        {"k": "Illusion", "v": "The end-of-history illusion: you see past change clearly and assume the future you is finished.",
         "c": M, "say": "The end-of-history illusion: you see past change clearly and assume the future you is finished."},
        {"k": "Major", "v": "Only twenty-seven percent of graduates work in a job related to their major. Careers drift.",
         "c": L, "say": "Only twenty-seven percent of graduates work in a job related to their major. Careers drift."},
        {"k": "Stock story", "v": "I am a person who holds this stock is how a dead thesis gets a second decade.",
         "c": R, "say": "I am a person who holds this stock is how a dead thesis gets a second decade."},
        {"k": "Vows", "v": "A forty-year financial vow at twenty-two is a letter to a stranger. Leave a stamp for revisions.",
         "c": D, "say": "A forty-year financial vow at twenty-two is a letter to a stranger. Leave a stamp for revisions."},
        {"k": "Moderate", "v": "Moderate plans survive personality drift. Extreme plans require you never to grow.",
         "c": OK, "say": "Moderate plans survive personality drift. Extreme plans require you never to grow."},
    ], M),
],
"ch16": [
    Sheet("bubble", "A BUBBLE IS TWO GAMES", "Same ticker, different payoff", [
        {"k": "Print", "v": "Short-term traders can be right about a print that is nonsense for a thirty-year holder.",
         "c": L, "say": "Short-term traders can be right about a print that is nonsense for a thirty-year holder."},
        {"k": "Cisco", "v": "Cisco at sixty dollars after a three hundred percent year was a trader's win and an owner's trap.",
         "c": D, "say": "Cisco at sixty dollars after a three hundred percent year was a trader's win and an owner's trap."},
        {"k": "Turnover", "v": "About one hundred twenty percent average fund turnover meant many 'holders' were not investing.",
         "c": M, "say": "About one hundred twenty percent average fund turnover meant many holders were not investing."},
        {"k": "Recruit", "v": "Bubbles recruit long-term money with short-term scoreboards. Name your clock before you copy.",
         "c": R, "say": "Bubbles recruit long-term money with short-term scoreboards. Name your clock before you copy."},
        {"k": "Rule", "v": "If you cannot say whether you are playing weeks or decades, you are playing someone else's game.",
         "c": OK, "say": "If you cannot say whether you are playing weeks or decades, you are playing someone else's game."},
    ], L),
],
"ch19": [
    Sheet("nicer", "BE NICER AND LESS EXTREME", "The last compression", [
        {"k": "Humility", "v": "When it is going well, hunt for the luck you are not crediting. That is how you stay kind.",
         "c": G, "say": "When it is going well, hunt for the luck you are not crediting. That is how you stay kind."},
        {"k": "Forgive", "v": "When it is going badly, hunt for the risk that was always there. That is how you stay sane.",
         "c": M, "say": "When it is going badly, hunt for the risk that was always there. That is how you stay sane."},
        {"k": "Sleep", "v": "If the plan wrecks sleep, it will wreck compounding. Sleep is a financial constraint.",
         "c": D, "say": "If the plan wrecks sleep, it will wreck compounding. Sleep is a financial constraint."},
        {"k": "Tails", "v": "Become OK with a lot going wrong. Own a net wide enough for the four percent and the seven percent.",
         "c": L, "say": "Become OK with a lot going wrong. Own a net wide enough for the four percent and the seven percent."},
        {"k": "Fee", "v": "Volatility is the fee. Pay it if you want the return. Skip the product if you will not pay.",
         "c": OK, "say": "Volatility is the fee. Pay it if you want the return. Skip the product if you will not pay."},
    ], G),
],
"ch09": [
    List("hidden-close", "CHAPTER 9 · CLOSE", "Copy the reserve, not the burn", [
        ("What you can see is the expense. What you cannot see is the net worth.",
         "What you can see is the expense. What you cannot see is the net worth."),
        ("Savings rates do not screenshot well. That is why people copy lifestyles instead.",
         "Savings rates do not screenshot well. That is why people copy lifestyles instead."),
        ("Looking poorer than you are can be a strategy, not a failure of taste.",
         "Looking poorer than you are can be a strategy, not a failure of taste."),
        ("Judge the iceberg. The boat is just the part that photographs.",
         "Judge the iceberg. The boat is just the part that photographs."),
    ], OK),
],
"ch13": [
    List("error-close", "CHAPTER 13 · CLOSE", "Leave slack on purpose", [
        ("A ninety-five percent bet still hits the five percent in a long life. If the five percent is ruin, skip it.",
         "A ninety-five percent bet still hits the five percent in a long life. If the five percent is ruin, skip it."),
        ("Projects run over budget. Your retirement math should assume the same slop.",
         "Projects run over budget. Your retirement math should assume the same slop."),
        ("Save more than the model. Borrow less than the bank offers.",
         "Save more than the model. Borrow less than the bank offers."),
        ("A plan that only works if every assumption is right is a wish.",
         "A plan that only works if every assumption is right is a wish."),
    ], OK),
],
"ch17": [
    List("pess-close", "CHAPTER 17 · CLOSE", "Do not let the crash own the file", [
        ("A one percent fall is a headline. A one percent rise is a mention. Attention is a biased sample.",
         "A one percent fall is a headline. A one percent rise is a mention. Attention is a biased sample."),
        ("Heart-disease deaths fell more than seventy percent since nineteen sixty-five, slowly, so it barely felt like news.",
         "Heart-disease deaths fell more than seventy percent since nineteen sixty-five, slowly, so it barely felt like news."),
        ("A forty percent drop in months is a saga. A one hundred forty percent gain over six years is a shrug.",
         "A forty percent drop in months is a saga. A one hundred forty percent gain over six years is a shrug."),
        ("Optimism can sound naive and still be the base rate of a growing economy.",
         "Optimism can sound naive and still be the base rate of a growing economy."),
    ], D),
],
"ch21": [],
}
    for k, segs in extra2.items():
        extra.setdefault(k, []).extend(segs)

    post = {
        "id": "ch21", "title": "Postscript",
        "segments": [
            S("ps1", "pm_sheet", {
                "kicker": "POSTSCRIPT · HOW THE U.S. CONSUMER WAS BUILT",
                "title": "August 1945: the war ends",
                "color": D,
                "note": "Housel postscript. Book-dated history, not a forecast.",
                "rows": [
                    {"k": "People", "v": "16 million Americans — 11% of the population — served. About 8 million were overseas. Average age 23.", "c": L},
                    {"k": "Home", "v": "Within 18 months all but 1.5 million were home and out of uniform.", "c": G},
                    {"k": "Housing", "v": "Fewer than 12,000 homes a month built in 1943 — less than one new home per American city.", "c": R},
                    {"k": "Fear", "v": "1946 Council of Economic Advisors to Truman: risk of a full-scale depression in the next one to four years.", "c": D},
                    {"k": "Jobs", "v": "Ships, tanks, and planes stopped almost overnight. Marriage spiked. Soldiers wanted a home and a job immediately.", "c": M},
                ],
            }, [
                "Sixteen million Americans, eleven percent of the population, served. About eight million were overseas. Average age twenty-three.",
                "Within eighteen months all but one point five million were home and out of uniform.",
                "Fewer than twelve thousand homes a month were built in nineteen forty-three, less than one new home per American city.",
                "In nineteen forty-six the Council of Economic Advisors warned Truman of a full-scale depression in the next one to four years.",
                "Ships, tanks, and planes stopped almost overnight. Marriage spiked. Soldiers wanted a home and a job immediately.",
            ]),
            S("ps2", "pm_sheet", {
                "kicker": "LOW RATES AND THE CONSUMER",
                "title": "Spending became policy",
                "color": G,
                "note": "Fed not independent until 1951, as the book states.",
                "rows": [
                    {"k": "0.38%", "v": "In 1942 the Fed said it would keep short-term rates at 0.38% to finance the war. They did not budge for seven years.", "c": G},
                    {"k": "Bills", "v": "Three-month Treasury yields stayed below 2% until the mid-1950s.", "c": L},
                    {"k": "War cost", "v": "The explicit aim: keep the cost of financing the equivalent of $6 trillion of war spending low.", "c": D},
                    {"k": "GI Bill", "v": "16 million veterans: often no money down, no interest in year one, payments that could beat rent.", "c": OK},
                    {"k": "Credit", "v": "First credit card 1950. Interest on debt, including cards, was tax deductible then. Household debt in the 1950s grew 1.5× faster than in the 2000s splurge.", "c": R},
                ],
            }, [
                "In nineteen forty-two the Fed said it would keep short-term rates at zero point three eight percent to finance the war. They did not budge for seven years.",
                "Three-month Treasury yields stayed below two percent until the mid nineteen fifties.",
                "The explicit aim: keep the cost of financing the equivalent of six trillion dollars of war spending low.",
                "The G.I. Bill: sixteen million veterans, often no money down, no interest in year one, payments that could beat rent.",
                "The first credit card arrived in nineteen fifty. Interest on debt, including cards, was tax deductible then. Household debt in the nineteen fifties grew one point five times faster than in the two thousands splurge.",
            ]),
            S("ps3", "pm_sheet", {
                "kicker": "WHAT THAT DID TO HOUSEHOLDS",
                "title": "Debt, homes, and a new normal",
                "color": M,
                "rows": [
                    {"k": "Debt now", "v": "Household debt-to-income just over 100% when Housel wrote. Through the 1950s–1970s it stayed below 60%.", "c": R},
                    {"k": "Own", "v": "Homeownership 47% in 1900, about there for four decades, 53% by 1945, 62% by 1970.", "c": G},
                    {"k": "Incomes", "v": "Real income for the bottom 20% grew by a nearly identical amount as the top 5% from 1950 to 1980.", "c": OK},
                    {"k": "Lesson", "v": "Today's consumer expectations were trained in a unique postwar machine — cheap credit, houses, and a culture that told people to spend.", "c": M},
                    {"k": "Use", "v": "Your grandparents' 'everyone had a house and a pension' is a specific era, not a human constant. Chapter 1 again.", "c": D},
                ],
            }, [
                "Household debt-to-income was just over one hundred percent when Housel wrote. Through the nineteen fifties to seventies it stayed below sixty percent.",
                "Homeownership was forty-seven percent in nineteen hundred, about there for four decades, fifty-three percent by nineteen forty-five, sixty-two percent by nineteen seventy.",
                "Real income for the bottom twenty percent grew by a nearly identical amount as the top five percent from nineteen fifty to nineteen eighty.",
                "Today's consumer expectations were trained in a unique postwar machine: cheap credit, houses, and a culture that told people to spend.",
                "Your grandparents' story that everyone had a house and a pension is a specific era, not a human constant. That is chapter one again.",
            ]),
            S("ps4", "pm_sheet", {
                "kicker": "THE BUYING SPREE",
                "title": "Cars, houses, and 40% more spending",
                "color": G,
                "note": "Postscript figures as printed.",
                "rows": [
                    {"k": "Cars", "v": "Commercial car and truck making nearly ceased 1942–1945. Then 21 million cars sold 1945–1949, another 37 million by 1955.", "c": L},
                    {"k": "Homes", "v": "Just under 2 million homes built 1940–1945. Then 7 million from 1945–1950, another 8 million by 1955.", "c": G},
                    {"k": "1950 spend", "v": "Fed to Truman, 1951: consumer spending plus residential construction about $203 billion — around 40% above 1944.", "c": D},
                    {"k": "Wages", "v": "Average wages doubled 1940–1948, then doubled again by 1963. The country got rich by making the poor less poor.", "c": OK},
                    {"k": "Top 1%", "v": "Share of national income after tax for the roughly $16,000-and-over group: from 13% to 7% by 1945, as cited.", "c": M},
                ],
            }, [
                "Commercial car and truck making nearly ceased from nineteen forty-two to forty-five. Then twenty-one million cars sold from forty-five to forty-nine, another thirty-seven million by nineteen fifty-five.",
                "Just under two million homes were built from nineteen forty to forty-five. Then seven million from forty-five to fifty, another eight million by fifty-five.",
                "The Fed wrote Truman in nineteen fifty-one: consumer spending plus residential construction about two hundred three billion dollars, around forty percent above nineteen forty-four.",
                "Average wages doubled from nineteen forty to forty-eight, then doubled again by nineteen sixty-three. The country got rich by making the poor less poor.",
                "The top group's share of national income after tax, the roughly sixteen thousand and over group, came down from thirteen percent to seven percent by nineteen forty-five.",
            ]),
            S("ps5", "pm_sheet", {
                "kicker": "EQUAL LIFESTYLES, THEN A CRACK",
                "title": "1945–1980 versus 1973",
                "color": R,
                "rows": [
                    {"k": "Women work", "v": "Women's labor force participation: 31% after the war, 37% by 1955, 40% by 1965.", "c": L},
                    {"k": "Chevys", "v": "Normal people drove Chevys, rich people Cadillacs — similar engines. Three TV stations put tens of millions in sync each night.", "c": G},
                    {"k": "Debt 5×", "v": "Household debt increased fivefold 1947–1957, but incomes rose fast and starting debt was low, so the ratio stayed manageable — still below 60% even after the 1970s.", "c": D},
                    {"k": "1973", "v": "Recession: unemployment highest since the 1930s. Inflation stayed high. Short-term rates 8% in 1973, up from 2.5% a decade earlier.", "c": R},
                    {"k": "Expectation", "v": "The crack: winds turned uneven, but expectations stayed in a 1945–1980 equality-of-lifestyle world. That gap still trains how people spend.", "c": M},
                ],
            }, [
                "Women's labor force participation: thirty-one percent after the war, thirty-seven percent by nineteen fifty-five, forty percent by nineteen sixty-five.",
                "Normal people drove Chevys, rich people Cadillacs, similar engines. Three TV stations put tens of millions in sync each night.",
                "Household debt increased fivefold from nineteen forty-seven to fifty-seven, but incomes rose fast and starting debt was low, so the ratio stayed manageable, still below sixty percent even after the nineteen seventies.",
                "Nineteen seventy-three: unemployment highest since the nineteen thirties. Inflation stayed high. Short-term rates eight percent, up from two point five percent a decade earlier.",
                "The crack: winds turned uneven, but expectations stayed in a nineteen forty-five to eighty equality-of-lifestyle world. That gap still trains how people spend.",
            ]),
            S("ps6", "pm_sheet", {
                "kicker": "WHY THE POSTSCRIPT EXISTS",
                "title": "Expectations outlived the era that trained them",
                "color": M,
                "note": "Postscript close. Book-dated history, not a forecast.",
                "rows": [
                    {"k": "Machine", "v": "Cheap credit, a housing boom, and a culture of spend built a specific American consumer after 1945.",
                     "c": G},
                    {"k": "Even years", "v": "From about 1950 to 1980, the bottom and the top could feel they were in the same lifestyle movie.",
                     "c": L},
                    {"k": "After", "v": "Winds turned uneven. Incomes and luck diverged. The 1945–1980 script did not update as fast.",
                     "c": R},
                    {"k": "Chapter 1", "v": "Your grandparents' 'normal' was a postwar policy accident, not a law of money. That is why no one is crazy.",
                     "c": M},
                    {"k": "Use", "v": "Do not copy a 1955 household as if it were a template. Copy the behaviour: enough, slack, and time.",
                     "c": OK},
                ],
            }, [
                "Cheap credit, a housing boom, and a culture of spend built a specific American consumer after nineteen forty-five.",
                "From about nineteen fifty to eighty, the bottom and the top could feel they were in the same lifestyle movie.",
                "Winds turned uneven. Incomes and luck diverged. The nineteen forty-five to eighty script did not update as fast.",
                "Your grandparents' normal was a postwar policy accident, not a law of money. That is why no one is crazy.",
                "Do not copy a nineteen fifty-five household as if it were a template. Copy the behaviour: enough, slack, and time.",
            ]),
        ],
    }

    extra.setdefault("ch18", []).append(
        List("stories-close", "CHAPTER 18 · CLOSE", "Keep the story thinner than the cash", [
            ("A Pluto flyby can be ninety-nine point nine nine nine nine eight percent accurate. A portfolio cannot.",
             "A Pluto flyby can be ninety-nine point nine nine nine nine eight percent accurate. A portfolio cannot."),
            ("About eighty-five percent of active funds missed their benchmarks in the span the book cites.",
             "About eighty-five percent of active funds missed their benchmarks in the span the book cites."),
            ("Founders tell Kahneman that at least eighty percent of the outcome is what they do inside the firm. Markets disagree.",
             "Founders tell Kahneman that at least eighty percent of the outcome is what they do inside the firm. Markets disagree."),
            ("Prefer rules that survive a wrong story: save, diversify, avoid ruin, stay for tails.",
             "Prefer rules that survive a wrong story: save, diversify, avoid ruin, stay for tails."),
        ], OK)
    )

    for ch in CHAPTERS:
        more = extra.get(ch["id"], [])
        if not more:
            continue
        ids = [s["id"] for s in ch["segments"]]
        if "recap" in ids:
            i = ids.index("recap")
            ch["segments"] = ch["segments"][:i] + more + ch["segments"][i:]
        else:
            ch["segments"].extend(more)
    CHAPTERS.append(post)
